const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');
const http = require('http');
const https = require('https');
const { app } = require('electron');
const findFreePort = require('find-free-port');
const log = require('./logger');
const dotenv = require('dotenv');

class BackendManager {
  constructor() {
    this.process = null;
    this.grpcPort = null;
    this.toolsDaemonPort = null;
    this.temporalFrontendPort = null;
    this.temporalUIPort = null;
    this.useTLS = process.env.DISABLE_TLS !== 'true'; // TLS enabled by default unless DISABLE_TLS=true
    this.isRunning = false;
    this.isShuttingDown = false;
    this.startupTimeout = 60000; // 60 seconds - Temporal initialization can be slow on first run
    this.shutdownTimeout = 25000; // 25 seconds - must be longer than Go's total shutdown (15s)
    this.isDevelopment = process.env.NODE_ENV === 'development'; // Added for development mode
    this.restartAttempts = 0;
    this.maxRestartAttempts = 5;
    this.restartDelay = 1000; // Start with 1 second delay
    this.intentionalShutdown = false; // Track if shutdown was intentional
    this.mockDriverConfig = null; // Store mock driver configuration
    this.instanceId = null; // Unique identifier for this instance (used in dev mode for process identification)

    // Load environment variables on initialization
    this.loadEnvironment();
  }

  parseShellEnvFile(filePath) {
    const parsed = {};
    if (!fs.existsSync(filePath)) {
      return parsed;
    }

    const content = fs.readFileSync(filePath, 'utf8');
    content.split('\n').forEach((line) => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) {
        return;
      }

      // Supports both:
      //   export KEY=value
      //   KEY=value
      const match = trimmed.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
      if (!match) {
        return;
      }

      const key = match[1];
      let value = match[2].trim();

      // Strip single or double quotes when present
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }

      parsed[key] = value;
    });

    return parsed;
  }

  applyPortsEnvironment() {
    const portsPath = path.join(__dirname, '../../.env.ports');
    const parsedPorts = this.parseShellEnvFile(portsPath);
    const keys = Object.keys(parsedPorts);

    if (keys.length === 0) {
      return;
    }

    // .env.ports is generated by dev scripts and should be the source of truth
    // for runtime port/db wiring in this worktree.
    keys.forEach((key) => {
      process.env[key] = parsedPorts[key];
    });

    const dbUrl = process.env.DATABASE_URL || '';
    let dbHost = '(unset)';
    let dbPort = '(unset)';
    try {
      if (dbUrl) {
        const u = new URL(dbUrl);
        dbHost = u.hostname || dbHost;
        dbPort = u.port || dbPort;
      }
    } catch (e) {
      // Ignore URL parse errors; we still log raw driver/port vars below.
    }

    log.info('[BackendManager] Applied .env.ports overrides', {
      path: portsPath,
      keys,
      databaseDriver: process.env.DATABASE_DRIVER || '(unset)',
      pgHost: process.env.PGHOST || dbHost,
      pgPort: process.env.PGPORT || dbPort,
      grpcPort: process.env.GRPC_PORT || '(unset)',
      toolsDaemonPort: process.env.TOOLS_DAEMON_PORT || '(unset)'
    });
  }

  loadEnvironment() {
    // Try to load root env files (.env first, then .env.local overrides)
    const envPath = path.join(__dirname, '../../.env');
    if (fs.existsSync(envPath)) {
      const result = dotenv.config({ path: envPath });
      if (result.parsed) {
        log.info('[BackendManager] Loaded environment from .env file');
        log.info('[BackendManager] Loaded vars:', Object.keys(result.parsed).join(', '));
      }
    }

    const envLocalPath = path.join(__dirname, '../../.env.local');
    if (fs.existsSync(envLocalPath)) {
      const result = dotenv.config({ path: envLocalPath, override: true });
      if (result.parsed) {
        log.info('[BackendManager] Loaded environment from .env.local file');
        log.info('[BackendManager] Loaded vars:', Object.keys(result.parsed).join(', '));
      }
    }

    // Load build-time config (generated by CI, contains runtime secrets for packaged app)
    try {
      const buildConfig = require('./build-config');
      let injected = [];
      for (const [key, value] of Object.entries(buildConfig)) {
        if (!process.env[key] && value) {
          process.env[key] = value;
          injected.push(key);
        }
      }
      if (injected.length > 0) {
        log.info('[BackendManager] Injected build config vars:', injected.join(', '));
      }
    } catch (e) {
      // build-config.js doesn't exist in development — this is expected
      log.debug('[BackendManager] No build-config.js found (expected in dev mode)');
    }

    // Normalize runtime env from generated worktree-specific ports/db file.
    // This avoids stale inherited shell env causing random cross-worktree DB drift.
    this.applyPortsEnvironment();
  }

  loadMockDriverConfig() {
    try {
      const configPath = path.join(app.getPath('userData'), 'mock-driver-config.json');
      if (fs.existsSync(configPath)) {
        const data = fs.readFileSync(configPath, 'utf8');
        this.mockDriverConfig = JSON.parse(data);
        log.info('[BackendManager] Loaded mock driver config:', this.mockDriverConfig);
      }
    } catch (error) {
      log.error('[BackendManager] Failed to load mock driver config:', error);
    }
  }

  /**
   * Clean up any orphaned backend processes from previous runs.
   * This can happen if the app crashed or was force-killed without proper cleanup.
   * Called on startup to ensure a clean state.
   * 
   * In development mode: Only kills processes matching our instanceId (reliant-{instanceId})
   * In production mode: Kills all orphaned reliant-backend processes
   */
  async cleanupOrphanedProcesses() {
    const { execSync } = require('child_process');
    
    // Compute instanceId early if not already set (for cleanup before getBinaryPath is called)
    if (!this.instanceId && this.isDevelopment) {
      const projectRoot = path.join(__dirname, '../..');
      const worktreeMatch = projectRoot.match(/\.reliant\/worktrees\/([^/]+)/);
      if (worktreeMatch) {
        this.instanceId = worktreeMatch[1];
      } else {
        this.instanceId = path.basename(projectRoot);
      }
    }
    
    log.info(`[BackendManager] Checking for orphaned processes (instanceId: ${this.instanceId || 'production'})`);
    
    try {
      if (process.platform === 'darwin' || process.platform === 'linux') {
        // In dev mode, look for our unique binary name: reliant-{instanceId}
        // In prod mode, look for reliant-backend
        const searchPattern = this.isDevelopment && this.instanceId
          ? `reliant-${this.instanceId}`
          : 'reliant-backend';
        
        try {
          // Get all matching processes
          const psResult = execSync(`ps aux | grep "${searchPattern}" | grep -v grep`, { 
            encoding: 'utf8', 
            timeout: 5000 
          }).trim();
          
          if (!psResult) {
            log.debug('[BackendManager] No orphaned processes found');
            return;
          }
          
          const lines = psResult.split('\n').filter(line => line.trim());
          const pidsToKill = [];
          
          for (const line of lines) {
            // Parse PID from ps output (format: "user PID %CPU %MEM ... command")
            const parts = line.trim().split(/\s+/);
            const pid = parts[1];
            
            // Skip our own process
            if (pid === String(this.process?.pid)) {
              continue;
            }
            
            log.info(`[BackendManager] Found orphaned process: PID ${pid}`);
            pidsToKill.push(pid);
          }
          
          if (pidsToKill.length > 0) {
            log.warn(`[BackendManager] Found ${pidsToKill.length} orphaned backend process(es): ${pidsToKill.join(', ')}`);
            
            for (const pid of pidsToKill) {
              try {
                // Try graceful shutdown first
                log.info(`[BackendManager] Killing orphaned process ${pid}...`);
                execSync(`kill -TERM ${pid}`, { timeout: 1000 });
              } catch (e) {
                // Process might already be gone
              }
            }
            
            // Wait a moment for graceful shutdown
            await new Promise(resolve => setTimeout(resolve, 2000));
            
            // Force kill any remaining
            for (const pid of pidsToKill) {
              try {
                execSync(`kill -0 ${pid}`, { timeout: 1000 }); // Check if still running
                log.warn(`[BackendManager] Force killing orphaned process ${pid}...`);
                execSync(`kill -9 ${pid}`, { timeout: 1000 });
              } catch (e) {
                // Process is gone, which is what we want
              }
            }
            
            log.info('[BackendManager] Orphaned process cleanup complete');
          }
        } catch (e) {
          // grep returns exit code 1 if no matches - this is fine
          if (e.status !== 1) {
            log.debug('[BackendManager] Process search failed:', e.message);
          }
        }
        
        // Also clean up orphaned crashpad handlers (only in production - these are per-app-bundle)
        if (!this.isDevelopment) {
          try {
            const crashpadResult = execSync('pgrep -f "chrome_crashpad_handler.*reliant"', { encoding: 'utf8', timeout: 5000 }).trim();
            const crashpadPids = crashpadResult.split('\n').filter(pid => pid);
            
            if (crashpadPids.length > 0) {
              log.warn(`[BackendManager] Found ${crashpadPids.length} orphaned crashpad process(es)`);
              for (const pid of crashpadPids) {
                try {
                  execSync(`kill -9 ${pid}`, { timeout: 1000 });
                } catch (e) {
                  // Ignore
                }
              }
            }
          } catch (e) {
            // No crashpad processes found
          }
        }
        
      } else if (process.platform === 'win32') {
        // Windows: Look for our unique binary name or reliant-backend.exe in prod
        const searchName = this.isDevelopment && this.instanceId
          ? `reliant-${this.instanceId}.exe`
          : 'reliant-backend.exe';
        
        try {
          // Get process info
          const tasklistResult = execSync(
            `tasklist /FI "IMAGENAME eq ${searchName}" /NH`,
            { encoding: 'utf8', timeout: 5000 }
          );
          
          // Parse PIDs from tasklist output (format: "name.exe    PID ...")
          const lines = tasklistResult.split('\n').filter(line => line.includes(searchName));
          const pidsToKill = [];
          
          for (const line of lines) {
            const match = line.match(new RegExp(`${searchName.replace('.', '\\.')}\\s+(\\d+)`));
            if (match) {
              const pid = match[1];
              
              // Skip our own process
              if (pid === String(this.process?.pid)) {
                continue;
              }
              
              log.info(`[BackendManager] Found orphaned process: PID ${pid}`);
              pidsToKill.push(pid);
            }
          }
          
          if (pidsToKill.length > 0) {
            log.warn(`[BackendManager] Found ${pidsToKill.length} orphaned backend process(es) on Windows`);
            
            for (const pid of pidsToKill) {
              try {
                log.info(`[BackendManager] Killing orphaned process ${pid}...`);
                execSync(`taskkill /PID ${pid} /F`, { timeout: 5000 });
              } catch (e) {
                log.debug(`[BackendManager] Failed to kill process ${pid}:`, e.message);
              }
            }
            
            log.info('[BackendManager] Orphaned process cleanup complete');
          }
        } catch (e) {
          log.debug('[BackendManager] No orphaned processes found on Windows:', e.message);
        }
      }
      
      // Also check the PID lock file for any orphaned process
      // The Go backend writes its PID to this file when it acquires the lock
      await this.cleanupFromLockFile();
      
    } catch (error) {
      // Don't let cleanup failures prevent startup
      log.error('[BackendManager] Error during orphan cleanup (continuing anyway):', error.message);
    }
  }
  
  /**
   * Check the PID lock file and kill any orphaned process recorded in it.
   * This is a fallback for cases where the process name-based cleanup misses zombies.
   */
  async cleanupFromLockFile() {
    const { execSync } = require('child_process');
    
    // Determine data directory (same logic as when starting backend)
    const dataDir = this.isDevelopment
      ? './data'
      : path.join(app.getPath('userData'), 'data');
    
    const lockFilePath = path.join(dataDir, '.reliant-backend.lock');
    
    try {
      if (!fs.existsSync(lockFilePath)) {
        log.debug('[BackendManager] No lock file found at:', lockFilePath);
        return;
      }
      
      // Read PID from lock file
      const content = fs.readFileSync(lockFilePath, 'utf8').trim();
      const pid = parseInt(content, 10);
      
      if (isNaN(pid) || pid <= 0) {
        log.debug('[BackendManager] Invalid PID in lock file:', content);
        // Remove invalid lock file
        try { fs.unlinkSync(lockFilePath); } catch (e) { /* ignore */ }
        return;
      }
      
      // Skip if it's our own process
      if (pid === process.pid || pid === this.process?.pid) {
        log.debug('[BackendManager] Lock file PID is our own process, skipping');
        return;
      }
      
      // Check if process is running
      if (process.platform === 'win32') {
        try {
          execSync(`tasklist /FI "PID eq ${pid}" /NH`, { encoding: 'utf8', timeout: 5000 });
          log.warn(`[BackendManager] Found orphaned process from lock file: PID ${pid}`);
          execSync(`taskkill /PID ${pid} /F`, { timeout: 5000 });
          log.info(`[BackendManager] Killed orphaned process ${pid} from lock file`);
        } catch (e) {
          // Process not found or already dead
          log.debug('[BackendManager] Lock file process not running:', pid);
        }
      } else {
        // Unix: check if process exists
        try {
          execSync(`kill -0 ${pid}`, { timeout: 1000 });
          // Process exists - kill it
          log.warn(`[BackendManager] Found orphaned process from lock file: PID ${pid}`);
          
          try {
            execSync(`kill -TERM ${pid}`, { timeout: 1000 });
            // Wait for graceful shutdown
            await new Promise(resolve => setTimeout(resolve, 2000));
            
            // Check if still running
            try {
              execSync(`kill -0 ${pid}`, { timeout: 1000 });
              // Still running - force kill
              log.warn(`[BackendManager] Force killing orphaned process ${pid}`);
              execSync(`kill -9 ${pid}`, { timeout: 1000 });
            } catch (e) {
              // Process exited gracefully
            }
          } catch (e) {
            // SIGTERM failed, try SIGKILL
            try { execSync(`kill -9 ${pid}`, { timeout: 1000 }); } catch (e2) { /* ignore */ }
          }
          
          log.info(`[BackendManager] Killed orphaned process ${pid} from lock file`);
        } catch (e) {
          // Process doesn't exist - stale lock file
          log.debug('[BackendManager] Lock file process not running:', pid);
        }
      }
      
      // Remove the stale lock file so the new process can start fresh
      try {
        fs.unlinkSync(lockFilePath);
        log.info('[BackendManager] Removed stale lock file');
      } catch (e) {
        log.debug('[BackendManager] Could not remove lock file:', e.message);
      }
      
    } catch (error) {
      log.debug('[BackendManager] Error checking lock file:', error.message);
    }
  }

  getBinaryPath() {

    if (this.isDevelopment) {
      // In development, use the pre-built dev binary
      // The npm script builds to dist/reliant (or reliant.exe on Windows)
      const binaryName = process.platform === 'win32' ? 'reliant.exe' : 'reliant';
      const devBinaryPath = path.join(__dirname, '../../dist', binaryName);
      log.info('[BackendManager] Development mode - using binary:', devBinaryPath);

      if (!fs.existsSync(devBinaryPath)) {
        log.error('[BackendManager] ERROR: Development binary not found at:', devBinaryPath);

        throw new Error(`Development backend binary not found: ${devBinaryPath}. Run 'npm run build:backend' first.`);
      }

      // Generate a unique instance ID based on the worktree/project directory
      // This allows us to identify and clean up only OUR backend process
      const projectRoot = path.join(__dirname, '../..');
      const worktreeMatch = projectRoot.match(/\.reliant\/worktrees\/([^/]+)/);
      if (worktreeMatch) {
        // We're in a worktree - use the worktree ID (e.g., "19e1db5c3d48")
        this.instanceId = worktreeMatch[1];
      } else {
        // Main repo - use the project directory name
        this.instanceId = path.basename(projectRoot);
      }
      
      // Create a symlink with unique name for process identification
      // This makes it easy to find/kill only processes for this worktree
      const uniqueBinaryName = process.platform === 'win32' 
        ? `reliant-${this.instanceId}.exe` 
        : `reliant-${this.instanceId}`;
      const symlinkPath = path.join(__dirname, '../../dist', uniqueBinaryName);
      
      // Create/update symlink if needed
      try {
        if (fs.existsSync(symlinkPath)) {
          const existingTarget = fs.readlinkSync(symlinkPath);
          if (existingTarget !== devBinaryPath && existingTarget !== binaryName) {
            fs.unlinkSync(symlinkPath);
            fs.symlinkSync(binaryName, symlinkPath);
          }
        } else {
          fs.symlinkSync(binaryName, symlinkPath);
        }
        log.info(`[BackendManager] Using unique binary name: ${uniqueBinaryName}`);
      } catch (error) {
        // If symlink fails (e.g., Windows without admin), fall back to original binary
        log.warn(`[BackendManager] Could not create symlink, using original binary: ${error.message}`);
        return {
          command: devBinaryPath,
          args: ['monolith']
        };
      }

      log.info('[BackendManager] Starting backend with command:', symlinkPath);
      log.info('[BackendManager] Instance ID:', this.instanceId);

      return {
        command: symlinkPath,
        args: ['monolith']
      };
    } else {
      // In production, use embedded binary
      const platform = process.platform;
      const arch = process.arch;

      // Map Node.js arch names to Go arch names
      const archMap = {
        'x64': 'amd64',
        'arm64': 'arm64',
        'ia32': '386'
      };

      const goArch = archMap[arch] || arch;
      const binaryName = platform === 'win32' ? 'reliant-backend.exe' : 'reliant-backend';

      // Use platform-specific binary paths
      if (platform === 'darwin') {
        // macOS: use architecture-specific binary (x64 or arm64)
        const macArch = arch === 'x64' ? 'x64' : 'arm64';
        const binaryPath = path.join(process.resourcesPath, 'server', `mac-${macArch}`, binaryName);

        log.info(`[BackendManager] Looking for macOS ${macArch} backend at: ${binaryPath}`);

        if (!fs.existsSync(binaryPath)) {
          throw new Error(`macOS ${macArch} backend binary not found: ${binaryPath}. Ensure the binary was built for ${macArch}.`);
        }

        // Ensure binary is executable on Unix systems
        try {
          fs.chmodSync(binaryPath, '755');
        } catch (error) {
          log.warn('Could not set binary permissions:', error.message);
        }

        const args = ['monolith'];

        // Add mock driver flags if configured
        if (this.mockDriverConfig?.enabled && this.mockDriverConfig?.mode === 'replay' && this.mockDriverConfig?.replayFile) {
          args.push('--replay', this.mockDriverConfig.replayFile);
          log.info('[BackendManager] Mock driver enabled with replay file:', this.mockDriverConfig.replayFile);
        }

        return {
          command: binaryPath,
          args: args
        };
      } else if (platform === 'win32') {
        // Windows: use win32-amd64 or win32-arm64 based on architecture
        const platformDir = arch === 'arm64' ? 'win32-arm64' : 'win32-amd64';
        const binaryPath = path.join(process.resourcesPath, 'server', platformDir, binaryName);

        log.info(`[BackendManager] Looking for Windows backend at: ${binaryPath}`);

        if (!fs.existsSync(binaryPath)) {
          throw new Error(`Windows backend binary not found: ${binaryPath}. Ensure the binary was built for platform ${platform}-${goArch}`);
        }

        const args = ['monolith'];

        // Add mock driver flags if configured
        if (this.mockDriverConfig?.enabled && this.mockDriverConfig?.mode === 'replay' && this.mockDriverConfig?.replayFile) {
          args.push('--replay', this.mockDriverConfig.replayFile);
          log.info('[BackendManager] Mock driver enabled with replay file:', this.mockDriverConfig.replayFile);
        }

        return {
          command: binaryPath,
          args: args
        };
      } else if (platform === 'linux') {
        // Linux: use linux-amd64 or linux-arm64 based on architecture
        const platformDir = arch === 'arm64' ? 'linux-arm64' : 'linux-amd64';
        const binaryPath = path.join(process.resourcesPath, 'server', platformDir, binaryName);

        log.info(`[BackendManager] Looking for Linux backend at: ${binaryPath}`);

        if (!fs.existsSync(binaryPath)) {
          throw new Error(`Linux backend binary not found: ${binaryPath}. Ensure the binary was built for platform ${platform}-${goArch}`);
        }

        // Ensure binary is executable on Unix systems
        try {
          fs.chmodSync(binaryPath, '755');
        } catch (error) {
          log.warn('Could not set binary permissions:', error.message);
        }

        const args = ['monolith'];

        // Add mock driver flags if configured
        if (this.mockDriverConfig?.enabled && this.mockDriverConfig?.mode === 'replay' && this.mockDriverConfig?.replayFile) {
          args.push('--replay', this.mockDriverConfig.replayFile);
          log.info('[BackendManager] Mock driver enabled with replay file:', this.mockDriverConfig.replayFile);
        }

        return {
          command: binaryPath,
          args: args
        };
      } else {
        throw new Error(`Unsupported platform: ${platform}`);
      }
    }
  }

  async findConsecutiveFreePorts(startPort, count) {
    // Check if a specific range of ports is free
    const checkPortRange = async (basePort) => {
      try {
        // Check each port in the range
        for (let i = 0; i < count; i++) {
          const port = basePort + i;
          // Try to find a free port starting at exactly this port
          const [freePort] = await findFreePort(port, port);
          if (freePort !== port) {
            return null; // This port is not free
          }
        }
        return basePort; // All ports in range are free
      } catch (error) {
        return null; // Range is not available
      }
    };

    // Try starting from the specified port, incrementing until we find a free range
    for (let basePort = startPort; basePort < startPort + 1000; basePort++) {
      const freeBase = await checkPortRange(basePort);
      if (freeBase !== null) {
        return freeBase;
      }
    }

    throw new Error(`Could not find ${count} consecutive free ports starting from ${startPort}`);
  }

  async waitForReady(timeout = null) {
    const actualTimeout = timeout || this.startupTimeout;

    return new Promise((resolve, reject) => {
      const startTime = Date.now();

      const checkReady = async () => {
        // Check if we've exceeded timeout
        if (Date.now() - startTime > actualTimeout) {
          reject(new Error(`Backend failed to become ready within ${actualTimeout}ms`));
          return;
        }

        try {
          const isHealthy = await this.checkHealth();
          if (isHealthy) {
            log.info(`[BackendManager] Backend ready after ${Date.now() - startTime}ms`);
            resolve(true);
            return;
          } else {
          }
        } catch (error) {
          // Backend not ready yet, continue polling
        }

        // Schedule next check - poll faster for quicker startup
        setTimeout(checkReady, 50);
      };

      // Start checking
      checkReady();
    });
  }

  checkHealth() {
    const protocol = this.useTLS ? https : http;

    const callConnectUnary = (path, body, validateResponse) =>
      new Promise((resolve, reject) => {
        const req = protocol.request({
          hostname: 'localhost',
          port: this.grpcPort,
          path,
          method: 'POST',
          timeout: 1000,
          rejectUnauthorized: false, // Accept self-signed certificates
          headers: {
            'Content-Type': 'application/json',
          },
        }, (res) => {
          let responseBody = '';
          res.setEncoding('utf8');
          res.on('data', (chunk) => {
            responseBody += chunk;
          });
          res.on('end', () => {
            try {
              if (validateResponse) {
                resolve(validateResponse(res, responseBody));
                return;
              }
              resolve(res.statusCode === 200);
            } catch (error) {
              reject(error);
            }
          });
        });

        req.on('error', reject);
        req.on('timeout', () => {
          req.destroy();
          reject(new Error('Health check timeout'));
        });

        req.write(body);
        req.end();
      });

    return callConnectUnary(
      '/reliant.v1.SystemService/Ready',
      '{}',
      (res, responseBody) => {
        if (res.statusCode !== 200) {
          return false;
        }

        try {
          const parsed = JSON.parse(responseBody);
          return parsed?.status === 'ready';
        } catch {
          return false;
        }
      }
    );
  }

  async start() {
    const startTime = Date.now();
    log.info('[BackendManager] start() called');

    // Clean up any orphaned processes from previous runs before starting
    // This prevents "app can't be opened" errors after failed updates
    await this.cleanupOrphanedProcesses();

    // Check if external backend is already running (dev mode with Air)
    if (process.env.RELIANT_EXTERNAL_BACKEND) {
      const externalGrpcPort = parseInt(process.env.GRPC_PORT, 10);
      const externalToolsDaemonPort = parseInt(process.env.TOOLS_DAEMON_PORT, 10);
      const externalTemporalPort = parseInt(process.env.TEMPORAL_FRONTEND_PORT, 10);
      const externalTemporalUIPort = parseInt(process.env.TEMPORAL_UI_PORT, 10);
      
      log.info('[BackendManager] Using external backend (Air/dev mode)');
      log.info('[BackendManager] External gRPC port:', externalGrpcPort);
      log.info('[BackendManager] External tools daemon gRPC port:', externalToolsDaemonPort);
      log.info('[BackendManager] External Temporal port:', externalTemporalPort);
      log.info('[BackendManager] External Temporal UI port:', externalTemporalUIPort);
      
      this.grpcPort = externalGrpcPort;
      this.toolsDaemonPort = externalToolsDaemonPort;
      this.temporalFrontendPort = externalTemporalPort;
      this.temporalUIPort = externalTemporalUIPort;
      this.isRunning = true;
      
      // Wait for external backend to be ready
      await this.waitForReady();
      log.info('[BackendManager] ✓ External backend is ready');
      return this.grpcPort;
    }

    // Load mock driver config if not already loaded
    if (!this.mockDriverConfig) {
      this.loadMockDriverConfig();
    }

    log.info('[BackendManager] Mock driver config:', JSON.stringify(this.mockDriverConfig));

    if (this.isRunning) {
      log.info('[BackendManager] Backend already running on gRPC port:', this.grpcPort);
      return this.grpcPort;
    }

    if (this.isShuttingDown) {
      log.info('[BackendManager] Backend is shutting down, waiting...');
      // Wait for shutdown to complete using event-driven approach
      await new Promise((resolve) => {
        const checkShutdown = () => {
          if (!this.isShuttingDown) {
            resolve();
          } else {
            // Check again in next tick
            setImmediate(checkShutdown);
          }
        };
        checkShutdown();
      });
      return this.start();
    }

    try {
      // Find available port for gRPC server (or use env var if set by dev script)
      const grpcPortStart = Date.now();
      if (process.env.GRPC_PORT) {
        this.grpcPort = parseInt(process.env.GRPC_PORT, 10);
        log.info(`[BackendManager] Using GRPC_PORT from environment: ${this.grpcPort}`);
      } else {
        [this.grpcPort] = await findFreePort(9090, 9190);
        log.info(`[BackendManager] ✓ gRPC port found in ${Date.now() - grpcPortStart}ms:`, this.grpcPort);
      }

      const toolsDaemonPortStart = Date.now();
      if (process.env.TOOLS_DAEMON_PORT) {
        this.toolsDaemonPort = parseInt(process.env.TOOLS_DAEMON_PORT, 10);
        log.info(`[BackendManager] Using TOOLS_DAEMON_PORT from environment: ${this.toolsDaemonPort}`);
      } else {
        [this.toolsDaemonPort] = await findFreePort(9190, 9290);
        log.info(`[BackendManager] ✓ tools daemon gRPC port found in ${Date.now() - toolsDaemonPortStart}ms:`, this.toolsDaemonPort);
      }

      // Find 4 consecutive free ports for Temporal (frontend, history, matching, worker)
      const temporalPortStart = Date.now();
      const temporalFrontendPort = await this.findConsecutiveFreePorts(7000, 4);
      log.info(`[BackendManager] ✓ Temporal ports found in ${Date.now() - temporalPortStart}ms: ${temporalFrontendPort}-${temporalFrontendPort + 3}`);

      // Find a free port for Temporal UI (or use env var if set by dev script)
      const temporalUIPortStart = Date.now();
      let temporalUIPort;
      if (process.env.TEMPORAL_UI_PORT) {
        temporalUIPort = parseInt(process.env.TEMPORAL_UI_PORT, 10);
        log.info(`[BackendManager] Using TEMPORAL_UI_PORT from environment: ${temporalUIPort}`);
      } else {
        [temporalUIPort] = await findFreePort(8233, 8333);
        log.info(`[BackendManager] ✓ Temporal UI port found in ${Date.now() - temporalUIPortStart}ms: ${temporalUIPort}`);
      }

      // Store temporal ports
      this.temporalFrontendPort = temporalFrontendPort;
      this.temporalUIPort = temporalUIPort;

      // Get binary path
      const binaryPath = this.getBinaryPath();
      // Build environment variables for V2
      const homeDir = require('os').homedir();
      let backendEnv = {
        ...process.env,
        GRPC_PORT: this.grpcPort.toString(),  // Pass allocated gRPC port
        TOOLS_DAEMON_PORT: this.toolsDaemonPort.toString(),  // Dedicated tools-daemon gRPC listener
        TEMPORAL_FRONTEND_PORT: temporalFrontendPort.toString(),  // Pass allocated Temporal gRPC port
        TEMPORAL_UI_PORT: temporalUIPort.toString(),  // Pass allocated Temporal UI port
// User config: ~/.reliant/ (user-editable, git-friendly)
        RELIANT_USER_CONFIG_DIR: path.join(homeDir, '.reliant'),
        // Internal app data: platform-specific (databases, analytics, auth, cache)
        RELIANT_APP_DATA_DIR: app.getPath('userData'),
        // Logs: platform-specific logs directory
        RELIANT_LOGS_PATH: app.getPath('logs'),
        // Temp: system temp directory
        RELIANT_TEMP_PATH: app.getPath('temp'),
        // CRITICAL: Set environment mode for the Go backend
        // In packaged apps, NODE_ENV is not set automatically, causing the backend to default to dev mode
        RELIANT_ENV: this.isDevelopment ? 'dev' : 'prod',
      };

      // Keep backend database env deterministic from the already-normalized process env.
      // This prevents stale inherited DATABASE_URL/PG* values from leaking into spawned backend.
      [
        'DATABASE_DRIVER',
        'DATABASE_URL',
        'PGHOST',
        'PGPORT',
        'PGDATABASE',
        'PGUSER',
        'PGSSLMODE',
        'RELIANT_POSTGRES_PORT'
      ].forEach((key) => {
        if (process.env[key] !== undefined) {
          backendEnv[key] = process.env[key];
        }
      });

      log.info('[BackendManager] Effective backend DB env', {
        driver: backendEnv.DATABASE_DRIVER || '(unset)',
        pgHost: backendEnv.PGHOST || '(unset)',
        pgPort: backendEnv.PGPORT || '(unset)',
        pgDatabase: backendEnv.PGDATABASE || '(unset)',
        hasDatabaseUrl: Boolean(backendEnv.DATABASE_URL)
      });

      // CRITICAL: In production, ensure PATH includes common locations for MCP tools
      // MCP servers often use npx, uvx, python, etc. which aren't in Electron's default PATH
      if (!this.isDevelopment) {
        const isWindows = process.platform === 'win32';
        const pathSeparator = isWindows ? ';' : ':';

        let additionalPaths = [];

        if (isWindows) {
          // Windows-specific paths
          additionalPaths = [
            path.join(process.env.PROGRAMFILES || 'C:\\Program Files', 'nodejs'),
            path.join(process.env.APPDATA || path.join(homeDir, 'AppData', 'Roaming'), 'npm'),
            path.join(homeDir, 'AppData', 'Local', 'Programs', 'Python'),
            path.join(homeDir, '.local', 'bin'),
            path.join(homeDir, 'go', 'bin'),  // Go binaries on Windows
          ];
        } else {
          // Unix-specific paths (macOS/Linux)
          additionalPaths = [
            '/usr/local/bin',
            '/opt/homebrew/bin',  // macOS Apple Silicon Homebrew
            '/usr/bin',
            '/bin',
            path.join(homeDir, 'go', 'bin'),  // Go binaries (air, etc.)
            path.join(homeDir, '.local', 'bin'),  // Python user binaries (uvx, etc.)
            path.join(homeDir, '.npm-global', 'bin'),  // Global npm binaries
            '/opt/homebrew/opt/python/libexec/bin',  // Homebrew python
            '/usr/local/go/bin',  // System Go installation
          ];

          // Try to find nvm-managed node installations (Unix only)
          const nvmDir = path.join(homeDir, '.nvm', 'versions', 'node');
          if (fs.existsSync(nvmDir)) {
            try {
              const versions = fs.readdirSync(nvmDir);
              if (versions.length > 0) {
                // Use the latest version (or default)
                const latestVersion = versions.sort().reverse()[0];
                const nvmNodeBin = path.join(nvmDir, latestVersion, 'bin');
                if (fs.existsSync(nvmNodeBin)) {
                  additionalPaths.push(nvmNodeBin);
                  log.info('[BackendManager] Found nvm node installation:', nvmNodeBin);
                }
              }
            } catch (err) {
              log.warn('[BackendManager] Error scanning nvm directory:', err.message);
            }
          }
        }

        // Get existing PATH and deduplicate
        const existingPath = backendEnv.PATH || backendEnv.Path || '';
        const pathParts = existingPath.split(pathSeparator).filter(p => p);

        // Add additional paths if they exist and aren't already in PATH
        for (const dir of additionalPaths) {
          if (fs.existsSync(dir) && !pathParts.includes(dir)) {
            pathParts.push(dir);
          }
        }

        backendEnv.PATH = pathParts.join(pathSeparator);
        if (isWindows) {
          backendEnv.Path = backendEnv.PATH; // Windows uses both PATH and Path
        }
        log.info('[BackendManager] Production PATH set to:', backendEnv.PATH);

        // Ensure critical environment variables are set for MCP servers
        if (!isWindows) {
          if (!backendEnv.SHELL) {
            backendEnv.SHELL = '/bin/zsh';  // macOS default
          }
        }
        if (!backendEnv.HOME && !isWindows) {
          backendEnv.HOME = homeDir;
        }
        if (!backendEnv.USERPROFILE && isWindows) {
          backendEnv.USERPROFILE = homeDir;
        }
        // Some MCP servers need USER/USERNAME
        if (!backendEnv.USER && !isWindows) {
          backendEnv.USER = require('os').userInfo().username;
        }
        if (!backendEnv.USERNAME && isWindows) {
          backendEnv.USERNAME = require('os').userInfo().username;
        }
        // TERM is needed for scripts that use tput or terminal capabilities
        if (!backendEnv.TERM && !isWindows) {
          backendEnv.TERM = 'xterm-256color';
        }

        log.info('[BackendManager] Environment variables set:', {
          SHELL: backendEnv.SHELL,
          HOME: backendEnv.HOME,
          USERPROFILE: backendEnv.USERPROFILE,
          USER: backendEnv.USER,
          USERNAME: backendEnv.USERNAME,
          PATH_length: backendEnv.PATH.length
        });
      }

      // Set data directory based on mode
      // In development: use ./data (relative to cwd) for worktree isolation
      // In production: use userData/data for shared app data
      if (!backendEnv.RELIANT_DATA_DIR) {
        backendEnv.RELIANT_DATA_DIR = this.isDevelopment
          ? './data'  // Dev: local to each worktree
          : path.join(app.getPath('userData'), 'data');  // Prod: shared app data
      }

      // Spawn backend process
      // In development, inherit stdout/stderr so we can see output directly
      // In production, pipe them so we can capture them
      // CRITICAL: Always pipe stdin (index 0) so the backend can detect when the parent process dies (Suicide Pact pattern)
      const stdio = this.isDevelopment ? ['pipe', 'inherit', 'inherit'] : ['pipe', 'pipe', 'pipe'];

      this.process = spawn(binaryPath.command, binaryPath.args, {
        cwd: process.cwd(),
        stdio: stdio,
        env: backendEnv,
        windowsHide: true  // Prevent console window from appearing on Windows
      });

      log.info('[BackendManager] Backend process started with PID:', this.process.pid);

      // CRITICAL: Keep stdin stream alive for the "Suicide Pact" pattern to work correctly.
      // The Go backend monitors stdin for EOF to detect when the parent process dies.
      // If we don't keep this stream alive, Node.js may auto-close it, causing premature shutdown.
      if (this.process.stdin) {
        // Prevent errors from crashing the process
        this.process.stdin.on('error', (err) => {
          log.debug('[BackendManager] stdin stream error (expected on shutdown):', err.message);
        });
        // Keep the stream referenced to prevent garbage collection
        this.stdinStream = this.process.stdin;
      }

      // Only set up stream handlers in production mode
      if (!this.isDevelopment) {
        // Log output for debugging
        this.process.stdout.on('data', (data) => {
          const output = data.toString().trim();
          // Always log backend stdout
          if (output) {
            log.info(`[Backend]: ${output}`);
          }
        });

        this.process.stderr.on('data', (data) => {
          const output = data.toString().trim();
          if (output) {
            log.error(`[Backend Error]: ${output}`);
          }
        });
      }

      this.process.on('error', (error) => {
        log.error('Failed to start backend process:', error);
        this.isRunning = false;
      });

      this.process.on('exit', (code, signal) => {
        log.info(`[BackendManager] Backend process exited (code: ${code}, signal: ${signal})`);
        this.isRunning = false;
        this.process = null;

        // Auto-restart on crash if not intentionally shutting down
        if (!this.isShuttingDown && !this.intentionalShutdown && code !== 0) {
          log.error('Backend crashed unexpectedly, attempting restart...');
          this.handleCrash();
        } else if (code === 0) {
          // Reset restart attempts on clean exit
          this.restartAttempts = 0;
        }
      });

      // Wait for backend to be ready
      const readyStart = Date.now();
      await this.waitForReady();
      log.info(`[BackendManager] ✓ Backend ready in ${Date.now() - readyStart}ms`);

      this.isRunning = true;

      log.info(`[BackendManager] ✓✓✓ Total backend startup: ${Date.now() - startTime}ms`);
      return this.grpcPort;

    } catch (error) {
      log.error('[BackendManager] Failed to start backend:', error);
      log.error('[BackendManager] Error stack:', error.stack);
      await this.cleanup();
      throw error;
    }
  }

  async cleanup() {
    // Clean up stdin stream reference
    if (this.stdinStream) {
      this.stdinStream = null;
    }
    if (this.process && !this.process.killed) {
      try {
        this.process.kill('SIGKILL');
      } catch (e) {
        log.error('Error killing process:', e);
      }
    }
    this.process = null;
    this.isRunning = false;
    this.grpcPort = null;
    this.toolsDaemonPort = null;
    this.temporalFrontendPort = null;
    this.temporalUIPort = null;
  }

  async handleCrash() {
    if (this.restartAttempts >= this.maxRestartAttempts) {
      log.error(`[BackendManager] Max restart attempts (${this.maxRestartAttempts}) reached, giving up`);
      // Emit an event or notify the main window about the failure
      return;
    }

    this.restartAttempts++;
    const delay = Math.min(this.restartDelay * this.restartAttempts, 10000); // Max 10 seconds delay

    log.info(`[BackendManager] Restart attempt ${this.restartAttempts}/${this.maxRestartAttempts} in ${delay}ms...`);

    setTimeout(async () => {
      try {
        await this.start();
        log.info('[BackendManager] Backend restarted successfully');
        // Reset attempts after successful restart
        this.restartAttempts = 0;
      } catch (error) {
        log.error('[BackendManager] Failed to restart backend:', error);
        // Will retry if attempts remaining
        this.handleCrash();
      }
    }, delay);
  }

  async stop() {
    // Skip stopping if using external backend
    if (process.env.RELIANT_EXTERNAL_BACKEND) {
      log.info('[BackendManager] External backend - skipping stop (managed externally)');
      this.isRunning = false;
      return;
    }

    if (!this.process || this.isShuttingDown) {
      return;
    }

    this.intentionalShutdown = true; // Mark as intentional shutdown
    this.isShuttingDown = true;
    log.info('[BackendManager] Stopping backend gracefully...');

    return new Promise((resolve) => {
      let cleanupDone = false;

      const cleanup = () => {
        if (cleanupDone) return;
        cleanupDone = true;

        this.process = null;
        this.isRunning = false;
        this.grpcPort = null;
        this.toolsDaemonPort = null;
        this.temporalFrontendPort = null;
        this.temporalUIPort = null;
        this.isShuttingDown = false;
        this.intentionalShutdown = false; // Reset for next start
        resolve();
      };

      // Set a timeout for forced kill
      const forceKillTimeout = setTimeout(() => {
        if (this.process && !this.process.killed) {
          log.warn('[BackendManager] Force killing backend after timeout');
          try {
            this.process.kill('SIGKILL');
          } catch (e) {
            log.error('Error force killing:', e);
          }
        }
        cleanup();
      }, this.shutdownTimeout);

      // Listen for exit
      this.process.once('exit', (code, signal) => {
        log.info(`[BackendManager] Backend exited gracefully (code: ${code}, signal: ${signal})`);
        clearTimeout(forceKillTimeout);
        cleanup();
      });

      // Try graceful shutdown with SIGTERM
      try {
        this.process.kill('SIGTERM');
      } catch (error) {
        log.error('Error sending SIGTERM:', error);
        clearTimeout(forceKillTimeout);
        cleanup();
      }
    });
  }

  getPort() {
    return this.grpcPort;
  }

  getTemporalFrontendPort() {
    return this.temporalFrontendPort;
  }

  getTemporalUIPort() {
    return this.temporalUIPort;
  }

  getStatus() {
    return {
      isRunning: this.isRunning,
      grpcPort: this.grpcPort,
      toolsDaemonPort: this.toolsDaemonPort,
      temporalFrontendPort: this.temporalFrontendPort,
      temporalUIPort: this.temporalUIPort,
      useTLS: this.useTLS,
      isShuttingDown: this.isShuttingDown,
      mockDriverActive: this.mockDriverConfig?.enabled && this.mockDriverConfig?.mode === 'replay',
      mockDriverFile: this.mockDriverConfig?.replayFile
    };
  }

  async isReady() {
    if (!this.isRunning || !this.grpcPort) {
      return false;
    }

    try {
      return await this.checkHealth();
    } catch {
      return false;
    }
  }

  // Emergency cleanup - called on app crash
  emergencyStop() {
    if (this.process && !this.process.killed) {
      try {
        this.process.kill('SIGKILL');
      } catch (e) {
        // Ignore errors during emergency stop
      }
    }
  }
}

module.exports = BackendManager;
