import type { InputMessage } from "../api/chat-grpc";

// Chat-related request types
// NOTE: model, temperature, max_tokens, mode are passed via workflow_params
export interface CreateChatRequest {
  title?: string;             // Optional - will be generated by titler if not provided
  project_id: string;         // Required - using snake_case to match backend
  workflow?: string;          // Optional - defaults to user's preference (e.g., "builtin://agent")
  messages: InputMessage[];   // Required - at least one user message
  attachments?: string[];     // Optional - attachment IDs for first message
  worktree_id?: string;       // Optional - using snake_case
  workflow_params?: Record<string, unknown>;  // Workflow inputs: model, temperature, max_tokens, mode, etc.
  selectedPresets?: Record<string, string>;   // Preset selections per target ("" = workflow-level, "Agent A" = group)
}

// NOTE: model/temperature/maxTokens are workflow params, not chat fields
// Use workflow_params when sending messages to override them
export interface UpdateChatRequest {
  title?: string;
  worktree_id?: string;
}

export interface BranchChatRequest {
  messageId: string;
  title?: string;
}
