// =============================================================================
// GENERATED FILE - DO NOT EDIT DIRECTLY
// =============================================================================
//
// Source of truth: config/shortcuts.yaml
// Generated by: go run ./tools/docgen/shortcuts
// Regenerate with: make generate-shortcuts
//
// This file contains the default keyboard shortcut definitions.
// =============================================================================

import type { ShortcutDefinition } from './shortcutsStore';

/**
 * Default keyboard shortcuts.
 *
 * Bindings are authored strings ("Cmd+Shift+P", "Cmd+K C") rather than
 * pre-resolved modifier objects. Platform folding (Cmd to Meta on macOS, to
 * Control elsewhere) happens at load time in parseBinding(), so one definition
 * serves every platform and sequences stay readable.
 *
 * Categories:
 *   - Focus
 *   - File & Window Management
 *   - Search & Navigation
 *   - Chat Navigation
 *   - Project Navigation
 *   - File Navigation
 *   - Panel Navigation
 *   - Interface
 *   - Terminal
 *   - Chat Control
 *   - Parameters
 */
export const defaultShortcuts: Record<string, Omit<ShortcutDefinition, 'currentBinding'>> = {
  newChat: {
    id: 'newChat',
    name: 'New Chat',
    description: 'Create a new chat tab',
    category: 'File & Window Management',
    defaultBinding: 'Cmd+T',
    defaultWebBinding: 'Cmd+K T',
    context: 'global',
    handler: 'onNewChat'
  },
  openProject: {
    id: 'openProject',
    name: 'Open Project',
    description: 'Open a new project directory',
    category: 'File & Window Management',
    defaultBinding: 'Cmd+O',
    defaultWebBinding: 'Cmd+K O',
    context: 'global',
    handler: 'onOpenProject'
  },
  closeTab: {
    id: 'closeTab',
    name: 'Close Tab',
    description: 'Close active file viewer tab or window',
    category: 'File & Window Management',
    defaultBinding: 'Cmd+W',
    defaultWebBinding: 'Cmd+K W',
    context: 'global',
    handler: 'onCloseTab'
  },
  openWorkflows: {
    id: 'openWorkflows',
    name: 'Open Workflow Builder',
    description: 'Open the workflow builder panel',
    category: 'File & Window Management',
    defaultBinding: 'Cmd+Shift+K',
    defaultWebBinding: 'Cmd+Shift+K',
    context: 'global',
    handler: 'onOpenWorkflows'
  },
  quickFileOpen: {
    id: 'quickFileOpen',
    name: 'Quick File Open',
    description: 'Open file by name (fuzzy search)',
    category: 'Search & Navigation',
    defaultBinding: 'Cmd+P',
    defaultWebBinding: 'Cmd+K P',
    context: 'global',
    handler: 'onQuickFileOpen'
  },
  commandPalette: {
    id: 'commandPalette',
    name: 'Command Palette',
    description: 'Open command palette',
    category: 'Search & Navigation',
    defaultBinding: 'Cmd+Shift+P',
    defaultWebBinding: 'Cmd+Shift+P',
    context: 'global',
    handler: 'onCommandPalette'
  },
  findInFiles: {
    id: 'findInFiles',
    name: 'Find in Files',
    description: 'Search content across all files',
    category: 'Search & Navigation',
    defaultBinding: 'Cmd+Shift+F',
    defaultWebBinding: 'Cmd+Shift+F',
    context: 'global',
    handler: 'onFindInFiles'
  },
  findReplace: {
    id: 'findReplace',
    name: 'Find and Replace',
    description: 'Find and replace text across files',
    category: 'Search & Navigation',
    defaultBinding: 'Cmd+Shift+H',
    defaultWebBinding: 'Cmd+Shift+H',
    context: 'global',
    handler: 'onFindReplace'
  },
  chatSearch: {
    id: 'chatSearch',
    name: 'Search Chats',
    description: 'Search the current conversation and chat history',
    category: 'Search & Navigation',
    defaultBinding: 'Cmd+F',
    defaultWebBinding: 'Cmd+F',
    context: 'global',
    handler: 'onChatSearch'
  },
  editorFind: {
    id: 'editorFind',
    name: 'Find in File',
    description: 'Open the editor\'s find widget',
    category: 'Search & Navigation',
    defaultBinding: 'Cmd+F',
    defaultWebBinding: 'Cmd+F',
    context: 'monaco',
    handler: 'onEditorFind',
    passthrough: true
  },
  focusChat: {
    id: 'focusChat',
    name: 'Focus Chat Input',
    description: 'Move the cursor to the chat composer',
    category: 'Focus',
    defaultBinding: 'Cmd+L',
    defaultWebBinding: 'Cmd+K L',
    context: 'global',
    handler: 'onFocusChat'
  },
  focusTranscript: {
    id: 'focusTranscript',
    name: 'Focus Conversation',
    description: 'Move the cursor to the conversation, to scroll and read by keyboard',
    category: 'Focus',
    defaultBinding: 'Cmd+K C',
    defaultWebBinding: 'Cmd+K C',
    context: 'global',
    handler: 'onFocusTranscript'
  },
  focusTerminal: {
    id: 'focusTerminal',
    name: 'Focus Terminal',
    description: 'Move the cursor to the terminal, opening it if hidden',
    category: 'Focus',
    defaultBinding: 'Cmd+K J',
    defaultWebBinding: 'Cmd+K J',
    context: 'global',
    handler: 'onFocusTerminal'
  },
  focusLeftSidebar: {
    id: 'focusLeftSidebar',
    name: 'Focus Chat List',
    description: 'Move the cursor to the left chat sidebar, opening it if hidden',
    category: 'Focus',
    defaultBinding: 'Cmd+K A',
    defaultWebBinding: 'Cmd+K A',
    context: 'global',
    handler: 'onFocusLeftSidebar'
  },
  focusPrevious: {
    id: 'focusPrevious',
    name: 'Return Focus',
    description: 'Send the cursor back to the pane it came from',
    category: 'Focus',
    defaultBinding: 'Cmd+K Escape',
    defaultWebBinding: 'Cmd+K Escape',
    context: 'global',
    handler: 'onFocusPrevious'
  },
  nextChat: {
    id: 'nextChat',
    name: 'Next Chat',
    description: 'Switch to the next chat in the list (down)',
    category: 'Chat Navigation',
    defaultBinding: 'Cmd+Shift+Down',
    defaultWebBinding: 'Cmd+Shift+Down',
    context: 'global',
    handler: 'onNextChat'
  },
  prevChat: {
    id: 'prevChat',
    name: 'Previous Chat',
    description: 'Switch to the previous chat in the list (up)',
    category: 'Chat Navigation',
    defaultBinding: 'Cmd+Shift+Up',
    defaultWebBinding: 'Cmd+Shift+Up',
    context: 'global',
    handler: 'onPrevChat'
  },
  selectionUpMonaco: {
    id: 'selectionUpMonaco',
    name: 'Extend Selection Up',
    description: 'Native text selection in the editor',
    category: 'Chat Navigation',
    defaultBinding: 'Cmd+Shift+Up',
    defaultWebBinding: 'Cmd+Shift+Up',
    context: 'monaco',
    handler: 'onNativeSelection',
    passthrough: true
  },
  selectionDownMonaco: {
    id: 'selectionDownMonaco',
    name: 'Extend Selection Down',
    description: 'Native text selection in the editor',
    category: 'Chat Navigation',
    defaultBinding: 'Cmd+Shift+Down',
    defaultWebBinding: 'Cmd+Shift+Down',
    context: 'monaco',
    handler: 'onNativeSelection',
    passthrough: true
  },
  selectionLeftMonaco: {
    id: 'selectionLeftMonaco',
    name: 'Extend Selection Left',
    description: 'Native text selection in the editor',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+Shift+Left',
    defaultWebBinding: 'Cmd+Shift+Left',
    context: 'monaco',
    handler: 'onNativeSelection',
    passthrough: true
  },
  selectionRightMonaco: {
    id: 'selectionRightMonaco',
    name: 'Extend Selection Right',
    description: 'Native text selection in the editor',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+Shift+Right',
    defaultWebBinding: 'Cmd+Shift+Right',
    context: 'monaco',
    handler: 'onNativeSelection',
    passthrough: true
  },
  selectionUpComposer: {
    id: 'selectionUpComposer',
    name: 'Extend Selection Up (Composer)',
    description: 'Native text selection in the chat composer',
    category: 'Chat Navigation',
    defaultBinding: 'Cmd+Shift+Up',
    defaultWebBinding: 'Cmd+Shift+Up',
    context: 'chat-input',
    handler: 'onNativeSelection',
    passthrough: true
  },
  selectionDownComposer: {
    id: 'selectionDownComposer',
    name: 'Extend Selection Down (Composer)',
    description: 'Native text selection in the chat composer',
    category: 'Chat Navigation',
    defaultBinding: 'Cmd+Shift+Down',
    defaultWebBinding: 'Cmd+Shift+Down',
    context: 'chat-input',
    handler: 'onNativeSelection',
    passthrough: true
  },
  selectionLeftComposer: {
    id: 'selectionLeftComposer',
    name: 'Extend Selection Left (Composer)',
    description: 'Native text selection in the chat composer',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+Shift+Left',
    defaultWebBinding: 'Cmd+Shift+Left',
    context: 'chat-input',
    handler: 'onNativeSelection',
    passthrough: true
  },
  selectionRightComposer: {
    id: 'selectionRightComposer',
    name: 'Extend Selection Right (Composer)',
    description: 'Native text selection in the chat composer',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+Shift+Right',
    defaultWebBinding: 'Cmd+Shift+Right',
    context: 'chat-input',
    handler: 'onNativeSelection',
    passthrough: true
  },
  switchChat: {
    id: 'switchChat',
    name: 'Switch Chat',
    description: 'Open the chat switcher to jump to any chat by name',
    category: 'Chat Navigation',
    defaultBinding: 'Cmd+E',
    defaultWebBinding: 'Cmd+E',
    context: 'global',
    handler: 'onSwitchChat'
  },
  switchWorktree: {
    id: 'switchWorktree',
    name: 'Switch Branch Chat',
    description: 'Jump between branched (worktree) chats',
    category: 'Chat Navigation',
    defaultBinding: 'Cmd+K B',
    defaultWebBinding: 'Cmd+K B',
    context: 'global',
    handler: 'onSwitchWorktree'
  },
  nextAttentionChat: {
    id: 'nextAttentionChat',
    name: 'Next Chat Needing Attention',
    description: 'Jump to the next chat waiting on you (approval, error, or unread)',
    category: 'Chat Navigation',
    defaultBinding: 'Cmd+K D',
    defaultWebBinding: 'Cmd+K D',
    context: 'global',
    handler: 'onNextAttentionChat'
  },
  switchProject: {
    id: 'switchProject',
    name: 'Switch Project',
    description: 'Open the project switcher to jump to any project',
    category: 'Project Navigation',
    defaultBinding: 'Cmd+Shift+E',
    defaultWebBinding: 'Cmd+Shift+E',
    context: 'global',
    handler: 'onSwitchProject'
  },
  nextProject: {
    id: 'nextProject',
    name: 'Next Project',
    description: 'Switch to the next project',
    category: 'Project Navigation',
    defaultBinding: 'Cmd+K Right',
    defaultWebBinding: 'Cmd+K Right',
    context: 'global',
    handler: 'onNextProject'
  },
  prevProject: {
    id: 'prevProject',
    name: 'Previous Project',
    description: 'Switch to the previous project',
    category: 'Project Navigation',
    defaultBinding: 'Cmd+K Left',
    defaultWebBinding: 'Cmd+K Left',
    context: 'global',
    handler: 'onPrevProject'
  },
  nextFileTab: {
    id: 'nextFileTab',
    name: 'Next File Tab',
    description: 'Switch to the next open file tab',
    category: 'File Navigation',
    defaultBinding: 'Cmd+Shift+]',
    defaultWebBinding: 'Cmd+Shift+]',
    context: 'global',
    handler: 'onNextFileTab'
  },
  prevFileTab: {
    id: 'prevFileTab',
    name: 'Previous File Tab',
    description: 'Switch to the previous open file tab',
    category: 'File Navigation',
    defaultBinding: 'Cmd+Shift+[',
    defaultWebBinding: 'Cmd+Shift+[',
    context: 'global',
    handler: 'onPrevFileTab'
  },
  focusFileEditor: {
    id: 'focusFileEditor',
    name: 'Focus File Editor',
    description: 'Move the cursor to the active file editor',
    category: 'Focus',
    defaultBinding: 'Cmd+K E',
    defaultWebBinding: 'Cmd+K E',
    context: 'global',
    handler: 'onFocusFileEditor'
  },
  reopenLastClosedFile: {
    id: 'reopenLastClosedFile',
    name: 'Reopen Last Closed File',
    description: 'Reopen the most recently closed file',
    category: 'File Navigation',
    defaultBinding: 'Cmd+Shift+T',
    defaultWebBinding: 'Cmd+K Z',
    context: 'global',
    handler: 'onReopenLastClosedFile'
  },
  cutFile: {
    id: 'cutFile',
    name: 'Cut File',
    description: 'Cut selected file for moving',
    category: 'File Navigation',
    defaultBinding: 'Cmd+X',
    defaultWebBinding: 'Cmd+X',
    context: 'file-tree',
    handler: 'onCutFile'
  },
  copyFile: {
    id: 'copyFile',
    name: 'Copy File',
    description: 'Copy selected file',
    category: 'File Navigation',
    defaultBinding: 'Cmd+C',
    defaultWebBinding: 'Cmd+C',
    context: 'file-tree',
    handler: 'onCopyFile'
  },
  pasteFile: {
    id: 'pasteFile',
    name: 'Paste File',
    description: 'Paste file to current location',
    category: 'File Navigation',
    defaultBinding: 'Cmd+V',
    defaultWebBinding: 'Cmd+V',
    context: 'file-tree',
    handler: 'onPasteFile'
  },
  nextRightSidebarTab: {
    id: 'nextRightSidebarTab',
    name: 'Next Right Sidebar Tab',
    description: 'Switch to the next right sidebar tab (files, changes, tasks, processes, browser)',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+Shift+Right',
    defaultWebBinding: 'Cmd+Shift+Right',
    context: 'global',
    handler: 'onNextRightSidebarTab'
  },
  prevRightSidebarTab: {
    id: 'prevRightSidebarTab',
    name: 'Previous Right Sidebar Tab',
    description: 'Switch to the previous right sidebar tab',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+Shift+Left',
    defaultWebBinding: 'Cmd+Shift+Left',
    context: 'global',
    handler: 'onPrevRightSidebarTab'
  },
  sidebarFiles: {
    id: 'sidebarFiles',
    name: 'Show Files',
    description: 'Open the right sidebar to the files tab',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+K F',
    defaultWebBinding: 'Cmd+K F',
    context: 'global',
    handler: 'onSidebarFiles'
  },
  sidebarChanges: {
    id: 'sidebarChanges',
    name: 'Show Changes',
    description: 'Open the right sidebar to the source-control changes tab',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+K G',
    defaultWebBinding: 'Cmd+K G',
    context: 'global',
    handler: 'onSidebarChanges'
  },
  sidebarTasks: {
    id: 'sidebarTasks',
    name: 'Show Tasks',
    description: 'Open the right sidebar to the tasks tab',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+K K',
    defaultWebBinding: 'Cmd+K K',
    context: 'global',
    handler: 'onSidebarTasks'
  },
  sidebarProcesses: {
    id: 'sidebarProcesses',
    name: 'Show Processes & Packages',
    description: 'Open the right sidebar to the processes and package commands tab',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+K R',
    defaultWebBinding: 'Cmd+K R',
    context: 'global',
    handler: 'onSidebarProcesses'
  },
  sidebarBrowser: {
    id: 'sidebarBrowser',
    name: 'Show Browser',
    description: 'Open the right sidebar to the browser tab',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+K V',
    defaultWebBinding: 'Cmd+K V',
    context: 'global',
    handler: 'onSidebarBrowser'
  },
  focusRightSidebar: {
    id: 'focusRightSidebar',
    name: 'Focus Right Sidebar',
    description: 'Move the cursor to the right sidebar, opening it if hidden',
    category: 'Focus',
    defaultBinding: 'Cmd+Shift+B',
    defaultWebBinding: 'Cmd+Shift+B',
    context: 'global',
    handler: 'onFocusRightSidebar'
  },
  runPackageCommand: {
    id: 'runPackageCommand',
    name: 'Package Commands',
    description: 'Show package commands and running processes',
    category: 'Panel Navigation',
    defaultBinding: 'Cmd+K N',
    defaultWebBinding: 'Cmd+K N',
    context: 'global',
    handler: 'onRunPackageCommand'
  },
  toggleSettings: {
    id: 'toggleSettings',
    name: 'Toggle Settings',
    description: 'Open or close the settings panel',
    category: 'Interface',
    defaultBinding: 'Cmd+,',
    defaultWebBinding: 'Cmd+,',
    context: 'global',
    handler: 'onToggleSettings'
  },
  toggleSidebar: {
    id: 'toggleSidebar',
    name: 'Toggle Chat Sidebar',
    description: 'Show or hide the left chat sidebar',
    category: 'Interface',
    defaultBinding: 'Cmd+Alt+B',
    defaultWebBinding: 'Cmd+Alt+B',
    context: 'global',
    handler: 'onToggleSidebar'
  },
  toggleFileBrowser: {
    id: 'toggleFileBrowser',
    name: 'Toggle Right Sidebar',
    description: 'Show or hide the right sidebar',
    category: 'Interface',
    defaultBinding: 'Cmd+B',
    defaultWebBinding: 'Cmd+B',
    context: 'global',
    handler: 'onToggleFileBrowser'
  },
  toggleTerminal: {
    id: 'toggleTerminal',
    name: 'Toggle Terminal',
    description: 'Show or hide the terminal panel',
    category: 'Terminal',
    defaultBinding: 'Cmd+J',
    defaultWebBinding: 'Cmd+J',
    context: 'global',
    handler: 'onToggleTerminal'
  },
  newTerminal: {
    id: 'newTerminal',
    name: 'New Terminal',
    description: 'Create a new terminal instance',
    category: 'Terminal',
    defaultBinding: 'Cmd+Shift+J',
    defaultWebBinding: 'Cmd+Shift+J',
    context: 'global',
    handler: 'onNewTerminal'
  },
  stopStreaming: {
    id: 'stopStreaming',
    name: 'Stop AI Response',
    description: 'Stop the current AI response generation',
    category: 'Chat Control',
    defaultBinding: 'Escape',
    defaultWebBinding: 'Escape',
    context: 'global',
    handler: 'onStopStreaming',
    allowInInput: true
  },
  approveToolRequests: {
    id: 'approveToolRequests',
    name: 'Approve Tool Requests',
    description: 'Approve all pending tool requests for the current chat',
    category: 'Chat Control',
    defaultBinding: 'Cmd+Enter',
    defaultWebBinding: 'Cmd+Enter',
    context: 'global',
    handler: 'onApproveToolRequests'
  },
  composerNewline: {
    id: 'composerNewline',
    name: 'Insert Newline',
    description: 'Insert a line break in the chat composer',
    category: 'Chat Control',
    defaultBinding: 'Cmd+Enter',
    defaultWebBinding: 'Cmd+Enter',
    context: 'chat-input',
    handler: 'onComposerNewline'
  },
  slashCommands: {
    id: 'slashCommands',
    name: 'Slash Commands',
    description: 'Open the slash command menu in the chat composer',
    category: 'Chat Control',
    defaultBinding: 'Cmd+/',
    defaultWebBinding: 'Cmd+/',
    context: 'global',
    handler: 'onSlashCommands'
  },
  dismissModal: {
    id: 'dismissModal',
    name: 'Close Modal',
    description: 'Close the open dialog or overlay',
    category: 'Interface',
    defaultBinding: 'Escape',
    defaultWebBinding: 'Escape',
    context: 'modal',
    handler: 'onDismissModal',
    allowInInput: true
  },
  dismissSlashMenu: {
    id: 'dismissSlashMenu',
    name: 'Dismiss Slash Menu',
    description: 'Close the slash command menu',
    category: 'Chat Control',
    defaultBinding: 'Escape',
    defaultWebBinding: 'Escape',
    context: 'slash-menu',
    handler: 'onDismissSlashMenu',
    allowInInput: true
  },
  changeModel: {
    id: 'changeModel',
    name: 'Change Model',
    description: 'Open the model picker for the current chat',
    category: 'Parameters',
    defaultBinding: 'Cmd+K M',
    defaultWebBinding: 'Cmd+K M',
    context: 'global',
    handler: 'onChangeModel'
  },
  changeThinkingLevel: {
    id: 'changeThinkingLevel',
    name: 'Change Thinking Level',
    description: 'Cycle the reasoning effort for models that support it',
    category: 'Parameters',
    defaultBinding: 'Cmd+K H',
    defaultWebBinding: 'Cmd+K H',
    context: 'global',
    handler: 'onChangeThinkingLevel'
  },
  changeWorkflow: {
    id: 'changeWorkflow',
    name: 'Change Workflow',
    description: 'Pick the workflow the next message runs',
    category: 'Parameters',
    defaultBinding: 'Cmd+K Y',
    defaultWebBinding: 'Cmd+K Y',
    context: 'global',
    handler: 'onChangeWorkflow'
  },
  editWorkflowParams: {
    id: 'editWorkflowParams',
    name: 'Edit Workflow Parameters',
    description: 'Open the parameter panel for the selected workflow',
    category: 'Parameters',
    defaultBinding: 'Cmd+K I',
    defaultWebBinding: 'Cmd+K I',
    context: 'global',
    handler: 'onEditWorkflowParams'
  }
};
