// Copyright (c) 2025 Reliant Labs
//
// Preset reference generator - generates documentation from preset YAML files.
//
// SOURCE OF TRUTH:
//   - internal/workflow/builtin/presets/*.yaml
//
// GENERATED FILES:
//   - generated/docs-source/workflows/presets-reference.generated.md
//
// Usage: go run ./tools/docgen/presets <output>
// Regenerate with: make generate-presets

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// ModelSelector represents the model configuration which can have id or tags
type ModelSelector struct {
	ID   string   `yaml:"id,omitempty"`
	Tags []string `yaml:"tags,omitempty"`
}

// Preset represents a preset YAML file structure
type Preset struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
	Tag         string `yaml:"tag"`
	Params      struct {
		Model        ModelSelector `yaml:"model"`
		Tools        []string      `yaml:"tools"`
		SpawnPresets []string      `yaml:"spawn_presets"`
		SystemPrompt string        `yaml:"system_prompt"`
		Temperature  float64       `yaml:"temperature"`
		MaxTurns     int           `yaml:"max_turns"`
	} `yaml:"params"`
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: %s <output>\n", os.Args[0])
		os.Exit(1)
	}

	output := os.Args[1]

	// Find presets directory relative to project root
	presetsDir := "internal/workflow/builtin/presets"

	presets, err := loadPresets(presetsDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error loading presets: %v\n", err)
		os.Exit(1)
	}

	markdown := generateMarkdown(presets)

	if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(output, []byte(markdown), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated preset reference: %s (%d presets)\n", output, len(presets))
}

func loadPresets(dir string) ([]Preset, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.yaml"))
	if err != nil {
		return nil, err
	}

	var presets []Preset
	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", file, err)
		}

		var preset Preset
		if err := yaml.Unmarshal(data, &preset); err != nil {
			return nil, fmt.Errorf("parsing %s: %w", file, err)
		}

		presets = append(presets, preset)
	}

	// Sort by name for consistent output
	sort.Slice(presets, func(i, j int) bool {
		return presets[i].Name < presets[j].Name
	})

	return presets, nil
}

func generateMarkdown(presets []Preset) string {
	var sb strings.Builder

	sb.WriteString(`---
# =============================================================================
# GENERATED FILE - DO NOT EDIT DIRECTLY
#
# Source of truth: internal/workflow/builtin/presets/*.yaml
# Generated by: go run ./tools/docgen/presets
# Regenerate with: make generate-presets
# =============================================================================
title: Built-in Presets Reference
weight: 25
description: Auto-generated reference for all built-in presets
---

This auto-generated reference documents all built-in presets available in Reliant.
For usage information and examples, see the [Presets Guide](/docs/workflows/presets/).

## Quick Reference

| Preset | Model | Tools | Description |
|--------|-------|-------|-------------|
`)

	// Generate summary table
	for _, p := range presets {
		// Format tools as a compact list
		toolsStr := formatTools(p.Params.Tools)

		// Truncate description for table
		desc := firstSentence(p.Description)
		if len(desc) > 80 {
			desc = desc[:77] + "..."
		}
		desc = strings.ReplaceAll(desc, "|", "\\|")

		sb.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n",
			p.Name,
			formatModel(p.Params.Model),
			toolsStr,
			desc,
		))
	}

	sb.WriteString("\n## Preset Details\n\n")

	// Generate detailed sections for each preset
	for _, p := range presets {
		sb.WriteString(fmt.Sprintf("### %s\n\n", p.Name))

		if p.Description != "" {
			sb.WriteString(p.Description + "\n\n")
		}

		// Parameters table
		sb.WriteString("| Parameter | Value |\n")
		sb.WriteString("|-----------|-------|\n")
		sb.WriteString(fmt.Sprintf("| **Model** | %s |\n", formatModel(p.Params.Model)))
		sb.WriteString(fmt.Sprintf("| **Tag** | `%s` |\n", p.Tag))

		if len(p.Params.Tools) > 0 {
			sb.WriteString(fmt.Sprintf("| **Tools** | %s |\n", formatToolsForDetail(p.Params.Tools)))
		}

		if len(p.Params.SpawnPresets) > 0 {
			sb.WriteString(fmt.Sprintf("| **Spawn Presets** | %s |\n", formatSpawnPresets(p.Params.SpawnPresets)))
		}

		sb.WriteString("\n---\n\n")
	}

	return sb.String()
}

func formatModel(model ModelSelector) string {
	if model.ID != "" {
		return "`" + model.ID + "`"
	}
	if len(model.Tags) > 0 {
		return "`tags:" + strings.Join(model.Tags, ",") + "`"
	}
	return "-"
}

func formatTools(tools []string) string {
	if len(tools) == 0 {
		return "-"
	}

	// Compact representation for table
	var parts []string
	for _, t := range tools {
		parts = append(parts, "`"+t+"`")
	}

	result := strings.Join(parts, ", ")
	if len(result) > 50 {
		// Truncate if too long
		count := len(tools)
		result = fmt.Sprintf("`%s` (+%d more)", tools[0], count-1)
	}
	return result
}

func formatToolsForDetail(tools []string) string {
	var parts []string
	for _, t := range tools {
		parts = append(parts, "`"+t+"`")
	}
	return strings.Join(parts, ", ")
}

func formatSpawnPresets(presets []string) string {
	var parts []string
	for _, p := range presets {
		parts = append(parts, "`"+p+"`")
	}
	return strings.Join(parts, ", ")
}

func firstSentence(s string) string {
	s = strings.TrimSpace(s)

	// Get first line first
	if idx := strings.Index(s, "\n"); idx > 0 {
		s = s[:idx]
	}

	// Then first sentence
	for _, delim := range []string{". ", "! ", "? "} {
		if idx := strings.Index(s, delim); idx > 0 {
			return s[:idx+1]
		}
	}

	return s
}
