// Code generated by tools/docgen/nodes. DO NOT EDIT.
// Source: proto annotations [(reliant)] in workflow_v2.proto
// Regenerate with: make generate-nodes

package schema

// init populates FieldDescriptions with descriptions from proto annotations.
// The map and GetFieldDescription function are defined in field_descriptions_base.go.
func init() {
	FieldDescriptions["approval.timeout"] = "How long to wait for approval"
	FieldDescriptions["approval.title"] = "Approval dialog title"
	FieldDescriptions["call_llm.model"] = "Model selector using tags (e.g. flagship) or explicit ID"
	FieldDescriptions["call_llm.system_prompt"] = "System message for this LLM call"
	FieldDescriptions["call_llm.temperature"] = "Temperature (0-1) controls randomness"
	FieldDescriptions["call_llm.thinking_level"] = "Extended thinking level for complex reasoning"
	FieldDescriptions["call_llm.tool_filter"] = "Filter which tools are available. Use tool names, glob patterns (edit*), tags (tag:search), or !exclusions (!bash)."
	FieldDescriptions["create_worktree.base_branch"] = "Base branch to branch from"
	FieldDescriptions["create_worktree.copy_files"] = "Files to copy from source repo (e.g. .env)"
	FieldDescriptions["create_worktree.force"] = "Force creation by deleting existing worktree"
	FieldDescriptions["create_worktree.name"] = "Worktree name, used in path"
	FieldDescriptions["execute_tools.tool_calls"] = "CEL expression for tool calls to execute"
	FieldDescriptions["loop.items"] = "CEL expression evaluating to a list or map to iterate over"
	FieldDescriptions["loop.key"] = "CEL expression for output map key per iteration"
	FieldDescriptions["loop.on_failure"] = "Failure policy for parallel iterations"
	FieldDescriptions["loop.parallel"] = "Execute all iterations concurrently"
	FieldDescriptions["loop.while"] = "CEL condition: loop continues while true"
	FieldDescriptions["loop.yield"] = "CEL expression to yield to user on loop exit"
	FieldDescriptions["router.fallback"] = "Fallback preset if routing decision fails"
	FieldDescriptions["router.model"] = "Model for routing decision (defaults to fast model)"
	FieldDescriptions["router.outputs"] = "Declared output mappings (name → CEL expression)"
	FieldDescriptions["router.system_prompt"] = "Custom system prompt for the routing LLM"
	FieldDescriptions["run.command"] = "Shell command to execute"
	FieldDescriptions["save_message.attachments"] = "Attachment IDs. CEL expression must return []string."
	FieldDescriptions["save_message.content"] = "Message content"
	FieldDescriptions["save_message.display_style"] = "UI display style hint"
	FieldDescriptions["save_message.role"] = "Message role"
	FieldDescriptions["save_message.tool_calls"] = "Tool calls from LLM response"
	FieldDescriptions["workflow.args"] = "Input values for the sub-workflow"
	FieldDescriptions["workflow.presets"] = "Preset configurations for sub-workflow inputs"
	FieldDescriptions["workflow.ref"] = "Workflow reference (builtin://name or project://name)"
}
