// Code generated by tools/docgen/nodes. DO NOT EDIT.
// Source: proto annotations [(reliant)] in workflow_v2.proto
// Regenerate with: make generate-nodes

package schema

// init populates FieldDescriptions with descriptions from proto annotations.
// The map and GetFieldDescription function are defined in field_descriptions_base.go.
func init() {
	FieldDescriptions["action.connection"] = "Id of the saved connection to authenticate with. Leave it empty to use your default connection"
	FieldDescriptions["action.uses"] = "Which integration action to run, as integration/action@major"
	FieldDescriptions["action.with"] = "Action parameters, keyed as in the action's schema. Values may be literals or {{ }} templates"
	FieldDescriptions["ask_question.metadata"] = "The questions to ask, as JSON: a questions list, each with question text and its options"
	FieldDescriptions["call_llm.model"] = "A model tag (flagship, fast, cheap) or an explicit model ID"
	FieldDescriptions["call_llm.skills"] = "Skills to preload into this call, by path, so the model starts with their instructions"
	FieldDescriptions["call_llm.system_prompt"] = "Optional instructions for how the model should behave on this call"
	FieldDescriptions["call_llm.temperature"] = "How varied replies are: 0 is the most repeatable, higher is more creative (0 to 2)"
	FieldDescriptions["call_llm.thinking_level"] = "Extended thinking level for complex reasoning"
	FieldDescriptions["compact.model"] = "Model used to summarize the conversation (defaults to the built-in summarization tier)"
	FieldDescriptions["create_worktree.base_branch"] = "The branch to start from. Empty uses the repository's default branch"
	FieldDescriptions["create_worktree.copy_files"] = "Exact paths from the project root to copy into the new worktree, such as untracked config"
	FieldDescriptions["create_worktree.force"] = "Force creation by deleting existing worktree"
	FieldDescriptions["create_worktree.name"] = "A short name for the worktree; it becomes part of the worktree's folder path"
	FieldDescriptions["execute_tools.tool_calls"] = "The tool calls to run: wire in the tool_calls output of the Call LLM step that requested them"
	FieldDescriptions["invoke_tool.params"] = "The tool's parameters, keyed as in its schema. Values may be literals or {{ }} templates"
	FieldDescriptions["invoke_tool.tool"] = "The tool to run, by name. Only tools that allow direct use from a workflow can be named"
	FieldDescriptions["loop.items"] = "What to iterate over: an expression yielding a list or map. Each iteration sees it as iter.item"
	FieldDescriptions["loop.key"] = "For parallel loops, each iteration's key in _results. Defaults to the iteration's index"
	FieldDescriptions["loop.on_failure"] = "Failure policy for parallel iterations"
	FieldDescriptions["loop.parallel"] = "Execute all iterations concurrently"
	FieldDescriptions["loop.passthrough"] = "Inputs of this workflow to hand to the loop body under the same name"
	FieldDescriptions["loop.while"] = "CEL condition: loop continues while true"
	FieldDescriptions["router.fallback"] = "Where to go if the routing decision fails: a preset name (workflow routing) or a node id (node routing)"
	FieldDescriptions["router.model"] = "The model that makes the routing decision (defaults to a fast model)"
	FieldDescriptions["router.outputs"] = "Named outputs for this step, each an expression over the chosen workflow's outputs"
	FieldDescriptions["router.system_prompt"] = "Instructions for the routing model, replacing the default routing prompt"
	FieldDescriptions["run.command"] = "The shell command to run in the project directory"
	FieldDescriptions["save_message.content"] = "The message text, usually a template over an earlier step's output"
	FieldDescriptions["save_message.display_style"] = "UI display style hint"
	FieldDescriptions["save_message.role"] = "Message role"
	FieldDescriptions["save_message.tool_calls"] = "Tool calls to save with an assistant message: the tool_calls a Call LLM step returned"
	FieldDescriptions["workflow.args"] = "Values for the sub-workflow's inputs, keyed by input name"
	FieldDescriptions["workflow.passthrough"] = "Inputs of this workflow to hand to the sub-workflow under the same name"
	FieldDescriptions["workflow.presets"] = "A preset to apply per input group, as group: preset. Use default for ungrouped inputs"
	FieldDescriptions["workflow.ref"] = "The workflow to run: builtin://<name> for a built-in, project://<name> for one in this project"
}
