// Copyright (c) 2025 Reliant Labs

// Command toolconfiggen generates the tool parameter catalog that
// tools_config.tools is validated against.
//
// It walks the live tool registry, instantiates every tool, reflects each
// one's FULL parameter schema — bound parameters included, since the point is
// to describe what a human may bind, not what the model may set — and writes
// the result to internal/llm/tools/toolcatalog/catalog_generated.go.
//
// Run it with `go generate ./internal/llm/tools/...` or `make generate-tool-catalog`.
//
// It is a generator rather than a hand-written list because the alternative is
// two lists that must agree and are edited separately. We shipped registry /
// LiteLLM drift twice in one day from exactly that shape, and the failure is
// silent in the direction that matters: a binding for a parameter nobody has
// quietly does nothing.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"

	"github.com/reliant-labs/reliant/internal/llm/tools"
)

const outputPath = "toolcatalog/catalog_generated.go"

func main() {
	content, err := generate()
	if err != nil {
		fmt.Fprintf(os.Stderr, "toolconfiggen: %v\n", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "toolconfiggen: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outputPath, content, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "toolconfiggen: %v\n", err)
		os.Exit(1)
	}
}

// toolEntry is one tool's catalog row.
type toolEntry struct {
	Name       string
	Bindable   []string
	Unbindable map[string]string
}

func generate() ([]byte, error) {
	entries, err := collect()
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go run ./internal/llm/tools/cmd/toolconfiggen; DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString("package toolcatalog\n")
	buf.WriteString("\n")
	buf.WriteString("// generatedToolParams is the bindable surface of every registered tool,\n")
	buf.WriteString("// projected from each tool's reflected parameter schema.\n")
	buf.WriteString("var generatedToolParams = map[string]ToolParams{\n")
	for _, entry := range entries {
		fmt.Fprintf(&buf, "\t%q: {\n", entry.Name)

		buf.WriteString("\t\tBindable: map[string]struct{}{\n")
		for _, param := range entry.Bindable {
			fmt.Fprintf(&buf, "\t\t\t%q: {},\n", param)
		}
		buf.WriteString("\t\t},\n")

		buf.WriteString("\t\tUnbindable: map[string]string{\n")
		reasonKeys := make([]string, 0, len(entry.Unbindable))
		for param := range entry.Unbindable {
			reasonKeys = append(reasonKeys, param)
		}
		sort.Strings(reasonKeys)
		for _, param := range reasonKeys {
			fmt.Fprintf(&buf, "\t\t\t%q: %q,\n", param, entry.Unbindable[param])
		}
		buf.WriteString("\t\t},\n")

		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, buf.String())
	}
	return formatted, nil
}

// collect instantiates every registered tool and reads its parameter schema.
//
// The factory is constructed with no dependencies. That is deliberate and it
// is checked: a tool whose parameter schema depended on a live database or a
// configured provider would produce a different catalog on a developer's
// machine than in CI, which is the one property a generated file cannot have.
// Every tool in the registry reflects its schema from a Go struct, so nil deps
// are sufficient — and if that ever stops being true, the tool returns a nil
// schema here and this fails rather than emitting a short catalog.
func collect() ([]toolEntry, error) {
	factory := tools.NewToolsFactory(nil)
	registry := tools.GetToolRegistry()
	if len(registry) == 0 {
		return nil, fmt.Errorf("tool registry is empty; refusing to write an empty catalog")
	}

	seen := map[string]struct{}{}
	entries := make([]toolEntry, 0, len(registry))

	for _, def := range registry {
		tool := def.Factory(factory)
		if tool == nil {
			return nil, fmt.Errorf("tool %q: factory returned nil", def.Name)
		}

		schema := tool.ParamSchema()
		if schema == nil {
			return nil, fmt.Errorf("tool %q: nil parameter schema", def.Name)
		}

		// ParamSchema hides parameters that are already bound by default.
		// The catalog must describe what a human MAY bind, so those have to
		// be added back — generate_image's `model` is bound by default and
		// is precisely the parameter this feature exists to let people
		// configure.
		params := map[string]struct{}{}
		if schema.Properties != nil {
			for pair := schema.Properties.Oldest(); pair != nil; pair = pair.Next() {
				params[pair.Key] = struct{}{}
			}
		}
		if bindable, ok := tool.(tools.BindableTool); ok {
			for _, name := range bindable.Bindings().Names() {
				params[name] = struct{}{}
			}
		}

		// A parameter named by the unbindable policy must actually exist on
		// the tool. Without this check a renamed parameter would leave a
		// policy rule matching nothing, and the parameter it used to protect
		// would become bindable with no one noticing.
		unbindable := map[string]string{}
		for param, reason := range tools.UnbindableParams(def.Name) {
			if _, exists := params[param]; !exists {
				return nil, fmt.Errorf(
					"unbindable policy names %q.%q, but that tool has no such parameter (it has: %v)",
					def.Name, param, sortedKeys(params))
			}
			unbindable[param] = reason
			delete(params, param)
		}

		if _, duplicate := seen[def.Name]; duplicate {
			return nil, fmt.Errorf("tool %q is registered more than once", def.Name)
		}
		seen[def.Name] = struct{}{}

		entries = append(entries, toolEntry{
			Name:       def.Name,
			Bindable:   sortedKeys(params),
			Unbindable: unbindable,
		})
	}

	// Every tool the policy mentions must be a registered tool. A policy
	// entry for a deleted tool is dead weight that reads as protection.
	for _, name := range tools.UnbindablePolicyTools() {
		if _, registered := seen[name]; !registered {
			return nil, fmt.Errorf("unbindable policy names tool %q, which is not in the registry", name)
		}
	}

	sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })
	return entries, nil
}

func sortedKeys(set map[string]struct{}) []string {
	keys := make([]string, 0, len(set))
	for key := range set {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
