// Code generated by tools/docgen/celref. DO NOT EDIT.
// Source: internal/workflow/v3/cel_reflection.go (type registry)

package reference

// CELNamespaceInfo describes a CEL namespace
type CELNamespaceInfo struct {
	Name        string
	Description string
	Fields      []CELFieldInfo
	IsDynamic   bool
}

// CELFieldInfo describes a field in a typed namespace
type CELFieldInfo struct {
	Name        string
	Type        string
	Description string
}

// CELFunctionInfo describes a custom CEL function
type CELFunctionInfo struct {
	Name        string
	Signature   string
	Description string
	Example     string
}

// CELNodeOutputTypeInfo describes an output type for a node
type CELNodeOutputTypeInfo struct {
	NodeType    string
	Description string
	AccessPath  string
	Fields      []CELFieldInfo
}

// CELHelperTypeInfo describes a nested/helper type used in node outputs
type CELHelperTypeInfo struct {
	Name        string
	Description string
	AccessPath  string
	Fields      []CELFieldInfo
}

// CELNamespaces contains all available CEL namespaces
var CELNamespaces = []CELNamespaceInfo{
	{
		Name:        "inputs",
		Description: "Workflow input values passed at invocation",
		IsDynamic:   true,
	},
	{
		Name:        "iter",
		Description: "Loop iteration context (iteration count, first/last flags)",
		IsDynamic:   false,
		Fields: []CELFieldInfo{
			{Name: "index", Type: "int", Description: "Alias for iteration (0-indexed)"},
			{Name: "iteration", Type: "int", Description: "Current loop iteration (0-indexed)"},
			{Name: "key", Type: "string", Description: "Current key when iterating over a map"},
			{Name: "prev_outputs", Type: "map", Description: "Outputs from the previous iteration"},
			{Name: "value", Type: "any", Description: "Current value when iterating"},
		},
	},
	{
		Name:        "nodes",
		Description: "Output from completed nodes (nodes.<id>.<field>)",
		IsDynamic:   true,
	},
	{
		Name:        "outputs",
		Description: "Loop iteration outputs for while condition evaluation",
		IsDynamic:   true,
	},
	{
		Name:        "thread",
		Description: "Current thread context (token_count, message_count)",
		IsDynamic:   true,
	},
	{
		Name:        "trigger",
		Description: "Trigger context (message, attachments) for triggered workflows",
		IsDynamic:   true,
	},
	{
		Name:        "workflow",
		Description: "Workflow execution context (id, name, run_id, etc.)",
		IsDynamic:   false,
		Fields: []CELFieldInfo{
			{Name: "branch", Type: "string", Description: "Current git branch (empty if not in git repo)"},
			{Name: "id", Type: "string", Description: "Workflow execution ID (unique per run)"},
			{Name: "mode", Type: "string", Description: "Execution mode (auto, manual, plan)"},
			{Name: "name", Type: "string", Description: "Workflow definition name"},
			{Name: "path", Type: "string", Description: "Working directory path"},
			{Name: "run_id", Type: "string", Description: "Workflow run ID (Temporal run ID)"},
			{Name: "session_id", Type: "string", Description: "Session ID for the workflow"},
			{Name: "worktree_path", Type: "string", Description: "Git worktree path (if in a worktree)"},
		},
	},
}

// CELFunctions contains all custom CEL functions
var CELFunctions = []CELFunctionInfo{
	{Name: "parse_json", Signature: "parseJson(string) -> value", Description: "Parses a JSON string into a value", Example: "parseJson(nodes.run.stdout)"},
	{Name: "to_json", Signature: "toJson(value) -> string", Description: "Converts a value to a JSON string", Example: "toJson(inputs.config)"},
	{Name: "coalesce", Signature: "coalesce(a, b, ...) -> value", Description: "Returns the first non-null value", Example: "coalesce(inputs.model, 'claude-4-sonnet')"},
	{Name: "get_or_default", Signature: "getOrDefault(map, key, default) -> value", Description: "Safely gets a map value with a default", Example: "getOrDefault(config, 'timeout', 30)"},
	{Name: "parse_duration", Signature: "parseDuration(string) -> duration", Description: "Parses a duration string (e.g., '5m', '1h')", Example: "parseDuration('5m')"},
	{Name: "spawn", Signature: "spawn(workflow, presets) -> string", Description: "Builds a spawn filter spec for the given workflow and presets", Example: "spawn(workflow.name, inputs.spawn_presets)"},
	{Name: "join", Signature: "join(list, separator) -> string", Description: "Joins list elements into a string", Example: "join(inputs.tags, ',')"},
}

// CELNodeOutputTypes contains output type information for each node type
var CELNodeOutputTypes = []CELNodeOutputTypeInfo{
	{
		NodeType:    "approval",
		Description: "Output from approval requests",
		AccessPath:  "nodes.<id>.*",
		Fields: []CELFieldInfo{
			{Name: "action_taken", Type: "string", Description: ""},
			{Name: "approval_id", Type: "string", Description: ""},
			{Name: "data", Type: "map", Description: ""},
			{Name: "status", Type: "string", Description: ""},
		},
	},
	{
		NodeType:    "call_llm",
		Description: "Output from LLM inference calls",
		AccessPath:  "nodes.<id>.*",
		Fields: []CELFieldInfo{
			{Name: "message", Type: "object", Description: ""},
			{Name: "response_text", Type: "string", Description: ""},
			{Name: "thinking", Type: "object", Description: ""},
			{Name: "token_count", Type: "int", Description: ""},
			{Name: "tool_calls", Type: "array", Description: ""},
			{Name: "compaction_threshold", Type: "int", Description: ""},
		},
	},
	{
		NodeType:    "compact",
		Description: "Output from thread compaction",
		AccessPath:  "nodes.<id>.*",
		Fields: []CELFieldInfo{
			{Name: "message", Type: "object", Description: ""},
		},
	},
	{
		NodeType:    "create_worktree",
		Description: "Output from creating git worktrees",
		AccessPath:  "nodes.<id>.*",
		Fields: []CELFieldInfo{
			{Name: "base_branch", Type: "string", Description: ""},
			{Name: "branch", Type: "string", Description: ""},
			{Name: "id", Type: "string", Description: ""},
			{Name: "name", Type: "string", Description: ""},
			{Name: "path", Type: "string", Description: ""},
			{Name: "repo_id", Type: "string", Description: ""},
			{Name: "status", Type: "string", Description: ""},
		},
	},
	{
		NodeType:    "delete_worktree",
		Description: "Output from deleting git worktrees",
		AccessPath:  "nodes.<id>.*",
		Fields: []CELFieldInfo{
			{Name: "deleted", Type: "bool", Description: ""},
		},
	},
	{
		NodeType:    "execute_tools",
		Description: "Output from tool execution",
		AccessPath:  "nodes.<id>.*",
		Fields: []CELFieldInfo{
			{Name: "message", Type: "object", Description: ""},
			{Name: "response_data", Type: "map", Description: ""},
			{Name: "thread_token_count", Type: "int", Description: ""},
			{Name: "tool_results", Type: "array", Description: ""},
			{Name: "total_result_chars", Type: "int", Description: ""},
		},
	},
	{
		NodeType:    "run",
		Description: "Output from shell command execution",
		AccessPath:  "nodes.<id>.*",
		Fields: []CELFieldInfo{
			{Name: "exit_code", Type: "int", Description: ""},
			{Name: "stderr", Type: "string", Description: ""},
			{Name: "stdout", Type: "string", Description: ""},
		},
	},
	{
		NodeType:    "save_message",
		Description: "Output from saving messages to thread",
		AccessPath:  "nodes.<id>.*",
		Fields: []CELFieldInfo{
			{Name: "message", Type: "object", Description: ""},
			{Name: "message_count", Type: "int", Description: ""},
			{Name: "message_id", Type: "string", Description: ""},
			{Name: "thread", Type: "string", Description: ""},
			{Name: "thread_token_count", Type: "int", Description: ""},
			{Name: "tool_calls", Type: "array", Description: ""},
			{Name: "tool_results", Type: "array", Description: ""},
		},
	},
}

// CELHelperTypes contains nested/helper types used in node outputs
var CELHelperTypes = []CELHelperTypeInfo{
	{
		Name:        "MessageOutput",
		Description: "Standardized output for activities that produce messages",
		AccessPath:  "nodes.<id>.message.*",
		Fields: []CELFieldInfo{
			{Name: "id", Type: "string", Description: "Unique message ID"},
			{Name: "role", Type: "string", Description: "Message role: \\\"user\\\", \\\"assistant\\\", or \\\"system\\\""},
			{Name: "text", Type: "string", Description: "Message content text"},
		},
	},
	{
		Name:        "ThinkingOutput",
		Description: "Extended thinking content from LLM (when thinking_level is set)",
		AccessPath:  "nodes.<id>.thinking.*",
		Fields: []CELFieldInfo{
			{Name: "content", Type: "string", Description: "Raw thinking text"},
			{Name: "signature", Type: "string", Description: "Signature for multi-turn preservation"},
		},
	},
	{
		Name:        "ToolCall",
		Description: "Tool invocation request from the LLM",
		AccessPath:  "nodes.<id>.tool_calls[*].*",
		Fields: []CELFieldInfo{
			{Name: "id", Type: "string", Description: "Unique tool call ID"},
			{Name: "name", Type: "string", Description: "Name of the tool being called"},
			{Name: "input", Type: "string", Description: "JSON-encoded input parameters"},
			{Name: "type", Type: "string", Description: "Content block type (for streaming)"},
			{Name: "finished", Type: "bool", Description: "Whether streaming is complete"},
			{Name: "block_index", Type: "int", Description: "Position in message blocks"},
			{Name: "thought_signature", Type: "string", Description: "For Gemini API requirement"},
		},
	},
	{
		Name:        "ToolResult",
		Description: "Result from executing a tool call",
		AccessPath:  "nodes.<id>.tool_results[*].*",
		Fields: []CELFieldInfo{
			{Name: "tool_call_id", Type: "string", Description: "ID of the tool call this result is for"},
			{Name: "name", Type: "string", Description: "Name of the tool that was executed"},
			{Name: "content", Type: "string", Description: "Tool execution result content"},
			{Name: "metadata", Type: "string", Description: "Additional metadata about the execution"},
			{Name: "is_error", Type: "bool", Description: "Whether the tool execution resulted in an error"},
		},
	},
}

// GetCELNamespace returns info about a specific namespace
func GetCELNamespace(name string) (CELNamespaceInfo, bool) {
	for _, ns := range CELNamespaces {
		if ns.Name == name {
			return ns, true
		}
	}
	return CELNamespaceInfo{}, false
}

// GetCELNodeOutputType returns info about a specific node output type
func GetCELNodeOutputType(nodeType string) (CELNodeOutputTypeInfo, bool) {
	for _, nt := range CELNodeOutputTypes {
		if nt.NodeType == nodeType {
			return nt, true
		}
	}
	return CELNodeOutputTypeInfo{}, false
}

// GetCELHelperType returns info about a specific helper type
func GetCELHelperType(name string) (CELHelperTypeInfo, bool) {
	for _, ht := range CELHelperTypes {
		if ht.Name == name {
			return ht, true
		}
	}
	return CELHelperTypeInfo{}, false
}
