// Code generated by tools/docgen/v3schema. DO NOT EDIT.
// Source of truth: v3.AllInputTypes() registry
// AST parsing used only for docstrings

package reference

// InputTypeInfo contains documentation for an input type.
type InputTypeInfo struct {
	Name        string           // Go type name
	TypeName    string           // YAML type value
	Summary     string           // Brief description
	Description string           // Full description
	Example     string           // YAML example
	Fields      []InputFieldInfo // Struct fields
}

// InputFieldInfo contains documentation for an input field.
type InputFieldInfo struct {
	Name        string // YAML field name
	Type        string // Field type
	Required    bool   // Is field required
	Description string // Field description
}

// InputTypes is the registry of all input type documentation.
var InputTypes = map[string]InputTypeInfo{
	"any": {
		Name:        "AnyInput",
		TypeName:    "any",
		Summary:     "AnyInput accepts any JSON-serializable value.",
		Description: "AnyInput accepts any JSON-serializable value.\nUse when the input type is dynamic or varies at runtime.\nPrefer more specific types when possible for better validation.\n\nExample:\n\n\tinputs:\n\t  extra_data:\n\t    type: any\n\t    description: \"Additional data (any format)\"",
		Example:     "inputs:\n\t  extra_data:\n\t    type: any\n\t    description: \"Additional data (any format)\"",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "any", Required: false, Description: ""},
		},
	},
	"array": {
		Name:        "ArrayInput",
		TypeName:    "array",
		Summary:     "ArrayInput accepts a list of values with optional length constraints.",
		Description: "ArrayInput accepts a list of values with optional length constraints.\nUse for lists of items that don't fit other specialized types.\n\nExample:\n\n\tinputs:\n\t  tags:\n\t    type: array\n\t    description: \"Tags to apply\"\n\t    default: []\n\t    min_items: 0\n\t    max_items: 5",
		Example:     "inputs:\n\t  tags:\n\t    type: array\n\t    description: \"Tags to apply\"\n\t    default: []\n\t    min_items: 0\n\t    max_items: 5",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "any", Required: false, Description: "Array value"},
			{Name: "min_items", Type: "integer", Required: false, Description: ""},
			{Name: "max_items", Type: "integer", Required: false, Description: ""},
		},
	},
	"attachments": {
		Name:        "AttachmentsInput",
		TypeName:    "attachments",
		Summary:     "AttachmentsInput accepts file attachments for the workflow.",
		Description: "AttachmentsInput accepts file attachments for the workflow.\nFiles are uploaded and made available to LLM calls.\n\nExample:\n\n\tinputs:\n\t  files:\n\t    type: attachments\n\t    description: \"Files to analyze\"\n\t    min_items: 1\n\t    max_items: 10",
		Example:     "inputs:\n\t  files:\n\t    type: attachments\n\t    description: \"Files to analyze\"\n\t    min_items: 1\n\t    max_items: 10",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "any", Required: false, Description: "Array of attachments"},
			{Name: "min_items", Type: "integer", Required: false, Description: ""},
			{Name: "max_items", Type: "integer", Required: false, Description: ""},
		},
	},
	"boolean": {
		Name:        "BooleanInput",
		TypeName:    "boolean",
		Summary:     "BooleanInput accepts true/false values.",
		Description: "BooleanInput accepts true/false values.\nUse for feature flags, toggles, or binary options.\n\nExample:\n\n\tinputs:\n\t  verbose:\n\t    type: boolean\n\t    description: \"Enable verbose output\"\n\t    default: false\n\t  use_cache:\n\t    type: boolean\n\t    default: true",
		Example:     "inputs:\n\t  verbose:\n\t    type: boolean\n\t    description: \"Enable verbose output\"\n\t    default: false\n\t  use_cache:\n\t    type: boolean\n\t    default: true",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "boolean", Required: false, Description: ""},
		},
	},
	"enum": {
		Name:        "EnumInput",
		TypeName:    "enum",
		Summary:     "EnumInput accepts values from a predefined list of options.",
		Description: "EnumInput accepts values from a predefined list of options.\nUse for mode selection, choices, or constrained options.\nSet multi: true to allow selecting multiple values.\n\nExample:\n\n\tinputs:\n\t  mode:\n\t    type: enum\n\t    description: \"Operation mode\"\n\t    enum: [fast, balanced, thorough]\n\t    default: balanced\n\t  languages:\n\t    type: enum\n\t    description: \"Target languages\"\n\t    enum: [go, python, typescript, rust]\n\t    multi: true\n\t    default: [go, typescript]",
		Example:     "inputs:\n\t  mode:\n\t    type: enum\n\t    description: \"Operation mode\"\n\t    enum: [fast, balanced, thorough]\n\t    default: balanced\n\t  languages:\n\t    type: enum\n\t    description: \"Target languages\"\n\t    enum: [go, python, typescript, rust]\n\t    multi: true\n\t    default: [go, typescript]",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "any", Required: false, Description: "String if single, []string if Multi"},
			{Name: "enum", Type: "string[]", Required: false, Description: ""},
			{Name: "multi", Type: "boolean", Required: false, Description: ""},
		},
	},
	"group": {
		Name:        "GroupInput",
		TypeName:    "group",
		Summary:     "",
		Description: "",
		Example:     "",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "presets", Type: "PresetsConfig", Required: false, Description: "Preset configuration (tag and default)"},
			{Name: "inputs", Type: "object", Required: false, Description: "Nested inputs"},
		},
	},
	"integer": {
		Name:        "IntegerInput",
		TypeName:    "integer",
		Summary:     "IntegerInput accepts whole numbers with optional min/max constraints.",
		Description: "IntegerInput accepts whole numbers with optional min/max constraints.\nUse for counts, limits, or iteration bounds.\n\nExample:\n\n\tinputs:\n\t  max_turns:\n\t    type: integer\n\t    description: \"Maximum agent loop iterations\"\n\t    default: 10\n\t    min: 1\n\t    max: 100",
		Example:     "inputs:\n\t  max_turns:\n\t    type: integer\n\t    description: \"Maximum agent loop iterations\"\n\t    default: 10\n\t    min: 1\n\t    max: 100",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "integer", Required: false, Description: ""},
			{Name: "min", Type: "integer", Required: false, Description: ""},
			{Name: "max", Type: "integer", Required: false, Description: ""},
		},
	},
	"message": {
		Name:        "MessageInput",
		TypeName:    "message",
		Summary:     "MessageInput accepts the primary user message/prompt.",
		Description: "MessageInput accepts the primary user message/prompt.\nThis is typically the main input for chat-style workflows.\nThe UI will provide a rich text input.\n\nExample:\n\n\tinputs:\n\t  message:\n\t    type: message\n\t    description: \"Your question or request\"\n\t    required: true",
		Example:     "inputs:\n\t  message:\n\t    type: message\n\t    description: \"Your question or request\"\n\t    required: true",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "string", Required: false, Description: ""},
		},
	},
	"model": {
		Name:        "ModelInput",
		TypeName:    "model",
		Summary:     "ModelInput provides a model selector with available LLM options.",
		Description: "ModelInput provides a model selector with available LLM options.\nThe UI will show a dropdown of supported models.\n\nExample:\n\n\tinputs:\n\t  model:\n\t    type: model\n\t    description: \"LLM model to use\"\n\t    default:\n\t      id: claude-4-sonnet",
		Example:     "inputs:\n\t  model:\n\t    type: model\n\t    description: \"LLM model to use\"\n\t    default:\n\t      id: claude-4-sonnet",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "ModelSelector", Required: false, Description: ""},
		},
	},
	"number": {
		Name:        "NumberInput",
		TypeName:    "number",
		Summary:     "NumberInput accepts decimal numbers with optional min/max constraints.",
		Description: "NumberInput accepts decimal numbers with optional min/max constraints.\nUse for percentages, ratios, or any floating-point values.\n\nExample:\n\n\tinputs:\n\t  temperature:\n\t    type: number\n\t    description: \"LLM temperature (0.0-1.0)\"\n\t    default: 0.7\n\t    min: 0.0\n\t    max: 1.0",
		Example:     "inputs:\n\t  temperature:\n\t    type: number\n\t    description: \"LLM temperature (0.0-1.0)\"\n\t    default: 0.7\n\t    min: 0.0\n\t    max: 1.0",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "number", Required: false, Description: ""},
			{Name: "min", Type: "number", Required: false, Description: ""},
			{Name: "max", Type: "number", Required: false, Description: ""},
		},
	},
	"object": {
		Name:        "ObjectInput",
		TypeName:    "object",
		Summary:     "ObjectInput accepts structured key-value data with JSON Schema validation.",
		Description: "ObjectInput accepts structured key-value data with JSON Schema validation.\nUse for configuration objects or complex nested data.\n\nExample:\n\n\tinputs:\n\t  config:\n\t    type: object\n\t    description: \"Additional configuration\"\n\t    properties:\n\t      timeout:\n\t        type: integer\n\t        minimum: 1\n\t      retries:\n\t        type: integer\n\t        minimum: 0\n\t    required:\n\t      - timeout\n\t    default:\n\t      timeout: 30\n\t      retries: 3",
		Example:     "inputs:\n\t  config:\n\t    type: object\n\t    description: \"Additional configuration\"\n\t    properties:\n\t      timeout:\n\t        type: integer\n\t        minimum: 1\n\t      retries:\n\t        type: integer\n\t        minimum: 0\n\t    required:\n\t      - timeout\n\t    default:\n\t      timeout: 30\n\t      retries: 3",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "properties", Type: "object", Required: false, Description: "JSON Schema fields"},
			{Name: "required", Type: "string[]", Required: false, Description: ""},
			{Name: "additionalProperties", Type: "boolean", Required: false, Description: ""},
			{Name: "default", Type: "any", Required: false, Description: ""},
		},
	},
	"preset": {
		Name:        "PresetInput",
		TypeName:    "preset",
		Summary:     "PresetInput provides a dynamic preset picker filtered by tags.",
		Description: "PresetInput provides a dynamic preset picker filtered by tags.\nThe available presets are loaded at API layer based on the configured tags.\nUse for selecting one or more presets (e.g., spawn presets for agent workflow).\n\nExample:\n\n\tinputs:\n\t  spawn_presets:\n\t    type: preset\n\t    tags: [agent]      # Filter presets by these tags\n\t    multi: true        # Allow multiple selections\n\t    default: [general, researcher, code_reviewer]\n\t    description: Presets available for spawn tool",
		Example:     "inputs:\n\t  spawn_presets:\n\t    type: preset\n\t    tags: [agent]      # Filter presets by these tags\n\t    multi: true        # Allow multiple selections\n\t    default: [general, researcher, code_reviewer]\n\t    description: Presets available for spawn tool",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "any", Required: false, Description: "String if single, []string if Multi"},
			{Name: "tags", Type: "string[]", Required: false, Description: "Filter presets by these tags"},
			{Name: "multi", Type: "boolean", Required: false, Description: ""},
		},
	},
	"string": {
		Name:        "StringInput",
		TypeName:    "string",
		Summary:     "StringInput accepts text values with optional validation constraints.",
		Description: "StringInput accepts text values with optional validation constraints.\nUse for free-form text like prompts, names, or descriptions.\n\nExample:\n\n\tinputs:\n\t  query:\n\t    type: string\n\t    description: \"The search query\"\n\t    required: true\n\t  username:\n\t    type: string\n\t    default: \"anonymous\"\n\t    pattern: \"^[a-z0-9_]+$\"\n\t    min_length: 3\n\t    max_length: 20",
		Example:     "inputs:\n\t  query:\n\t    type: string\n\t    description: \"The search query\"\n\t    required: true\n\t  username:\n\t    type: string\n\t    default: \"anonymous\"\n\t    pattern: \"^[a-z0-9_]+$\"\n\t    min_length: 3\n\t    max_length: 20",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "string", Required: false, Description: ""},
			{Name: "pattern", Type: "string", Required: false, Description: ""},
			{Name: "min_length", Type: "integer", Required: false, Description: ""},
			{Name: "max_length", Type: "integer", Required: false, Description: ""},
		},
	},
	"tools": {
		Name:        "ToolsInput",
		TypeName:    "tools",
		Summary:     "ToolsInput selects which tools are available to the workflow.",
		Description: "ToolsInput selects which tools are available to the workflow.\nTools can be specified by name or tag (e.g., \"tag:search\").\n\nExample:\n\n\tinputs:\n\t  tools:\n\t    type: tools\n\t    description: \"Available tools\"\n\t    default: [view, edit, grep, glob, tag:mcp]",
		Example:     "inputs:\n\t  tools:\n\t    type: tools\n\t    description: \"Available tools\"\n\t    default: [view, edit, grep, glob, tag:mcp]",
		Fields: []InputFieldInfo{
			{Name: "description", Type: "string", Required: false, Description: ""},
			{Name: "ui", Type: "string", Required: false, Description: ""},
			{Name: "type", Type: "string", Required: true, Description: ""},
			{Name: "default", Type: "any", Required: false, Description: "Array of tool names"},
		},
	},
}

// GetInputType returns documentation for a specific input type.
func GetInputType(typeName string) (InputTypeInfo, bool) {
	info, ok := InputTypes[typeName]
	return info, ok
}

// ListInputTypes returns a list of all input type names.
func ListInputTypes() []string {
	types := make([]string, 0, len(InputTypes))
	for name := range InputTypes {
		types = append(types, name)
	}
	return types
}
