// Code generated by tools/docgen/llmschema. DO NOT EDIT.
// Regenerate with: make generate-llm-schema
//
// This schema is auto-generated from v3 registries:
//   - v3.AllNodeTypes() for node types
//   - v3.AllInputTypes() for input types
//
// Adding a new node or input type? Just register it in the appropriate init()
// block and regenerate this file.

package reference

// LLMWorkflowSchema is the JSON Schema for workflow definitions.
// Used by LLM tools for parameter validation.
const LLMWorkflowSchema = `{
  "type": "object",
  "description": "Workflow definition for Reliant. Auto-generated from v3 registries.",
  "properties": {
    "apiVersion": {
      "type": "string",
      "description": "APIVersion specifies the schema version. Optional, for future compatibility."
    },
    "description": {
      "type": "string",
      "description": "Description documents what this workflow does. Shown in list_workflows output."
    },
    "edges": {
      "type": "array",
      "description": "Edges connecting nodes",
      "items": {
        "type": "object",
        "description": "Edge connecting nodes",
        "properties": {
          "cases": {
            "type": "array",
            "description": "Target cases with optional conditions",
            "items": {
              "type": "object",
              "properties": {
                "condition": {
                  "type": "string",
                  "description": "CEL condition (if omitted acts as default)"
                },
                "label": {
                  "type": "string",
                  "description": "Label for this case"
                },
                "to": {
                  "type": "string",
                  "description": "Target node ID"
                }
              },
              "required": [
                "to"
              ]
            }
          },
          "from": {
            "type": "string",
            "description": "Source node ID"
          }
        },
        "required": [
          "from",
          "cases"
        ]
      }
    },
    "entry": {
      "description": "Entry node ID (string) or array of IDs for parallel start"
    },
    "inputs": {
      "type": "object",
      "description": "Workflow inputs with schemas",
      "additionalProperties": {
        "type": "object",
        "description": "Input parameter definition",
        "properties": {
          "default": {
            "description": "Default value for this input"
          },
          "description": {
            "type": "string",
            "description": "Human-readable description of this input"
          },
          "enum": {
            "type": "array",
            "description": "For type: enum",
            "items": {
              "type": "string"
            }
          },
          "inputs": {
            "type": "object",
            "description": "Nested inputs",
            "additionalProperties": {}
          },
          "max": {
            "type": "number",
            "description": "For type: number"
          },
          "max_items": {
            "type": "integer",
            "description": "For type: array"
          },
          "max_length": {
            "type": "integer",
            "description": "For type: string"
          },
          "min": {
            "type": "number",
            "description": "For type: number"
          },
          "min_items": {
            "type": "integer",
            "description": "For type: array"
          },
          "min_length": {
            "type": "integer",
            "description": "For type: string"
          },
          "multi": {
            "type": "boolean",
            "description": "For type: enum"
          },
          "pattern": {
            "type": "string",
            "description": "For type: string"
          },
          "required": {
            "type": "boolean",
            "description": "Whether this input is required"
          },
          "tag": {
            "type": "string",
            "description": "Tag for preset matching (e.g., \"agent\")"
          },
          "tags": {
            "type": "array",
            "description": "Filter presets by these tags",
            "items": {
              "type": "string"
            }
          },
          "type": {
            "type": "string",
            "description": "Input type. Valid types: any, array, attachments, boolean, enum, group, integer, message, model, number, object, preset, string, tools",
            "enum": [
              "any",
              "array",
              "attachments",
              "boolean",
              "enum",
              "group",
              "integer",
              "message",
              "model",
              "number",
              "object",
              "preset",
              "string",
              "tools"
            ]
          },
          "ui": {
            "type": "string",
            "description": "UI visibility: hidden or config",
            "enum": [
              "hidden",
              "config"
            ]
          }
        },
        "required": [
          "type"
        ]
      }
    },
    "name": {
      "type": "string",
      "description": "Name uniquely identifies this workflow. Used in refs like \"builtin://agent\"."
    },
    "nodes": {
      "type": "array",
      "description": "Workflow nodes",
      "items": {
        "type": "object",
        "description": "Workflow node (flattened schema with all possible fields)",
        "properties": {
          "actions": {
            "type": "array",
            "description": "Actions defines available response buttons. If omitted, default approve/reject actions are shown. (used by: approval)",
            "items": {
              "type": "object"
            }
          },
          "args": {
            "type": "object",
            "description": "Used by: loop",
            "additionalProperties": {}
          },
          "attachments": {
            "type": "string",
            "description": "AttachmentsExpr is a CEL expression for file attachments. (used by: save_message)"
          },
          "base_branch": {
            "type": "string",
            "description": "BaseBranch is the branch to branch from. Defaults to repo's default branch. (used by: create_worktree)"
          },
          "branch": {
            "type": "string",
            "description": "Branch is the branch name to create/checkout. Auto-generated if omitted. (used by: create_worktree)"
          },
          "cache_creation_tokens": {
            "type": "integer",
            "description": "Used by: save_message"
          },
          "cache_read_tokens": {
            "type": "integer",
            "description": "Used by: save_message"
          },
          "command": {
            "type": "string",
            "description": "Command is the shell command to execute. Required. Supports CEL expressions: \"{{inputs.command}}\" (used by: run)"
          },
          "condition": {
            "type": "string",
            "description": "Used by: compact"
          },
          "content": {
            "type": "string",
            "description": "ContentExpr is a CEL expression for the message content. (used by: save_message)"
          },
          "copy_files": {
            "type": "array",
            "description": "CopyFiles lists files to copy from the source repo (searches recursively). Useful for .env files that shouldn't be in git. (used by: create_worktree)",
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string",
            "description": "Description provides context for the approval decision. Supports CEL expressions. (used by: approval)"
          },
          "env": {
            "type": "object",
            "description": "Env sets environment variables for the command. (used by: run)",
            "additionalProperties": {
              "type": "string"
            }
          },
          "expected_response_tools": {
            "type": "array",
            "description": "ExpectedResponseTools filters which response tools to execute. If set, only tool calls matching these names are executed. Internal field: set by engine, not user-facing. (used by: execute_tools)",
            "items": {
              "type": "string"
            }
          },
          "force": {
            "type": "boolean",
            "description": "Force deletes existing worktree/branch if they exist. (used by: create_worktree)"
          },
          "id": {
            "type": "string",
            "description": "Unique node identifier"
          },
          "inline": {
            "type": "object",
            "description": "Used by: loop"
          },
          "input_tokens": {
            "type": "integer",
            "description": "Token tracking (set by engine) (used by: save_message)"
          },
          "level": {
            "type": "string",
            "description": "Level sets the notification severity: \"info\", \"warning\", \"error\", \"success\". (used by: emit_notification)"
          },
          "max_tokens": {
            "type": "integer",
            "description": "MaxTokens limits the response length. (used by: call_llm)"
          },
          "message": {
            "type": "string",
            "description": "Message is the notification body. Supports CEL expressions. (used by: emit_notification)"
          },
          "messages": {
            "type": "array",
            "description": "Messages injects messages for ad-hoc LLM calls without a thread. (used by: call_llm)",
            "items": {
              "type": "object"
            }
          },
          "mode": {
            "type": "string",
            "description": "Mode determines join behavior: - \"all\": Wait for all incoming branches to complete - \"any\": Continue when any one branch completes (cancels others) (used by: join)"
          },
          "model": {
            "type": "string",
            "description": "Model specifies which LLM to use. (used by: call_llm)"
          },
          "name": {
            "type": "string",
            "description": "Name identifies this worktree. Used in the path: ~/.reliant/worktrees/\u003crepo\u003e/\u003cname\u003e (used by: create_worktree)"
          },
          "output_tokens": {
            "type": "integer",
            "description": "Used by: save_message"
          },
          "presets": {
            "type": "object",
            "description": "Used by: loop",
            "additionalProperties": {
              "type": "string"
            }
          },
          "project": {
            "type": "object",
            "description": "Used by: loop"
          },
          "ref": {
            "type": "string",
            "description": "Used by: loop"
          },
          "response_tool": {
            "type": "object",
            "description": "ResponseTool defines a custom structured output tool. Note: As of this writing, defining a response tool does not automatically include it, you must include the name in your tool_filter. (used by: call_llm)"
          },
          "role": {
            "type": "string",
            "description": "RoleExpr is a CEL expression for the message role. Values: \"user\", \"assistant\", \"system\" (used by: save_message)"
          },
          "save_message": {
            "type": "object",
            "description": "Used by: compact"
          },
          "sub_agents": {
            "type": "array",
            "description": "SubAgents lists presets available for the spawn tool. (used by: call_llm)",
            "items": {
              "type": "string"
            }
          },
          "system_prompt": {
            "type": "string",
            "description": "SystemPrompt sets the system message for this call. (used by: call_llm)"
          },
          "temperature": {
            "type": "number",
            "description": "Temperature controls response randomness (0.0-1.0). (used by: call_llm)"
          },
          "thinking": {
            "type": "object",
            "description": "Used by: save_message"
          },
          "thinking_level": {
            "type": "string",
            "description": "ThinkingLevel enables extended thinking for complex reasoning. (used by: call_llm)"
          },
          "thread": {
            "type": "object",
            "description": "Used by: compact"
          },
          "timeout": {
            "type": "string",
            "description": "Used by: compact"
          },
          "title": {
            "type": "string",
            "description": "Title is the approval dialog title. (used by: approval)"
          },
          "tool_calls": {
            "type": "string",
            "description": "ToolCallsExpr is a CEL expression for tool calls. (used by: save_message)"
          },
          "tool_filter": {
            "type": "array",
            "description": "ToolFilter specifies which tools are available. (used by: call_llm)",
            "items": {
              "type": "string"
            }
          },
          "tool_results": {
            "type": "string",
            "description": "ToolResultsExpr is a CEL expression for tool results. (used by: save_message)"
          },
          "tools": {
            "type": "boolean",
            "description": "Tools enables/disables tool use for this call. (used by: call_llm)"
          },
          "triggering_message": {
            "type": "string",
            "description": "TriggeringMessage identifies which message triggered the compaction. Used for context in the compaction summary. (used by: compact)"
          },
          "type": {
            "type": "string",
            "description": "Node type. Valid types: approval, call_llm, compact, create_worktree, emit_notification, execute_tools, join, loop, run, save_message, workflow",
            "enum": [
              "approval",
              "call_llm",
              "compact",
              "create_worktree",
              "emit_notification",
              "execute_tools",
              "join",
              "loop",
              "run",
              "save_message",
              "workflow"
            ]
          },
          "while": {
            "type": "string",
            "description": "While is a CEL condition evaluated after each iteration. Loop continues while true. Required. (used by: loop)"
          },
          "work_dir": {
            "type": "string",
            "description": "WorkDir sets the working directory. Defaults to project root. (used by: run)"
          }
        },
        "required": [
          "id",
          "type"
        ]
      }
    },
    "outputs": {
      "type": "object",
      "description": "Output CEL expressions",
      "additionalProperties": {
        "type": "string"
      }
    },
    "tag": {
      "type": "string",
      "description": "Tag enables preset matching. Workflows with tag: \"agent\" can use agent presets."
    },
    "ui": {
      "type": "object",
      "description": "UI stores visual editor metadata (node positions, etc.). Ignored by engine."
    }
  },
  "required": [
    "name",
    "entry",
    "nodes"
  ]
}`
