// Code generated by tools/docgen/v3schema. DO NOT EDIT.
// Source of truth: v3.AllNodeTypes() registry
// AST parsing used only for docstrings

package reference

// NodeTypeInfo contains documentation for a node type.
type NodeTypeInfo struct {
	Name         string          // Go type name
	TypeName     string          // YAML type value
	Summary      string          // Brief description
	Description  string          // Full description
	OutputFields []string        // Available output fields
	Example      string          // YAML example
	Fields       []NodeFieldInfo // Struct fields
}

// NodeFieldInfo contains documentation for a node field.
type NodeFieldInfo struct {
	Name        string // YAML field name
	Type        string // Field type
	Required    bool   // Is field required
	Description string // Field description
}

// NodeTypes is the registry of all node type documentation.
var NodeTypes = map[string]NodeTypeInfo{
	"approval": {
		Name:         "ApprovalNode",
		TypeName:     "approval",
		Summary:      "ApprovalArgs contains the configuration fields for an approval node.",
		Description:  "ApprovalArgs contains the configuration fields for an approval node.\nApprovalNode pauses workflow execution and waits for user approval.\nPresents a dialog with configurable actions (approve, reject, custom).\n\nOutput fields accessible via nodes.<id>.*:\n  - approved: Boolean indicating user approved\n  - action: The action type selected by user\n  - feedback: Optional user feedback text\n\nExample:\n\n  - id: confirm-deploy\n    type: approval\n    title: \"Confirm Deployment\"\n    description: \"Ready to deploy to production?\"\n    actions:\n  - type: approve\n    label: \"Deploy\"\n  - type: reject\n    label: \"Cancel\"",
		OutputFields: []string{"approved", "action", "feedback"},
		Example:      "- id: confirm-deploy\n    type: approval\n    title: \"Confirm Deployment\"\n    description: \"Ready to deploy to production?\"\n    actions:\n  - type: approve\n    label: \"Deploy\"\n  - type: reject\n    label: \"Cancel\"",
		Fields: []NodeFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "ID is the unique identifier for this node within the workflow.\nMust be unique across all nodes. Used in edges and CEL expressions (nodes.<id>).\nConvention: use kebab-case (e.g., \"call-llm\", \"process-results\")."},
			{Name: "type", Type: "string", Required: true, Description: "Type is the node type (call_llm, execute_tools, workflow, loop, etc.).\nThis field is used during YAML parsing to determine which node struct to use.\nIt's included here so strict YAML parsing doesn't reject it as unknown."},
			{Name: "condition", Type: "string", Required: false, Description: "Condition is a direct CEL expression (no {{}} delimiters) that controls\nwhether this node executes. If omitted or evaluates to true, the node runs.\nExample: \"inputs.should_run\" or \"nodes.prev.success\"\nOn Join nodes, the only valid values are the literals \"all\" and \"any\"."},
			{Name: "thread", Type: "ThreadConfig", Required: false, Description: "Thread configures how this node relates to conversation threads.\nOptions: inherit (default), new, fork. See ThreadConfig for details."},
			{Name: "timeout", Type: "string", Required: false, Description: "Timeout overrides the default activity timeout for this node.\nFormat: Go duration string (e.g., \"5m\", \"1h30m\", \"30s\")."},
			{Name: "save_message", Type: "SaveMessageConfig", Required: false, Description: "SaveMessage automatically saves a message to the thread after this node completes.\nAllows CEL expressions with output.* namespace to access node output.\n\nThread behavior: For workflow nodes with thread.mode \"fork\" or \"new\", the\nsave_message saves to the PARENT workflow's thread, not the child's thread.\nThis allows capturing summaries from forked workflows back into the orchestrating thread."},
			{Name: "args", Type: "ApprovalArgs", Required: true, Description: ""},
		},
	},
	"call_llm": {
		Name:         "CallLLMNode",
		TypeName:     "call_llm",
		Summary:      "CallLLMArgs contains the configuration fields for a call_llm node.",
		Description:  "CallLLMArgs contains the configuration fields for a call_llm node.\nCallLLMNode calls a Large Language Model and returns the response.\nThis is the primary node type for AI interactions.\nIt is not a full agent loop, nor does it execute tools. You can add it inside of a loop (like builtin://agent), and pass tool requests to the ExecuteToolsNode to actually run tools.\n\nOutput fields accessible via nodes.<id>.*:\n  - message: The LLM's response message (content, role, etc.)\n  - tool_calls: Array of tool calls if the LLM requested tool execution\n  - stop_reason: Why the LLM stopped (\"end_turn\", \"tool_use\", \"max_tokens\")\n  - thinking: Extended thinking output (if thinking_level is set)\n  - token_count: Total token usage (prompt + response + context)\n\nExample:\n\n  - id: call-llm\n    type: call_llm\n    model:\n    tags: [flagship]\n    system_prompt: \"You are a helpful assistant.\"\n    tools: true",
		OutputFields: []string{"message", "tool_calls", "stop_reason", "thinking", "token_count"},
		Example:      "- id: call-llm\n    type: call_llm\n    model:\n    tags: [flagship]\n    system_prompt: \"You are a helpful assistant.\"\n    tools: true",
		Fields: []NodeFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "ID is the unique identifier for this node within the workflow.\nMust be unique across all nodes. Used in edges and CEL expressions (nodes.<id>).\nConvention: use kebab-case (e.g., \"call-llm\", \"process-results\")."},
			{Name: "type", Type: "string", Required: true, Description: "Type is the node type (call_llm, execute_tools, workflow, loop, etc.).\nThis field is used during YAML parsing to determine which node struct to use.\nIt's included here so strict YAML parsing doesn't reject it as unknown."},
			{Name: "condition", Type: "string", Required: false, Description: "Condition is a direct CEL expression (no {{}} delimiters) that controls\nwhether this node executes. If omitted or evaluates to true, the node runs.\nExample: \"inputs.should_run\" or \"nodes.prev.success\"\nOn Join nodes, the only valid values are the literals \"all\" and \"any\"."},
			{Name: "thread", Type: "ThreadConfig", Required: false, Description: "Thread configures how this node relates to conversation threads.\nOptions: inherit (default), new, fork. See ThreadConfig for details."},
			{Name: "timeout", Type: "string", Required: false, Description: "Timeout overrides the default activity timeout for this node.\nFormat: Go duration string (e.g., \"5m\", \"1h30m\", \"30s\")."},
			{Name: "save_message", Type: "SaveMessageConfig", Required: false, Description: "SaveMessage automatically saves a message to the thread after this node completes.\nAllows CEL expressions with output.* namespace to access node output.\n\nThread behavior: For workflow nodes with thread.mode \"fork\" or \"new\", the\nsave_message saves to the PARENT workflow's thread, not the child's thread.\nThis allows capturing summaries from forked workflows back into the orchestrating thread."},
			{Name: "args", Type: "CallLLMArgs", Required: true, Description: ""},
		},
	},
	"compact": {
		Name:         "CompactNode",
		TypeName:     "compact",
		Summary:      "CompactArgs contains the configuration fields for a compact node.",
		Description:  "CompactArgs contains the configuration fields for a compact node.\nCompactNode compacts the conversation context to reduce token usage.\nSummarizes older messages while preserving recent context and key information.\nUseful for long-running agent loops to prevent context overflow.\n\nOutput fields accessible via nodes.<id>.*:\n  - success: Boolean indicating compaction succeeded\n  - tokens_before: Token count before compaction\n  - tokens_after: Token count after compaction\n\nExample:\n\n  - id: compact\n    type: compact\n    condition: \"{{thread.token_count > 50000}}\"",
		OutputFields: []string{"success", "tokens_before", "tokens_after"},
		Example:      "- id: compact\n    type: compact\n    condition: \"{{thread.token_count > 50000}}\"",
		Fields: []NodeFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "ID is the unique identifier for this node within the workflow.\nMust be unique across all nodes. Used in edges and CEL expressions (nodes.<id>).\nConvention: use kebab-case (e.g., \"call-llm\", \"process-results\")."},
			{Name: "type", Type: "string", Required: true, Description: "Type is the node type (call_llm, execute_tools, workflow, loop, etc.).\nThis field is used during YAML parsing to determine which node struct to use.\nIt's included here so strict YAML parsing doesn't reject it as unknown."},
			{Name: "condition", Type: "string", Required: false, Description: "Condition is a direct CEL expression (no {{}} delimiters) that controls\nwhether this node executes. If omitted or evaluates to true, the node runs.\nExample: \"inputs.should_run\" or \"nodes.prev.success\"\nOn Join nodes, the only valid values are the literals \"all\" and \"any\"."},
			{Name: "thread", Type: "ThreadConfig", Required: false, Description: "Thread configures how this node relates to conversation threads.\nOptions: inherit (default), new, fork. See ThreadConfig for details."},
			{Name: "timeout", Type: "string", Required: false, Description: "Timeout overrides the default activity timeout for this node.\nFormat: Go duration string (e.g., \"5m\", \"1h30m\", \"30s\")."},
			{Name: "save_message", Type: "SaveMessageConfig", Required: false, Description: "SaveMessage automatically saves a message to the thread after this node completes.\nAllows CEL expressions with output.* namespace to access node output.\n\nThread behavior: For workflow nodes with thread.mode \"fork\" or \"new\", the\nsave_message saves to the PARENT workflow's thread, not the child's thread.\nThis allows capturing summaries from forked workflows back into the orchestrating thread."},
			{Name: "args", Type: "CompactArgs", Required: true, Description: ""},
		},
	},
	"create_worktree": {
		Name:         "CreateWorktreeNode",
		TypeName:     "create_worktree",
		Summary:      "CreateWorktreeArgs contains the configuration fields for a create_worktree node.",
		Description:  "CreateWorktreeArgs contains the configuration fields for a create_worktree node.\nCreateWorktreeNode creates a git worktree for isolated parallel development.\nWorktrees allow multiple agents to work on the same repo simultaneously\nwithout conflicts.\n\nOutput fields accessible via nodes.<id>.*:\n  - path: Filesystem path to the created worktree\n  - branch: The branch name used\n  - success: Boolean indicating creation succeeded\n\nExample:\n\n  - id: create-worktree\n    type: create_worktree\n    name: \"feature-auth\"\n    base_branch: main\n    copy_files: [\".env\", \".env.local\"]",
		OutputFields: []string{"path", "branch", "success"},
		Example:      "- id: create-worktree\n    type: create_worktree\n    name: \"feature-auth\"\n    base_branch: main\n    copy_files: [\".env\", \".env.local\"]",
		Fields: []NodeFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "ID is the unique identifier for this node within the workflow.\nMust be unique across all nodes. Used in edges and CEL expressions (nodes.<id>).\nConvention: use kebab-case (e.g., \"call-llm\", \"process-results\")."},
			{Name: "type", Type: "string", Required: true, Description: "Type is the node type (call_llm, execute_tools, workflow, loop, etc.).\nThis field is used during YAML parsing to determine which node struct to use.\nIt's included here so strict YAML parsing doesn't reject it as unknown."},
			{Name: "condition", Type: "string", Required: false, Description: "Condition is a direct CEL expression (no {{}} delimiters) that controls\nwhether this node executes. If omitted or evaluates to true, the node runs.\nExample: \"inputs.should_run\" or \"nodes.prev.success\"\nOn Join nodes, the only valid values are the literals \"all\" and \"any\"."},
			{Name: "thread", Type: "ThreadConfig", Required: false, Description: "Thread configures how this node relates to conversation threads.\nOptions: inherit (default), new, fork. See ThreadConfig for details."},
			{Name: "timeout", Type: "string", Required: false, Description: "Timeout overrides the default activity timeout for this node.\nFormat: Go duration string (e.g., \"5m\", \"1h30m\", \"30s\")."},
			{Name: "save_message", Type: "SaveMessageConfig", Required: false, Description: "SaveMessage automatically saves a message to the thread after this node completes.\nAllows CEL expressions with output.* namespace to access node output.\n\nThread behavior: For workflow nodes with thread.mode \"fork\" or \"new\", the\nsave_message saves to the PARENT workflow's thread, not the child's thread.\nThis allows capturing summaries from forked workflows back into the orchestrating thread."},
			{Name: "args", Type: "CreateWorktreeArgs", Required: true, Description: ""},
		},
	},
	"execute_tools": {
		Name:         "ExecuteToolsNode",
		TypeName:     "execute_tools",
		Summary:      "ExecuteToolsArgs contains the configuration fields for an execute_tools node.",
		Description:  "ExecuteToolsArgs contains the configuration fields for an execute_tools node.\nExecuteToolsNode executes tool calls requested by an LLM.\nTypically follows a call_llm node that returned tool_calls.\n\nOutput fields accessible via nodes.<id>.*:\n  - tool_results: Array of tool execution results\n  - success: Boolean indicating all tools succeeded\n\nExample:\n\n  - id: exec-tools\n    type: execute_tools\n    tool_calls: \"{{nodes.call-llm.tool_calls}}\"",
		OutputFields: []string{"tool_results", "success"},
		Example:      "- id: exec-tools\n    type: execute_tools\n    tool_calls: \"{{nodes.call-llm.tool_calls}}\"",
		Fields: []NodeFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "ID is the unique identifier for this node within the workflow.\nMust be unique across all nodes. Used in edges and CEL expressions (nodes.<id>).\nConvention: use kebab-case (e.g., \"call-llm\", \"process-results\")."},
			{Name: "type", Type: "string", Required: true, Description: "Type is the node type (call_llm, execute_tools, workflow, loop, etc.).\nThis field is used during YAML parsing to determine which node struct to use.\nIt's included here so strict YAML parsing doesn't reject it as unknown."},
			{Name: "condition", Type: "string", Required: false, Description: "Condition is a direct CEL expression (no {{}} delimiters) that controls\nwhether this node executes. If omitted or evaluates to true, the node runs.\nExample: \"inputs.should_run\" or \"nodes.prev.success\"\nOn Join nodes, the only valid values are the literals \"all\" and \"any\"."},
			{Name: "thread", Type: "ThreadConfig", Required: false, Description: "Thread configures how this node relates to conversation threads.\nOptions: inherit (default), new, fork. See ThreadConfig for details."},
			{Name: "timeout", Type: "string", Required: false, Description: "Timeout overrides the default activity timeout for this node.\nFormat: Go duration string (e.g., \"5m\", \"1h30m\", \"30s\")."},
			{Name: "save_message", Type: "SaveMessageConfig", Required: false, Description: "SaveMessage automatically saves a message to the thread after this node completes.\nAllows CEL expressions with output.* namespace to access node output.\n\nThread behavior: For workflow nodes with thread.mode \"fork\" or \"new\", the\nsave_message saves to the PARENT workflow's thread, not the child's thread.\nThis allows capturing summaries from forked workflows back into the orchestrating thread."},
			{Name: "args", Type: "ExecuteToolsArgs", Required: true, Description: ""},
		},
	},
	"join": {
		Name:         "JoinNode",
		TypeName:     "join",
		Summary:      "JoinNode synchronizes parallel workflow branches.",
		Description:  "JoinNode synchronizes parallel workflow branches.\nUse after fan-out patterns where multiple nodes run in parallel.\n\nOutput fields accessible via nodes.<id>.*:\n  - completed: Array of node IDs that completed\n  - results: Map of node ID to their outputs\n\nThe `condition` field (inherited from NodeBase) controls join satisfaction:\n\n  - \"\" (empty) or \"all\": Wait for ALL incoming branches to complete or skip.\n  - \"any\": Continue when ANY branch completes.\n\nSkipped branches are treated as completed for join satisfaction purposes.\n\nExample:\n\n\t# Wait for all parallel branches (default behavior)\n\t- id: wait-all\n\t  type: join\n\n\t# Continue when any branch completes\n\t- id: wait-any\n\t  type: join\n\t  condition: any",
		OutputFields: []string{"completed", "results"},
		Example:      "# Wait for all parallel branches (default behavior)\n\t- id: wait-all\n\t  type: join\n\n\t# Continue when any branch completes\n\t- id: wait-any\n\t  type: join\n\t  condition: any",
		Fields: []NodeFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "ID is the unique identifier for this node within the workflow.\nMust be unique across all nodes. Used in edges and CEL expressions (nodes.<id>).\nConvention: use kebab-case (e.g., \"call-llm\", \"process-results\")."},
			{Name: "type", Type: "string", Required: true, Description: "Type is the node type (call_llm, execute_tools, workflow, loop, etc.).\nThis field is used during YAML parsing to determine which node struct to use.\nIt's included here so strict YAML parsing doesn't reject it as unknown."},
			{Name: "condition", Type: "string", Required: false, Description: "Condition is a direct CEL expression (no {{}} delimiters) that controls\nwhether this node executes. If omitted or evaluates to true, the node runs.\nExample: \"inputs.should_run\" or \"nodes.prev.success\"\nOn Join nodes, the only valid values are the literals \"all\" and \"any\"."},
			{Name: "thread", Type: "ThreadConfig", Required: false, Description: "Thread configures how this node relates to conversation threads.\nOptions: inherit (default), new, fork. See ThreadConfig for details."},
			{Name: "timeout", Type: "string", Required: false, Description: "Timeout overrides the default activity timeout for this node.\nFormat: Go duration string (e.g., \"5m\", \"1h30m\", \"30s\")."},
			{Name: "save_message", Type: "SaveMessageConfig", Required: false, Description: "SaveMessage automatically saves a message to the thread after this node completes.\nAllows CEL expressions with output.* namespace to access node output.\n\nThread behavior: For workflow nodes with thread.mode \"fork\" or \"new\", the\nsave_message saves to the PARENT workflow's thread, not the child's thread.\nThis allows capturing summaries from forked workflows back into the orchestrating thread."},
		},
	},
	"loop": {
		Name:         "LoopNode",
		TypeName:     "loop",
		Summary:      "LoopNode repeats a sub-workflow while a condition is true.",
		Description:  "LoopNode repeats a sub-workflow while a condition is true.\nEssential for agent loops, retry patterns, and iterative processing.\n\nThe while condition has access to:\n  - outputs.*: Sub-workflow output from the last iteration\n  - iter.iteration: Current iteration number (0-indexed)\n\nOutput fields accessible via nodes.<id>.*:\n  - User-defined outputs are flattened to top level (e.g., nodes.loop.exit_code)\n  - _iterations: Total number of iterations completed (system field)\n\nExample:\n\n  - id: agent-loop\n    type: loop\n    ref: builtin://agent\n    while: \"{{outputs.stop_reason != 'end_turn' && iter.iteration < 50}}\"\n    args:\n    model: claude-4-sonnet",
		OutputFields: []string{"_iterations"},
		Example:      "- id: agent-loop\n    type: loop\n    ref: builtin://agent\n    while: \"{{outputs.stop_reason != 'end_turn' && iter.iteration < 50}}\"\n    args:\n    model: claude-4-sonnet",
		Fields: []NodeFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "ID is the unique identifier for this node within the workflow.\nMust be unique across all nodes. Used in edges and CEL expressions (nodes.<id>).\nConvention: use kebab-case (e.g., \"call-llm\", \"process-results\")."},
			{Name: "type", Type: "string", Required: true, Description: "Type is the node type (call_llm, execute_tools, workflow, loop, etc.).\nThis field is used during YAML parsing to determine which node struct to use.\nIt's included here so strict YAML parsing doesn't reject it as unknown."},
			{Name: "condition", Type: "string", Required: false, Description: "Condition is a direct CEL expression (no {{}} delimiters) that controls\nwhether this node executes. If omitted or evaluates to true, the node runs.\nExample: \"inputs.should_run\" or \"nodes.prev.success\"\nOn Join nodes, the only valid values are the literals \"all\" and \"any\"."},
			{Name: "thread", Type: "ThreadConfig", Required: false, Description: "Thread configures how this node relates to conversation threads.\nOptions: inherit (default), new, fork. See ThreadConfig for details."},
			{Name: "timeout", Type: "string", Required: false, Description: "Timeout overrides the default activity timeout for this node.\nFormat: Go duration string (e.g., \"5m\", \"1h30m\", \"30s\")."},
			{Name: "save_message", Type: "SaveMessageConfig", Required: false, Description: "SaveMessage automatically saves a message to the thread after this node completes.\nAllows CEL expressions with output.* namespace to access node output.\n\nThread behavior: For workflow nodes with thread.mode \"fork\" or \"new\", the\nsave_message saves to the PARENT workflow's thread, not the child's thread.\nThis allows capturing summaries from forked workflows back into the orchestrating thread."},
			{Name: "ref", Type: "string", Required: false, Description: "Ref is a workflow reference string. Formats:\n- \"builtin://workflow_name\" - Built-in workflow\n- \"project://workflow_name\" - Project-local workflow\n- \"workflow_name\" - Resolved from project then builtins\nSupports CEL: \"{{inputs.workflow_ref}}\""},
			{Name: "inline", Type: "Workflow", Required: false, Description: "Inline defines the workflow inline rather than referencing an external one.\nUseful for small, self-contained sub-workflows."},
			{Name: "args", Type: "object", Required: false, Description: "Args passes input values to the sub-workflow.\nKeys must match the sub-workflow's declared inputs.\nValues can be literals or CEL expressions."},
			{Name: "presets", Type: "object", Required: false, Description: "Presets applies preset configurations to sub-workflow inputs.\nFormat: map[group_name]preset_name\nUse \"default\" for ungrouped inputs.\nPreset values form the base; args override them."},
			{Name: "project", Type: "ProjectConfig", Required: false, Description: "Project configures the working directory for this sub-workflow.\nWhen set, all tools, preset loading, and nested child workflows\noperate within this directory.\n\nExample:\n  project:\n    path: \"{{nodes.create_worktree.path}}\"\n\nDefault (nil): inherit project path from parent workflow."},
			{Name: "while", Type: "string", Required: false, Description: "While is a direct CEL expression (no {{}} delimiters) evaluated after\neach iteration. Loop continues while true. Required."},
			{Name: "yield", Type: "string", Required: false, Description: "Yield is a CEL expression. When true and while condition is false,\nyield to user for interaction before exiting the loop."},
		},
	},
	"run": {
		Name:         "RunNode",
		TypeName:     "run",
		Summary:      "RunNode executes a shell command.",
		Description:  "RunNode executes a shell command.\nUseful for running build commands, tests, or scripts as part of a workflow.\n\nOutput fields accessible via nodes.<id>.*:\n  - stdout: Command standard output\n  - stderr: Command standard error\n  - exit_code: Process exit code (0 = success)\n  - success: Boolean indicating exit_code == 0\n\nExample:\n\n  - id: run-tests\n    type: run\n    command: \"npm test\"\n    env:\n    NODE_ENV: test",
		OutputFields: []string{"stdout", "stderr", "exit_code", "success"},
		Example:      "- id: run-tests\n    type: run\n    command: \"npm test\"\n    env:\n    NODE_ENV: test",
		Fields: []NodeFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "ID is the unique identifier for this node within the workflow.\nMust be unique across all nodes. Used in edges and CEL expressions (nodes.<id>).\nConvention: use kebab-case (e.g., \"call-llm\", \"process-results\")."},
			{Name: "type", Type: "string", Required: true, Description: "Type is the node type (call_llm, execute_tools, workflow, loop, etc.).\nThis field is used during YAML parsing to determine which node struct to use.\nIt's included here so strict YAML parsing doesn't reject it as unknown."},
			{Name: "condition", Type: "string", Required: false, Description: "Condition is a direct CEL expression (no {{}} delimiters) that controls\nwhether this node executes. If omitted or evaluates to true, the node runs.\nExample: \"inputs.should_run\" or \"nodes.prev.success\"\nOn Join nodes, the only valid values are the literals \"all\" and \"any\"."},
			{Name: "thread", Type: "ThreadConfig", Required: false, Description: "Thread configures how this node relates to conversation threads.\nOptions: inherit (default), new, fork. See ThreadConfig for details."},
			{Name: "timeout", Type: "string", Required: false, Description: "Timeout overrides the default activity timeout for this node.\nFormat: Go duration string (e.g., \"5m\", \"1h30m\", \"30s\")."},
			{Name: "save_message", Type: "SaveMessageConfig", Required: false, Description: "SaveMessage automatically saves a message to the thread after this node completes.\nAllows CEL expressions with output.* namespace to access node output.\n\nThread behavior: For workflow nodes with thread.mode \"fork\" or \"new\", the\nsave_message saves to the PARENT workflow's thread, not the child's thread.\nThis allows capturing summaries from forked workflows back into the orchestrating thread."},
			{Name: "command", Type: "string", Required: false, Description: "Command is the shell command to execute. Required.\nSupports CEL expressions: \"{{inputs.command}}\""},
			{Name: "env", Type: "object", Required: false, Description: "Env sets environment variables for the command."},
			{Name: "work_dir", Type: "string", Required: false, Description: "WorkDir sets the working directory. Defaults to project root."},
		},
	},
	"save_message": {
		Name:         "SaveMessageNode",
		TypeName:     "save_message",
		Summary:      "SaveMessageArgs contains the configuration fields for a save_message node.",
		Description:  "SaveMessageArgs contains the configuration fields for a save_message node.\nSaveMessageNode saves a message to the conversation thread.\nUse this to persist LLM responses, tool results, or custom messages.\nAll fields support CEL expressions for dynamic content.\n\nOutput fields accessible via nodes.<id>.*:\n  - success: Boolean indicating save succeeded\n  - message_id: ID of the saved message\n\nExample:\n\n  - id: save-response\n    type: save_message\n    role: assistant\n    content: \"{{nodes.call-llm.message.content}}\"\n    tool_calls: \"{{nodes.call-llm.tool_calls}}\"",
		OutputFields: []string{"success", "message_id"},
		Example:      "- id: save-response\n    type: save_message\n    role: assistant\n    content: \"{{nodes.call-llm.message.content}}\"\n    tool_calls: \"{{nodes.call-llm.tool_calls}}\"",
		Fields: []NodeFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "ID is the unique identifier for this node within the workflow.\nMust be unique across all nodes. Used in edges and CEL expressions (nodes.<id>).\nConvention: use kebab-case (e.g., \"call-llm\", \"process-results\")."},
			{Name: "type", Type: "string", Required: true, Description: "Type is the node type (call_llm, execute_tools, workflow, loop, etc.).\nThis field is used during YAML parsing to determine which node struct to use.\nIt's included here so strict YAML parsing doesn't reject it as unknown."},
			{Name: "condition", Type: "string", Required: false, Description: "Condition is a direct CEL expression (no {{}} delimiters) that controls\nwhether this node executes. If omitted or evaluates to true, the node runs.\nExample: \"inputs.should_run\" or \"nodes.prev.success\"\nOn Join nodes, the only valid values are the literals \"all\" and \"any\"."},
			{Name: "thread", Type: "ThreadConfig", Required: false, Description: "Thread configures how this node relates to conversation threads.\nOptions: inherit (default), new, fork. See ThreadConfig for details."},
			{Name: "timeout", Type: "string", Required: false, Description: "Timeout overrides the default activity timeout for this node.\nFormat: Go duration string (e.g., \"5m\", \"1h30m\", \"30s\")."},
			{Name: "save_message", Type: "SaveMessageConfig", Required: false, Description: "SaveMessage automatically saves a message to the thread after this node completes.\nAllows CEL expressions with output.* namespace to access node output.\n\nThread behavior: For workflow nodes with thread.mode \"fork\" or \"new\", the\nsave_message saves to the PARENT workflow's thread, not the child's thread.\nThis allows capturing summaries from forked workflows back into the orchestrating thread."},
			{Name: "args", Type: "SaveMessageArgs", Required: true, Description: ""},
		},
	},
	"workflow": {
		Name:         "WorkflowNode",
		TypeName:     "workflow",
		Summary:      "WorkflowNode invokes a sub-workflow (ref or inline).",
		Description:  "WorkflowNode invokes a sub-workflow (ref or inline).\nUse for modular workflow composition and reuse.\n\nOutput fields accessible via nodes.<id>.*:\n  - outputs: The sub-workflow's output values\n  - success: Boolean indicating workflow completed successfully\n\nExamples:\n\n\t# Reference a builtin workflow\n\t- id: run-agent\n\t  type: workflow\n\t  ref: builtin://agent\n\t  presets:\n\t    default: researcher\n\t  args:\n\t    max_turns: 10\n\n\t# Inline workflow definition\n\t- id: custom-flow\n\t  type: workflow\n\t  inline:\n\t    name: inner\n\t    entry: [step1]\n\t    nodes:\n\t      - id: step1\n\t        type: call_llm",
		OutputFields: []string{"outputs", "success"},
		Example:      "",
		Fields: []NodeFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "ID is the unique identifier for this node within the workflow.\nMust be unique across all nodes. Used in edges and CEL expressions (nodes.<id>).\nConvention: use kebab-case (e.g., \"call-llm\", \"process-results\")."},
			{Name: "type", Type: "string", Required: true, Description: "Type is the node type (call_llm, execute_tools, workflow, loop, etc.).\nThis field is used during YAML parsing to determine which node struct to use.\nIt's included here so strict YAML parsing doesn't reject it as unknown."},
			{Name: "condition", Type: "string", Required: false, Description: "Condition is a direct CEL expression (no {{}} delimiters) that controls\nwhether this node executes. If omitted or evaluates to true, the node runs.\nExample: \"inputs.should_run\" or \"nodes.prev.success\"\nOn Join nodes, the only valid values are the literals \"all\" and \"any\"."},
			{Name: "thread", Type: "ThreadConfig", Required: false, Description: "Thread configures how this node relates to conversation threads.\nOptions: inherit (default), new, fork. See ThreadConfig for details."},
			{Name: "timeout", Type: "string", Required: false, Description: "Timeout overrides the default activity timeout for this node.\nFormat: Go duration string (e.g., \"5m\", \"1h30m\", \"30s\")."},
			{Name: "save_message", Type: "SaveMessageConfig", Required: false, Description: "SaveMessage automatically saves a message to the thread after this node completes.\nAllows CEL expressions with output.* namespace to access node output.\n\nThread behavior: For workflow nodes with thread.mode \"fork\" or \"new\", the\nsave_message saves to the PARENT workflow's thread, not the child's thread.\nThis allows capturing summaries from forked workflows back into the orchestrating thread."},
			{Name: "ref", Type: "string", Required: false, Description: "Ref is a workflow reference string. Formats:\n- \"builtin://workflow_name\" - Built-in workflow\n- \"project://workflow_name\" - Project-local workflow\n- \"workflow_name\" - Resolved from project then builtins\nSupports CEL: \"{{inputs.workflow_ref}}\""},
			{Name: "inline", Type: "Workflow", Required: false, Description: "Inline defines the workflow inline rather than referencing an external one.\nUseful for small, self-contained sub-workflows."},
			{Name: "args", Type: "object", Required: false, Description: "Args passes input values to the sub-workflow.\nKeys must match the sub-workflow's declared inputs.\nValues can be literals or CEL expressions."},
			{Name: "presets", Type: "object", Required: false, Description: "Presets applies preset configurations to sub-workflow inputs.\nFormat: map[group_name]preset_name\nUse \"default\" for ungrouped inputs.\nPreset values form the base; args override them."},
			{Name: "project", Type: "ProjectConfig", Required: false, Description: "Project configures the working directory for this sub-workflow.\nWhen set, all tools, preset loading, and nested child workflows\noperate within this directory.\n\nExample:\n  project:\n    path: \"{{nodes.create_worktree.path}}\"\n\nDefault (nil): inherit project path from parent workflow."},
		},
	},
}

// GetNodeType returns documentation for a specific node type.
func GetNodeType(typeName string) (NodeTypeInfo, bool) {
	info, ok := NodeTypes[typeName]
	return info, ok
}

// ListNodeTypes returns a list of all node type names.
func ListNodeTypes() []string {
	types := make([]string, 0, len(NodeTypes))
	for name := range NodeTypes {
		types = append(types, name)
	}
	return types
}
