// Code generated by tools/docgen/v3schema. DO NOT EDIT.
// Source of truth: v3 package struct definitions
// AST parsing used only for docstrings

package reference

// SharedTypeInfo contains documentation for a shared config or output type.
type SharedTypeInfo struct {
	Name        string            // Go type name
	Summary     string            // Brief description
	Description string            // Full description
	Example     string            // YAML example
	Fields      []SharedFieldInfo // Struct fields
}

// SharedFieldInfo contains documentation for a shared type field.
type SharedFieldInfo struct {
	Name        string // YAML/JSON field name
	Type        string // Field type
	Required    bool   // Is field required
	Description string // Field description
}

// SharedTypes is the registry of all shared type documentation.
// These include config types referenced by node fields and output types accessible via CEL.
var SharedTypes = map[string]SharedTypeInfo{
	"ApprovalAction": {
		Name:        "ApprovalAction",
		Summary:     "ApprovalAction defines an action button in an approval dialog.",
		Description: "ApprovalAction defines an action button in an approval dialog.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "type", Type: "string", Required: true, Description: "Type is the action identifier: \"approve\", \"reject\", or custom."},
			{Name: "label", Type: "string", Required: true, Description: "Label is the button text shown to the user."},
		},
	},
	"ApprovalOutput": {
		Name:        "ApprovalOutput",
		Summary:     "ApprovalOutput is the output from the approval activity.",
		Description: "ApprovalOutput is the output from the approval activity.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "approval_id", Type: "string", Required: true, Description: "ApprovalID is the unique identifier for this approval request."},
			{Name: "status", Type: "string", Required: true, Description: "Status is the approval result: \"approved\", \"denied\", or \"timeout\"."},
			{Name: "action_taken", Type: "string", Required: true, Description: "ActionTaken is the action button that was clicked."},
			{Name: "data", Type: "object", Required: true, Description: "Data contains additional metadata from the approval."},
		},
	},
	"CallLLMMessageInput": {
		Name:        "CallLLMMessageInput",
		Summary:     "CallLLMMessageInput represents a message to inject into the conversation.",
		Description: "CallLLMMessageInput represents a message to inject into the conversation.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "role", Type: "string", Required: true, Description: ""},
			{Name: "content", Type: "string", Required: false, Description: ""},
			{Name: "tool_result", Type: "ToolResult", Required: false, Description: ""},
			{Name: "tool_calls", Type: "ToolCall[]", Required: false, Description: ""},
		},
	},
	"CallLLMOutput": {
		Name:        "CallLLMOutput",
		Summary:     "CallLLMOutput is the output from call_llm nodes.",
		Description: "CallLLMOutput is the output from call_llm nodes.\nAccess fields via nodes.<id>.* in CEL expressions.\n\nCommon patterns:\n\n\tcondition: \"nodes.llm.stop_reason == 'tool_use'\"  // Check for tool calls\n\tcontent: \"{{nodes.llm.message.content}}\"          // Get response text\n\ttool_calls: \"{{nodes.llm.tool_calls}}\"            // Pass to execute_tools",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "message", Type: "MessageOutput", Required: true, Description: "Message contains the saved assistant message details."},
			{Name: "response_text", Type: "string", Required: true, Description: "ResponseText is the plain text content of the LLM response."},
			{Name: "tool_calls", Type: "ToolCall[]", Required: true, Description: "ToolCalls contains tool calls requested by the LLM."},
			{Name: "token_count", Type: "integer", Required: true, Description: "TokenCount is the total number of tokens used (prompt + response + context)."},
			{Name: "thinking", Type: "ThinkingOutput", Required: true, Description: "Thinking contains extended thinking content (if thinking_level was set)."},
			{Name: "compaction_threshold", Type: "integer", Required: true, Description: "CompactionThreshold is the effective token count at which compaction triggers for the resolved model."},
		},
	},
	"CompactOutput": {
		Name:        "CompactOutput",
		Summary:     "CompactOutput is the output from the compact activity.",
		Description: "CompactOutput is the output from the compact activity.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "message", Type: "MessageOutput", Required: true, Description: "Message contains the compaction summary message."},
		},
	},
	"CreateWorktreeOutput": {
		Name:        "CreateWorktreeOutput",
		Summary:     "CreateWorktreeOutput is the output from the create_worktree activity.",
		Description: "CreateWorktreeOutput is the output from the create_worktree activity.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "ID is the unique identifier for the worktree."},
			{Name: "name", Type: "string", Required: true, Description: "Name is the name of the worktree."},
			{Name: "path", Type: "string", Required: true, Description: "Path is the filesystem path to the worktree."},
			{Name: "branch", Type: "string", Required: true, Description: "Branch is the git branch name used by the worktree."},
			{Name: "base_branch", Type: "string", Required: true, Description: "BaseBranch is the branch this worktree was created from."},
			{Name: "repo_id", Type: "string", Required: true, Description: "RepoID is the identifier of the parent repository."},
			{Name: "status", Type: "string", Required: true, Description: "Status is the current status of the worktree."},
		},
	},
	"DeleteWorktreeOutput": {
		Name:        "DeleteWorktreeOutput",
		Summary:     "DeleteWorktreeOutput is the output from the delete_worktree activity.",
		Description: "DeleteWorktreeOutput is the output from the delete_worktree activity.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "deleted", Type: "boolean", Required: true, Description: "Deleted indicates whether the worktree was successfully deleted."},
		},
	},
	"Edge": {
		Name:        "Edge",
		Summary:     "Edge connects a source node to destination(s) with conditional routing. Although the UI would indicate that we have distinct Switch nodes, these are actually just modeled on edges.",
		Description: "Edge connects a source node to destination(s) with conditional routing. Although the UI would indicate that we have distinct Switch nodes, these are actually just modeled on edges.\nCases are evaluated in order; only the first matching case is taken. If no case matches, the Default is used.\nNOTE: If you want to implement parallel processing, you must create multiple, distinct edges from the same source node.\n\nExample - Sequential flow (default only, no branching):\n\n\tedges:\n\t  - from: step1\n\t    default: step2\n\nExample - Conditional routing with fallback:\n\n\tedges:\n\t  - from: llm\n\t    cases:\n\t      - condition: \"nodes.llm.stop_reason == 'tool_use'\"\n\t        to: execute-tools\n\nExample - Fan-out (parallel execution):\n\n\tedges:\n\t  - from: start\n\t    default: [branch-a, branch-b, branch-c]",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "from", Type: "string", Required: true, Description: "From is the source node ID that this edge originates from.\nExample: from: call-llm"},
			{Name: "cases", Type: "EdgeCase[]", Required: false, Description: "Cases lists conditional routing paths, evaluated in order until one matches.\nAll cases must have a condition. Use default for unconditional routing."},
			{Name: "default", Type: "string[]", Required: false, Description: "Default is the fallback destination when no case condition matches (or when no cases exist).\nUse for unconditional routing or as a fallback after conditional cases.\nExamples: default: next-node OR default: [branch-a, branch-b]"},
		},
	},
	"EdgeCase": {
		Name:        "EdgeCase",
		Summary:     "EdgeCase defines one conditional routing path from an edge.",
		Description: "EdgeCase defines one conditional routing path from an edge.\nEvery case must have a condition. For unconditional routing, use Edge.Default instead.\n\nExample:\n\n\tcases:\n\t  - condition: \"nodes.check.success\"\n\t    to: success-handler\n\t  - condition: \"nodes.check.retry_count < 3\"\n\t    to: retry\n\tdefault: failure-handler",
		Example:     "cases:\n\t  - condition: \"nodes.check.success\"\n\t    to: success-handler\n\t  - condition: \"nodes.check.retry_count < 3\"\n\t    to: retry\n\tdefault: failure-handler",
		Fields: []SharedFieldInfo{
			{Name: "condition", Type: "string", Required: true, Description: "Condition is a direct CEL expression (no {{}} delimiters) that must\nevaluate to true for this case to match. Required for all cases.\nExample: \"nodes.llm.stop_reason == 'tool_use'\""},
			{Name: "to", Type: "string[]", Required: true, Description: "To is the destination node ID or array for fan-out.\nExamples: to: next-node OR to: [branch-a, branch-b]"},
			{Name: "label", Type: "string", Required: false, Description: "Label is a human-readable name for this routing case (shown in UI)."},
		},
	},
	"ExecuteToolsOutput": {
		Name:        "ExecuteToolsOutput",
		Summary:     "ExecuteToolsOutput is the output from execute_tools nodes.",
		Description: "ExecuteToolsOutput is the output from execute_tools nodes.\nContains results from executing tool calls requested by an LLM.\n\nCommon patterns:\n\n\tresults: \"{{nodes.tools.tool_results}}\"  // Pass results to save_message\n\tcondition: \"size(nodes.tools.tool_results) > 0\"  // Check for results",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "message", Type: "MessageOutput", Required: true, Description: "Message contains the saved tool result message."},
			{Name: "tool_results", Type: "ToolResult[]", Required: true, Description: "ToolResults contains results from each executed tool."},
			{Name: "thread_token_count", Type: "integer", Required: true, Description: "ThreadTokenCount is the total token count in the thread after execution."},
			{Name: "total_result_chars", Type: "integer", Required: true, Description: "TotalResultChars is the total characters in all tool results."},
			{Name: "response_data", Type: "object", Required: true, Description: "ResponseData contains structured data from response tools."},
		},
	},
	"InjectConfig": {
		Name:        "InjectConfig",
		Summary:     "InjectConfig configures message injection into a thread.",
		Description: "InjectConfig configures message injection into a thread.\nUsed with thread.inject to add context to new/forked threads.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "role", Type: "string", Required: false, Description: "Role is the message role: \"user\" (default), \"system\", or \"assistant\"."},
			{Name: "content", Type: "string", Required: true, Description: "Content is the message text. Required.\nSupports CEL expressions: \"Review the code: {{inputs.code}}\""},
			{Name: "attachments", Type: "string", Required: false, Description: "Attachments is an optional list of attachment IDs.\nSupports CEL: \"{{inputs.attachments}}\" or \"{{trigger.attachments}}\""},
		},
	},
	"JoinOutput": {
		Name:        "JoinOutput",
		Summary:     "JoinOutput is the output from a join node.",
		Description: "JoinOutput is the output from a join node.\nSystem fields use _ prefix.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "_sources", Type: "object[]", Required: true, Description: "Output from each source branch"},
		},
	},
	"LoopOutput": {
		Name:        "LoopOutput",
		Summary:     "LoopOutput is the output from loop nodes.",
		Description: "LoopOutput is the output from loop nodes.\nUser-defined outputs are flattened to top level for consistent CEL access.\nSystem fields use _ prefix (e.g., _iterations) and cannot be overridden.\n\nCommon patterns:\n\n\twhile: \"outputs.exit_code != 0 && iter.iteration < 10\"\n\tcondition: \"nodes.loop._iterations > 1\"\n\tcondition: \"nodes.loop.exit_code == 0\"",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "_iterations", Type: "integer", Required: true, Description: "Total iterations completed"},
		},
	},
	"MessageOutput": {
		Name:        "MessageOutput",
		Summary:     "MessageOutput is the standardized output for activities that produce messages.",
		Description: "MessageOutput is the standardized output for activities that produce messages.\nAccess via: nodes.<id>.message.*",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "id", Type: "string", Required: true, Description: "Unique message ID"},
			{Name: "role", Type: "string", Required: true, Description: "\"user\", \"assistant\", or \"system\""},
			{Name: "text", Type: "string", Required: true, Description: "Message content"},
		},
	},
	"ModelSelector": {
		Name:        "ModelSelector",
		Summary:     "ModelSelector is used for model input defaults in workflow definitions.",
		Description: "ModelSelector is used for model input defaults in workflow definitions.\nIt supports two selection modes: direct ID or tag-based selection.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "id", Type: "string", Required: false, Description: "ID specifies an exact model identifier for direct selection."},
			{Name: "tags", Type: "string[]", Required: false, Description: "Tags specifies tag-based model resolution."},
			{Name: "providers", Type: "string[]", Required: false, Description: "Providers specifies an ordered list of preferred providers.\nEmpty = system default, single = hard constraint, multiple = ordered fallback."},
		},
	},
	"ProjectConfig": {
		Name:        "ProjectConfig",
		Summary:     "ProjectConfig configures the working directory for a sub-workflow.",
		Description: "ProjectConfig configures the working directory for a sub-workflow.\nWhen set on a workflow or loop node, all child execution (tools, presets,\nnested workflows, spawn) uses this path as the working directory.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "path", Type: "string", Required: false, Description: "Path is the project directory path.\nSupports CEL expressions like \"{{nodes.create_worktree.path}}\".\nWhen set, all tools, preset loading, and child workflows use this directory.\nEmpty/nil means \"inherit from parent workflow\"."},
		},
	},
	"ResponseTool": {
		Name:        "ResponseTool",
		Summary:     "ResponseTool defines a custom tool for structured LLM output.",
		Description: "ResponseTool defines a custom tool for structured LLM output.\nWhen configured, the LLM must respond by calling this tool,\nensuring responses match your schema. It can be used to get decisions for edge routing, or inject\nadditional messages into the thread.\n\nExample:\n\n\tresponse_tool:\n\t  name: analyze_result\n\t  description: Return structured analysis\n\t  schema:\n\t    type: object\n\t    properties:\n\t      summary: { type: string }\n\t      confidence: { type: number }",
		Example:     "response_tool:\n\t  name: analyze_result\n\t  description: Return structured analysis\n\t  schema:\n\t    type: object\n\t    properties:\n\t      summary: { type: string }\n\t      confidence: { type: number }",
		Fields: []SharedFieldInfo{
			{Name: "name", Type: "string", Required: true, Description: "Name is the tool name the LLM will call."},
			{Name: "description", Type: "string", Required: false, Description: "Description explains what the tool does (shown to LLM)."},
			{Name: "schema", Type: "object", Required: false, Description: "Schema is a JSON Schema defining the expected response structure."},
		},
	},
	"RunOutput": {
		Name:        "RunOutput",
		Summary:     "RunOutput is the output from run nodes (shell command execution).",
		Description: "RunOutput is the output from run nodes (shell command execution).\n\nCommon patterns:\n\n\tcondition: \"nodes.run.exit_code == 0\"   // Check success\n\tdata: \"{{parseJson(nodes.run.stdout)}}\" // Parse JSON output\n\tcondition: \"nodes.run.stderr == ''\"     // Check for errors",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "exit_code", Type: "integer", Required: true, Description: "Process exit code (0 = success)"},
			{Name: "stdout", Type: "string", Required: true, Description: "Standard output"},
			{Name: "stderr", Type: "string", Required: true, Description: "Standard error"},
		},
	},
	"SaveMessageConfig": {
		Name:        "SaveMessageConfig",
		Summary:     "SaveMessageConfig configures automatic message saving after a node executes.",
		Description: "SaveMessageConfig configures automatic message saving after a node executes.\nAll fields support CEL expressions with access to output.* namespace.\nThis is a convenience for saving LLM responses without a separate save_message node.\n\nThread behavior: For workflow nodes with thread.mode \"fork\" or \"new\", the\nsave_message saves to the PARENT workflow's thread, not the child's thread.\nThis allows capturing summaries from forked workflows back into the orchestrating thread.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "condition", Type: "string", Required: false, Description: "Condition is a CEL expression that must evaluate to true for the message to be saved.\nIf not specified, the message is always saved (assuming role is set).\nSupports output.*, workflow.*, and nodes.* namespaces.\nExample: \"{{output.succeeded}}\" or \"{{output.exit_code == 0}}\""},
			{Name: "role", Type: "string", Required: false, Description: "Role is the message role: \"user\", \"assistant\", or \"system\".\nSupports CEL: \"{{output.role}}\" or static: \"assistant\""},
			{Name: "content", Type: "string", Required: false, Description: "Content is the message text content.\nSupports CEL: \"{{output.message.content}}\" or \"{{output.text}}\""},
			{Name: "tool_calls", Type: "string", Required: false, Description: "ToolCalls saves tool calls from LLM response.\nTypically: \"{{output.tool_calls}}\""},
			{Name: "tool_results", Type: "string", Required: false, Description: "ToolResults saves tool execution results.\nTypically: \"{{output.tool_results}}\""},
			{Name: "attachments", Type: "string", Required: false, Description: "Attachments saves file attachments.\nTypically: \"{{output.attachments}}\" or \"{{inputs.attachments}}\""},
			{Name: "display_style", Type: "string", Required: false, Description: "DisplayStyle sets the UI display style hint for the message.\nValues: \"info\", \"warning\", \"success\", \"hidden\"\nhidden=not shown in UI but sent to LLM"},
		},
	},
	"SaveMessageOutput": {
		Name:        "SaveMessageOutput",
		Summary:     "SaveMessageOutput is the output from the save_message activity.",
		Description: "SaveMessageOutput is the output from the save_message activity.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "message", Type: "MessageOutput", Required: true, Description: "Message contains the saved message details."},
			{Name: "message_id", Type: "string", Required: true, Description: "MessageID is the unique identifier of the saved message."},
			{Name: "thread", Type: "string", Required: true, Description: "Thread is the thread path where the message was saved."},
			{Name: "tool_calls", Type: "ToolCall[]", Required: false, Description: "ToolCalls contains tool calls included in the message."},
			{Name: "tool_results", Type: "ToolResult[]", Required: false, Description: "ToolResults contains tool results included in the message."},
			{Name: "thread_token_count", Type: "integer", Required: true, Description: "ThreadTokenCount is the total token count in the thread."},
			{Name: "message_count", Type: "integer", Required: true, Description: "MessageCount is the total number of messages in the thread."},
		},
	},
	"SkippedOutput": {
		Name:        "SkippedOutput",
		Summary:     "SkippedOutput is the output for nodes that were skipped due to conditions.",
		Description: "SkippedOutput is the output for nodes that were skipped due to conditions.\nUsed when a node's condition evaluates to false.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "skipped", Type: "boolean", Required: true, Description: "Always true for skipped nodes"},
		},
	},
	"SubWorkflow": {
		Name:        "SubWorkflow",
		Summary:     "SubWorkflow contains fields for invoking sub-workflows.",
		Description: "SubWorkflow contains fields for invoking sub-workflows.\nEmbedded in WorkflowNode and LoopNode. Must specify either ref or inline.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "ref", Type: "string", Required: false, Description: "Ref is a workflow reference string. Formats:\n- \"builtin://workflow_name\" - Built-in workflow\n- \"project://workflow_name\" - Project-local workflow\n- \"workflow_name\" - Resolved from project then builtins\nSupports CEL: \"{{inputs.workflow_ref}}\""},
			{Name: "inline", Type: "Workflow", Required: false, Description: "Inline defines the workflow inline rather than referencing an external one.\nUseful for small, self-contained sub-workflows."},
			{Name: "args", Type: "object", Required: false, Description: "Args passes input values to the sub-workflow.\nKeys must match the sub-workflow's declared inputs.\nValues can be literals or CEL expressions."},
			{Name: "presets", Type: "object", Required: false, Description: "Presets applies preset configurations to sub-workflow inputs.\nFormat: map[group_name]preset_name\nUse \"default\" for ungrouped inputs.\nPreset values form the base; args override them."},
			{Name: "project", Type: "ProjectConfig", Required: false, Description: "Project configures the working directory for this sub-workflow.\nWhen set, all tools, preset loading, and nested child workflows\noperate within this directory.\n\nExample:\n  project:\n    path: \"{{nodes.create_worktree.path}}\"\n\nDefault (nil): inherit project path from parent workflow."},
		},
	},
	"ThinkingOutput": {
		Name:        "ThinkingOutput",
		Summary:     "ThinkingOutput contains extended thinking content from the LLM.",
		Description: "ThinkingOutput contains extended thinking content from the LLM.\nOnly populated when thinking_level is set on call_llm nodes.\nAccess via: nodes.<id>.thinking.*",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "content", Type: "string", Required: true, Description: "Raw thinking text"},
			{Name: "signature", Type: "string", Required: true, Description: "Signature for multi-turn preservation"},
		},
	},
	"ThreadConfig": {
		Name:        "ThreadConfig",
		Summary:     "ThreadConfig configures thread behavior for a node.",
		Description: "ThreadConfig configures thread behavior for a node.\nThreads are conversation contexts that persist messages across nodes.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "mode", Type: "string", Required: false, Description: "Mode determines thread relationship to parent.\n- \"inherit\" (default): Use parent's thread\n- \"new\": Create a fresh empty thread\n- \"fork\": Copy parent's messages into a new thread"},
			{Name: "memo", Type: "boolean", Required: false, Description: "Memo controls thread reuse in loops. Only meaningful for new/fork modes.\n- false (default): Create fresh thread each iteration\n- true: Create thread once, reuse across iterations"},
			{Name: "inject", Type: "InjectConfig", Required: false, Description: "Inject adds a message to the thread before execution.\nFor inherit: Added on first execution only\nFor new: Becomes the first message in the new thread\nFor fork: Added after copied messages\nIn loops with memo:false (default): Added every iteration (fresh thread each time)\nIn loops with memo:true: Added first iteration only (same thread reused)"},
		},
	},
	"Workflow": {
		Name:        "Workflow",
		Summary:     "Example - Simple LLM workflow:",
		Description: "Example - Simple LLM workflow:\n\n\tname: simple-chat\n\tdescription: A simple chat workflow\n\n\tinputs:\n\t  message:\n\t    type: message\n\t    required: true\n\t  model:\n\t    type: model\n\t    tags: [flagship]\n\n\tentry: [call-llm]\n\n\tnodes:\n\t  - id: call-llm\n\t    type: call_llm\n\t    model: \"{{inputs.model}}\"\n\nExample - Agent loop with tools:\n\n\tname: agent-loop\n\tinputs:\n\t  model: { type: model, tags: [flagship] }\n\t  max_turns: { type: integer, default: 10 }\n\n\tentry: [agent]\n\n\tnodes:\n\t  - id: agent\n\t    type: loop\n\t    while: \"outputs.stop_reason != 'end_turn' && iter.iteration < inputs.max_turns\"\n\t    inline:\n\t      name: turn\n\t      entry: [llm]\n\t      nodes:\n\t        - id: llm\n\t          type: call_llm\n\t          model: \"{{inputs.model}}\"\n\t          tools: true\n\t        - id: tools\n\t          type: execute_tools\n\t      edges:\n\t        - from: llm\n\t          cases:\n\t            - condition: \"nodes.llm.stop_reason == 'tool_use'\"\n\t              to: tools\n\t        - from: tools\n\t          default: llm\n\t      outputs:\n\t        stop_reason: \"{{nodes.llm.stop_reason}}\"",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "name", Type: "string", Required: true, Description: "Name uniquely identifies this workflow. Used in refs like \"builtin://agent\".\nExample: name: my-workflow"},
			{Name: "apiVersion", Type: "string", Required: false, Description: "APIVersion specifies the schema version. Optional, for future compatibility."},
			{Name: "description", Type: "string", Required: false, Description: "Description documents what this workflow does. Shown in list_workflows output.\nExample: description: An agent that helps with code review"},
			{Name: "presets", Type: "PresetsConfig", Required: false, Description: "Presets configures preset matching for this workflow's ungrouped inputs.\nPresets with matching tag can apply to top-level inputs.\nExample: presets: { tag: agent, default: my-preset }"},
			{Name: "inputs", Type: "object", Required: false, Description: "Inputs defines parameters passed when invoking this workflow.\nTypes: string, number, integer, boolean, enum, model, message, attachments, tools, array, object, any, group.\nExample: inputs: { model: { type: model, tags: [flagship] } }"},
			{Name: "outputs", Type: "object", Required: false, Description: "Outputs defines return values as CEL expressions (use {{}} interpolation).\nExample: outputs: { result: \"{{nodes.final.message.content}}\" }"},
			{Name: "entry", Type: "string[]", Required: false, Description: "Entry specifies starting node(s) as a list of node IDs.\nExample: entry: [start] OR entry: [node1, node2]"},
			{Name: "nodes", Type: "any[]", Required: false, Description: "Nodes lists all workflow steps. Use list_node_types for available types.\nExample: nodes: [{ id: llm, type: call_llm, model: \"{{inputs.model}}\" }]"},
			{Name: "edges", Type: "Edge[]", Required: false, Description: "Edges define execution flow between nodes. Each edge has conditional cases and/or a default destination.\nNodes with no outgoing edges are terminal. Conditions are direct CEL (no {{}})."},
			{Name: "ui", Type: "WorkflowUI", Required: false, Description: "UI stores visual editor metadata (node positions, etc.). Ignored by engine."},
		},
	},
	"WorkflowOutput": {
		Name:        "WorkflowOutput",
		Summary:     "WorkflowOutput is the output from a workflow node (non-loop sub-workflow).",
		Description: "WorkflowOutput is the output from a workflow node (non-loop sub-workflow).\nContains the outputs declared by the sub-workflow, flattened to top level.",
		Example:     "",
		Fields: []SharedFieldInfo{
			{Name: "outputs", Type: "object", Required: true, Description: "Sub-workflow declared outputs"},
		},
	},
}

// GetSharedType returns documentation for a specific shared type.
func GetSharedType(typeName string) (SharedTypeInfo, bool) {
	info, ok := SharedTypes[typeName]
	return info, ok
}

// ListSharedTypes returns a list of all shared type names.
func ListSharedTypes() []string {
	types := make([]string, 0, len(SharedTypes))
	for name := range SharedTypes {
		types = append(types, name)
	}
	return types
}
