// Code generated by tools/docgen/schema. DO NOT EDIT.
// Source: internal/workflow/v3/workflow.go

package reference

// WorkflowSchemaType describes a workflow schema type
type WorkflowSchemaType struct {
	Name        string
	Description string
	Fields      []WorkflowSchemaField
}

// WorkflowSchemaField describes a field in a schema type
type WorkflowSchemaField struct {
	Name        string
	JSONName    string
	Type        string
	Required    bool
	Description string
	ToolHint    string
}

// WorkflowSchema contains the workflow schema types
var WorkflowSchema = []WorkflowSchemaType{
	{
		Name:        "Workflow",
		Description: "Example - Simple LLM workflow:\\n\\n    name: simple-chat\\n    description: A simple chat workflow\\n\\n    inputs:\\n      message:\\n        type: message\\n        required: true\\n      model:\\n        type: model\\n        default: claude-4-sonnet\\n\\n    entry: call-llm\\n\\n    nodes:\\n      - id: call-llm\\n        type: call_llm\\n        model: \\\"{{inputs.model}}\\\"\\n\\nExample - Agent loop with tools:\\n\\n    name: agent-loop\\n    inputs:\\n      model: { type: model, default: claude-4-sonnet }\\n      max_turns: { type: integer, default: 10 }\\n\\n    entry: agent\\n\\n    nodes:\\n      - id: agent\\n        type: loop\\n        while: \\\"outputs.stop_reason != 'end_turn' && iter.iteration < inputs.max_turns\\\"\\n        inline:\\n          name: turn\\n          entry: llm\\n          nodes:\\n            - id: llm\\n              type: call_llm\\n              model: \\\"{{inputs.model}}\\\"\\n              tools: true\\n            - id: tools\\n              type: execute_tools\\n          edges:\\n            - from: llm\\n              cases:\\n                - condition: \\\"nodes.llm.stop_reason == 'tool_use'\\\"\\n                  to: tools\\n            - from: tools\\n              default: llm\\n          outputs:\\n            stop_reason: \\\"{{nodes.llm.stop_reason}}\\\"",
		Fields: []WorkflowSchemaField{
			{Name: "Name", JSONName: "name", Type: "string", Required: true, Description: "Name uniquely identifies this workflow. Used in refs like \\\"builtin://agent\\\".\\nExample: name: my-workflow", ToolHint: ""},
			{Name: "APIVersion", JSONName: "apiVersion", Type: "string", Required: false, Description: "APIVersion specifies the schema version. Optional, for future compatibility.", ToolHint: ""},
			{Name: "Description", JSONName: "description", Type: "string", Required: false, Description: "Description documents what this workflow does. Shown in list_workflows output.\\nExample: description: An agent that helps with code review", ToolHint: ""},
			{Name: "Tag", JSONName: "tag", Type: "string", Required: false, Description: "Tag enables preset matching. Workflows with tag: \\\"agent\\\" can use agent presets.\\nExample: tag: agent", ToolHint: ""},
			{Name: "Inputs", JSONName: "inputs", Type: "map[string]Input", Required: false, Description: "Inputs defines parameters passed when invoking this workflow.\\nTypes: string, number, integer, boolean, enum, model, message, attachments, tools, array, object, any, group.\\nExample: inputs: { model: { type: model, default: claude-4-sonnet } }", ToolHint: "Use list_input_types and get_input_type tools for input type details."},
			{Name: "Outputs", JSONName: "outputs", Type: "map[string]string", Required: false, Description: "Outputs defines return values as CEL expressions (use {{}} interpolation).\\nExample: outputs: { result: \\\"{{nodes.final.message.content}}\\\" }", ToolHint: "CEL expressions mapping output names to values. Use get_cel_reference for CEL syntax."},
			{Name: "Entry", JSONName: "entry", Type: "string | string[]", Required: true, Description: "Entry specifies starting node(s). Single ID or array for parallel start.\\nExamples: entry: start OR entry: [node1, node2]", ToolHint: ""},
			{Name: "Nodes", JSONName: "nodes", Type: "Node[]", Required: true, Description: "Nodes lists all workflow steps. Use list_node_types for available types.\\nExample: nodes: [{ id: llm, type: call_llm, model: \\\"{{inputs.model}}\\\" }]", ToolHint: "Use list_node_types and get_node_type tools for node type details."},
			{Name: "Edges", JSONName: "edges", Type: "Edge[]", Required: true, Description: "Edges define execution flow between nodes. Each edge has conditional cases and/or a default destination.\\nNodes with no outgoing edges are terminal. Conditions are direct CEL (no {{}}).", ToolHint: "See Edge type below."},
			{Name: "UI", JSONName: "ui", Type: "WorkflowUI", Required: false, Description: "UI stores visual editor metadata (node positions, etc.). Ignored by engine.", ToolHint: ""},
		},
	},
	{
		Name:        "Edge",
		Description: "Edge connects a source node to destination(s) with conditional routing. Although the UI would indicate that we have distinct Switch nodes, these are actually just modeled on edges.\\nCases are evaluated in order; only the first matching case is taken. If no case matches, the Default is used.\\nNOTE: If you want to implement parallel processing, you must create multiple, distinct edges from the same source node.\\n\\nExample - Sequential flow (default only, no branching):\\n\\n    edges:\\n      - from: step1\\n        default: step2\\n\\nExample - Conditional routing with fallback:\\n\\n    edges:\\n      - from: llm\\n        cases:\\n          - condition: \\\"nodes.llm.stop_reason == 'tool_use'\\\"\\n            to: execute-tools\\n\\nExample - Fan-out (parallel execution):\\n\\n    edges:\\n      - from: start\\n        default: [branch-a, branch-b, branch-c]",
		Fields: []WorkflowSchemaField{
			{Name: "From", JSONName: "from", Type: "string", Required: true, Description: "From is the source node ID that this edge originates from.\\nExample: from: call-llm", ToolHint: ""},
			{Name: "Cases", JSONName: "cases", Type: "EdgeCase[]", Required: false, Description: "Cases lists conditional routing paths, evaluated in order until one matches.\\nAll cases must have a condition. Use default for unconditional routing.", ToolHint: ""},
			{Name: "Default", JSONName: "default", Type: "string | string[]", Required: false, Description: "Default is the fallback destination when no case condition matches (or when no cases exist).\\nUse for unconditional routing or as a fallback after conditional cases.\\nExamples: default: next-node OR default: [branch-a, branch-b]", ToolHint: ""},
		},
	},
	{
		Name:        "EdgeCase",
		Description: "EdgeCase defines one conditional routing path from an edge.\\nEvery case must have a condition. For unconditional routing, use Edge.Default instead.\\n\\nExample:\\n\\n    cases:\\n      - condition: \\\"nodes.check.success\\\"\\n        to: success-handler\\n      - condition: \\\"nodes.check.retry_count < 3\\\"\\n        to: retry\\n    default: failure-handler",
		Fields: []WorkflowSchemaField{
			{Name: "Condition", JSONName: "condition", Type: "string", Required: true, Description: "Condition is a direct CEL expression (no {{}} needed) that must evaluate to true for this case to match.\\nRequired for all cases. Example: condition: \\\"nodes.llm.stop_reason == 'tool_use'\\\"", ToolHint: ""},
			{Name: "To", JSONName: "to", Type: "string | string[]", Required: true, Description: "To is the destination node ID or array for fan-out.\\nExamples: to: next-node OR to: [branch-a, branch-b]", ToolHint: ""},
			{Name: "Label", JSONName: "label", Type: "string", Required: false, Description: "Label is a human-readable name for this routing case (shown in UI).", ToolHint: ""},
		},
	},
}

// GetWorkflowSchemaType returns info about a specific schema type
func GetWorkflowSchemaType(name string) (WorkflowSchemaType, bool) {
	for _, t := range WorkflowSchema {
		if t.Name == name {
			return t, true
		}
	}
	return WorkflowSchemaType{}, false
}
