// Copyright (c) 2025 Reliant Labs

package geminiwire

// SkipThoughtSignatureValidator is Google's documented stand-in for a
// thought signature the client does not have.
//
// Gemini 3.x validates the thought signature on the FIRST functionCall part of
// every step in the current turn, and 400s a request that replays one
// unsigned ("Function call is missing a thought_signature in functionCall
// parts"). History can legitimately hold unsigned calls: a call made by a
// different model before the user switched to Gemini mid-chat, or a row
// persisted before a signature was captured. Without a stand-in, one such row
// wedges the conversation on every later request.
//
// Google's thought-signature docs name two accepted dummies,
// "context_engineering_is_the_way_to_go" and this one, "for function call
// parts that were not generated by the API" (ai.google.dev FAQ), and caution
// that it "should be a last resort as it will negatively impact model
// performance" (Vertex AI docs). This is the value google-gemini/gemini-cli
// sends (SYNTHETIC_THOUGHT_SIGNATURE) against the same cloudcode v1internal
// backend Antigravity uses.
//
// It must reach the wire as this exact JSON string. A transport that types the
// field as bytes and base64-encodes it on marshal (the genai SDK's
// Part.ThoughtSignature) sends something else entirely, which the server
// rejects as an invalid signature rather than recognising as the bypass.
const SkipThoughtSignatureValidator = "skip_thought_signature_validator"

// StepNeedsSignatureStandIn reports whether one model step must have
// SkipThoughtSignatureValidator set on its FIRST functionCall part, given
// whether each of the step's functionCall parts already carries a real
// signature.
//
// True only when the step has at least one call and none of them is signed.
// A step with any real signature is left exactly as it is: Gemini signs only
// the first call of a parallel batch, so a real signature belongs in the part
// it arrived on, and the docs require it back "inside its original Part".
// Adding a dummy beside it, or moving it, would replay a step the model never
// produced.
//
// The input is a []bool rather than a part type because the drivers that
// share this rule do not share one: antigravity's wire part holds the
// signature as a string, the genai SDK's as []byte.
func StepNeedsSignatureStandIn(callSigned []bool) bool {
	if len(callSigned) == 0 {
		return false
	}
	for _, signed := range callSigned {
		if signed {
			return false
		}
	}
	return true
}
