name: Feature Request
description: Suggest an idea for this project.
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: "Pre-submit Checks"
      options:
        - label: "I have [searched existing issues](https://github.com/reliantlabs/reliant/issues?q=is%3Aissue) and there are no duplicates"
          required: true
        - label: "I have checked the [Reliant documentation](https://docs.reliantlabs.io/docs/) and my feature is not already supported"
          required: true
  - type: textarea
    id: "describe-solution"
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    id: "related-to-problem"
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm always frustrated when [...]"
    validations:
      required: false
  - type: textarea
    id: "additional-context"
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
  - type: dropdown
    id: "os"
    attributes:
      label: "Operating system (OS)"
      multiple: false
      options:
        - "Select an OS"
        - macOS
        - Linux
        - Windows
    validations:
      required: true
  - type: dropdown
    id: "importance"
    attributes:
      label: "How important is this feature to you?"
      multiple: false
      options:
        - "1 (Nice to have)"
        - "2"
        - "3"
        - "4"
        - "5 (Critical for my workflow)"
    validations:
      required: true
