package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	reliantv1 "github.com/reliant-labs/reliant/gen/reliant/v1"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type nodeBinding struct {
	NodeType       string
	OneofFieldName string
	IsStructural   bool
	ArgFieldKeys   []string
}

func main() {
	outPath := "bindings_generated.go"
	content, err := generate()
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(outPath, content, 0o644); err != nil {
		panic(err)
	}
}

func generate() ([]byte, error) {
	nodeDesc := (&reliantv1.Node{}).ProtoReflect().Descriptor()
	edgeDesc := (&reliantv1.Edge{}).ProtoReflect().Descriptor()
	edgeCaseDesc := (&reliantv1.EdgeCase{}).ProtoReflect().Descriptor()

	nodeFields := nodeDesc.Fields()
	edgeFields := edgeDesc.Fields()
	edgeCaseFields := edgeCaseDesc.Fields()

	argsOneof := nodeDesc.Oneofs().ByName("args")
	if argsOneof == nil {
		return nil, fmt.Errorf("node args oneof not found")
	}

	bindings := discoverNodeBindings(argsOneof)
	sort.Slice(bindings, func(i, j int) bool { return bindings[i].NodeType < bindings[j].NodeType })

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go run ./internal/workflow/yaml/cmd/yamlbindingsgen; DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString("package wfyaml\n")
	buf.WriteString("\n")
	buf.WriteString("import \"google.golang.org/protobuf/reflect/protoreflect\"\n")
	buf.WriteString("\n")
	buf.WriteString("type generatedNodeBinding struct {\n")
	buf.WriteString("\toneofFieldName protoreflect.Name\n")
	buf.WriteString("\tisStructural bool\n")
	buf.WriteString("\targFieldKeys map[string]struct{}\n")
	buf.WriteString("}\n")
	buf.WriteString("\n")

	fmt.Fprintf(&buf, "const yamlKeyID = %q\n", nodeFields.ByName("id").Name())
	fmt.Fprintf(&buf, "const yamlKeyType = %q\n", nodeFields.ByName("type").Name())
	fmt.Fprintf(&buf, "const yamlKeyCondition = %q\n", nodeFields.ByName("condition").Name())
	fmt.Fprintf(&buf, "const yamlKeyTimeout = %q\n", nodeFields.ByName("timeout").Name())
	fmt.Fprintf(&buf, "const yamlKeySaveMessage = %q\n", nodeFields.ByName("save_message").Name())
	fmt.Fprintf(&buf, "const yamlKeyDaemon = %q\n", nodeFields.ByName("daemon").Name())
	fmt.Fprintf(&buf, "const yamlKeyArgs = %q\n", argsOneof.Name())
	fmt.Fprintf(&buf, "const yamlKeyFrom = %q\n", edgeFields.ByName("from").Name())
	fmt.Fprintf(&buf, "const yamlKeyCases = %q\n", edgeFields.ByName("cases").Name())
	fmt.Fprintf(&buf, "const yamlKeyDefault = %q\n", edgeFields.ByName("default").Name())
	fmt.Fprintf(&buf, "const yamlKeyTo = %q\n", edgeCaseFields.ByName("to").Name())
	fmt.Fprintf(&buf, "const yamlKeyLabel = %q\n", edgeCaseFields.ByName("label").Name())
	buf.WriteString("\n")

	buf.WriteString("var generatedNodeBaseFieldKeys = map[string]struct{}{\n")
	baseKeys := []string{string(nodeFields.ByName("id").Name()), string(nodeFields.ByName("type").Name()), string(nodeFields.ByName("condition").Name()), string(nodeFields.ByName("timeout").Name()), string(nodeFields.ByName("save_message").Name()), string(nodeFields.ByName("daemon").Name())}
	sort.Strings(baseKeys)
	for _, key := range baseKeys {
		fmt.Fprintf(&buf, "\t%q: {},\n", key)
	}
	buf.WriteString("}\n")
	buf.WriteString("\n")

	buf.WriteString("var generatedEdgeFieldKeys = map[string]struct{}{\n")
	edgeKeys := []string{string(edgeFields.ByName("from").Name()), string(edgeFields.ByName("cases").Name()), string(edgeFields.ByName("default").Name())}
	sort.Strings(edgeKeys)
	for _, key := range edgeKeys {
		fmt.Fprintf(&buf, "\t%q: {},\n", key)
	}
	buf.WriteString("}\n")
	buf.WriteString("\n")

	buf.WriteString("var generatedEdgeCaseFieldKeys = map[string]struct{}{\n")
	edgeCaseKeys := []string{string(edgeCaseFields.ByName("to").Name()), string(edgeCaseFields.ByName("condition").Name()), string(edgeCaseFields.ByName("label").Name())}
	sort.Strings(edgeCaseKeys)
	for _, key := range edgeCaseKeys {
		fmt.Fprintf(&buf, "\t%q: {},\n", key)
	}
	buf.WriteString("}\n")
	buf.WriteString("\n")

	buf.WriteString("var generatedNodeBindingsByType = map[string]generatedNodeBinding{\n")
	for _, binding := range bindings {
		fmt.Fprintf(&buf, "\t%q: {\n", binding.NodeType)
		fmt.Fprintf(&buf, "\t\toneofFieldName: %q,\n", binding.OneofFieldName)
		fmt.Fprintf(&buf, "\t\tisStructural: %t,\n", binding.IsStructural)
		buf.WriteString("\t\targFieldKeys: map[string]struct{}{\n")
		sort.Strings(binding.ArgFieldKeys)
		for _, fieldKey := range binding.ArgFieldKeys {
			fmt.Fprintf(&buf, "\t\t\t%q: {},\n", fieldKey)
		}
		buf.WriteString("\t\t},\n")
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
	buf.WriteString("\n")

	buf.WriteString("func generatedNodeBindingForType(nodeType string) (generatedNodeBinding, bool) {\n")
	buf.WriteString("\tbinding, ok := generatedNodeBindingsByType[nodeType]\n")
	buf.WriteString("\treturn binding, ok\n")
	buf.WriteString("}\n")
	buf.WriteString("\n")

	buf.WriteString("func generatedHasNodeBaseFieldKey(key string) bool {\n")
	buf.WriteString("\t_, ok := generatedNodeBaseFieldKeys[key]\n")
	buf.WriteString("\treturn ok\n")
	buf.WriteString("}\n")
	buf.WriteString("\n")

	buf.WriteString("func generatedHasEdgeFieldKey(key string) bool {\n")
	buf.WriteString("\t_, ok := generatedEdgeFieldKeys[key]\n")
	buf.WriteString("\treturn ok\n")
	buf.WriteString("}\n")
	buf.WriteString("\n")

	buf.WriteString("func generatedHasEdgeCaseFieldKey(key string) bool {\n")
	buf.WriteString("\t_, ok := generatedEdgeCaseFieldKeys[key]\n")
	buf.WriteString("\treturn ok\n")
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, buf.String())
	}
	return formatted, nil
}

func discoverNodeBindings(argsOneof protoreflect.OneofDescriptor) []nodeBinding {
	result := make([]nodeBinding, 0, argsOneof.Fields().Len())
	fields := argsOneof.Fields()
	for i := 0; i < fields.Len(); i++ {
		oneofField := fields.Get(i)
		argsMessage := oneofField.Message()
		if argsMessage == nil {
			continue
		}
		messageOptions := argsMessage.Options()
		if messageOptions == nil {
			continue
		}
		ext := proto.GetExtension(messageOptions, reliantv1.E_NodeMeta)
		if ext == nil {
			continue
		}
		meta, ok := ext.(*reliantv1.NodeMeta)
		if !ok || meta == nil || strings.TrimSpace(meta.NodeType) == "" {
			continue
		}

		argKeys := make([]string, 0, argsMessage.Fields().Len())
		for fieldIdx := 0; fieldIdx < argsMessage.Fields().Len(); fieldIdx++ {
			argKeys = append(argKeys, string(argsMessage.Fields().Get(fieldIdx).Name()))
		}

		result = append(result, nodeBinding{
			NodeType:       meta.NodeType,
			OneofFieldName: string(oneofField.Name()),
			IsStructural:   meta.IsStructural,
			ArgFieldKeys:   argKeys,
		})
	}
	return result
}
