// Code generated by go run ./internal/llm/tools/cmd/toolconfiggen; DO NOT EDIT.

package toolcatalog

// generatedToolParams is the bindable surface of every registered tool,
// projected from each tool's reflected parameter schema.
var generatedToolParams = map[string]ToolParams{
	"add_dependency": {
		Bindable: map[string]struct{}{
			"from_task": {},
			"to_task":   {},
			"type":      {},
		},
		Unbindable: map[string]string{},
	},
	"add_task": {
		Bindable: map[string]struct{}{
			"description": {},
			"metadata":    {},
			"parent_id":   {},
			"position":    {},
			"title":       {},
		},
		Unbindable: map[string]string{},
	},
	"ask_user": {
		Bindable: map[string]struct{}{
			"questions": {},
		},
		Unbindable: map[string]string{},
	},
	"code_context": {
		Bindable: map[string]struct{}{
			"depth":          {},
			"file":           {},
			"include_source": {},
			"limit":          {},
			"repo":           {},
			"scope":          {},
			"symbol":         {},
			"want":           {},
		},
		Unbindable: map[string]string{},
	},
	"component_library": {
		Bindable: map[string]struct{}{
			"action":           {},
			"category":         {},
			"forge_integrated": {},
			"name":             {},
			"path":             {},
			"query":            {},
			"repo":             {},
			"tag":              {},
		},
		Unbindable: map[string]string{},
	},
	"create_plan": {
		Bindable: map[string]struct{}{
			"complexity":  {},
			"description": {},
			"tasks":       {},
			"title":       {},
		},
		Unbindable: map[string]string{},
	},
	"create_subtask": {
		Bindable: map[string]struct{}{
			"assignee":       {},
			"description":    {},
			"metadata":       {},
			"parent_task_id": {},
			"title":          {},
		},
		Unbindable: map[string]string{},
	},
	"create_workflow": {
		Bindable: map[string]struct{}{
			"content": {},
			"name":    {},
		},
		Unbindable: map[string]string{},
	},
	"delete_scenario": {
		Bindable: map[string]struct{}{
			"id":   {},
			"name": {},
		},
		Unbindable: map[string]string{},
	},
	"edit": {
		Bindable: map[string]struct{}{
			"new_string":  {},
			"old_string":  {},
			"replace_all": {},
			"repo":        {},
		},
		Unbindable: map[string]string{
			"file_path": "an edit is defined by the file it edits; fixing it makes the tool able to edit exactly one file",
		},
	},
	"edit_scenario": {
		Bindable: map[string]struct{}{
			"expected_version": {},
			"id":               {},
			"name":             {},
			"new_string":       {},
			"old_string":       {},
		},
		Unbindable: map[string]string{},
	},
	"edit_workflow": {
		Bindable: map[string]struct{}{
			"expected_version": {},
			"id":               {},
			"new_string":       {},
			"old_string":       {},
		},
		Unbindable: map[string]string{},
	},
	"fetch": {
		Bindable: map[string]struct{}{
			"format":   {},
			"max_size": {},
			"timeout":  {},
			"url":      {},
		},
		Unbindable: map[string]string{},
	},
	"find_replace": {
		Bindable: map[string]struct{}{
			"file_glob":    {},
			"find_pattern": {},
			"ignore_case":  {},
			"preview":      {},
			"replace_text": {},
			"repo":         {},
			"use_regex":    {},
		},
		Unbindable: map[string]string{},
	},
	"generate_image": {
		Bindable: map[string]struct{}{
			"background": {},
			"model":      {},
			"prompt":     {},
			"quality":    {},
			"repo":       {},
			"size":       {},
		},
		Unbindable: map[string]string{
			"save_to": "every generated image would overwrite the previous one at the same path",
		},
	},
	"get_cel_reference": {
		Bindable:   map[string]struct{}{},
		Unbindable: map[string]string{},
	},
	"get_plan": {
		Bindable:   map[string]struct{}{},
		Unbindable: map[string]string{},
	},
	"get_preset": {
		Bindable: map[string]struct{}{
			"name": {},
		},
		Unbindable: map[string]string{},
	},
	"get_schema": {
		Bindable: map[string]struct{}{
			"name": {},
		},
		Unbindable: map[string]string{},
	},
	"get_workflow": {
		Bindable: map[string]struct{}{
			"id": {},
		},
		Unbindable: map[string]string{},
	},
	"get_workflow_suggestions": {
		Bindable:   map[string]struct{}{},
		Unbindable: map[string]string{},
	},
	"list_presets": {
		Bindable:   map[string]struct{}{},
		Unbindable: map[string]string{},
	},
	"list_ready_tasks": {
		Bindable:   map[string]struct{}{},
		Unbindable: map[string]string{},
	},
	"list_scenarios": {
		Bindable: map[string]struct{}{
			"id": {},
		},
		Unbindable: map[string]string{},
	},
	"list_tasks": {
		Bindable:   map[string]struct{}{},
		Unbindable: map[string]string{},
	},
	"list_workflows": {
		Bindable:   map[string]struct{}{},
		Unbindable: map[string]string{},
	},
	"load_tool": {
		Bindable: map[string]struct{}{
			"name":  {},
			"query": {},
		},
		Unbindable: map[string]string{},
	},
	"metadata_writer": {
		Bindable: map[string]struct{}{
			"action":   {},
			"metadata": {},
		},
		Unbindable: map[string]string{},
	},
	"move_code": {
		Bindable: map[string]struct{}{
			"operation":    {},
			"repo":         {},
			"source_end":   {},
			"source_file":  {},
			"source_start": {},
			"target_file":  {},
			"target_line":  {},
		},
		Unbindable: map[string]string{},
	},
	"project_analyzer": {
		Bindable: map[string]struct{}{
			"action": {},
			"path":   {},
		},
		Unbindable: map[string]string{},
	},
	"read_attachment": {
		Bindable: map[string]struct{}{
			"attachment_id": {},
			"pages":         {},
		},
		Unbindable: map[string]string{},
	},
	"remove_dependency": {
		Bindable: map[string]struct{}{
			"from_task": {},
			"to_task":   {},
			"type":      {},
		},
		Unbindable: map[string]string{},
	},
	"run_scenario": {
		Bindable: map[string]struct{}{
			"id":   {},
			"name": {},
		},
		Unbindable: map[string]string{},
	},
	"save_attachment": {
		Bindable: map[string]struct{}{
			"repo": {},
		},
		Unbindable: map[string]string{
			"attachment_id": "names the one attachment to save, which is chosen per call and cannot be known in advance",
			"save_to":       "every save would target the same file, so each call destroys the last one's output",
		},
	},
	"shell": {
		Bindable: map[string]struct{}{
			"command":           {},
			"description":       {},
			"env":               {},
			"max_output":        {},
			"repo":              {},
			"run_in_background": {},
			"tail_lines":        {},
			"timeout":           {},
		},
		Unbindable: map[string]string{},
	},
	"shell_kill": {
		Bindable: map[string]struct{}{},
		Unbindable: map[string]string{
			"process_id": "identifies one live process, which is chosen per call and cannot be known in advance",
		},
	},
	"shell_list": {
		Bindable: map[string]struct{}{
			"all":        {},
			"chat_id":    {},
			"session_id": {},
		},
		Unbindable: map[string]string{},
	},
	"shell_output": {
		Bindable: map[string]struct{}{
			"limit":                  {},
			"offset":                 {},
			"regex":                  {},
			"regex_case_insensitive": {},
			"regex_context_after":    {},
			"regex_context_before":   {},
			"tail":                   {},
		},
		Unbindable: map[string]string{
			"process_id": "identifies one live process, which is chosen per call and cannot be known in advance",
		},
	},
	"shell_wait": {
		Bindable: map[string]struct{}{
			"tail_lines":      {},
			"timeout_seconds": {},
		},
		Unbindable: map[string]string{
			"process_id": "identifies one live process, which is chosen per call and cannot be known in advance",
		},
	},
	"skill": {
		Bindable: map[string]struct{}{
			"action":                 {},
			"limit":                  {},
			"offset":                 {},
			"path":                   {},
			"query":                  {},
			"regex":                  {},
			"regex_case_insensitive": {},
			"regex_context_after":    {},
			"regex_context_before":   {},
			"section":                {},
		},
		Unbindable: map[string]string{},
	},
	"sourcegraph": {
		Bindable: map[string]struct{}{
			"context_window": {},
			"count":          {},
			"query":          {},
			"timeout":        {},
		},
		Unbindable: map[string]string{},
	},
	"spawn_send": {
		Bindable: map[string]struct{}{
			"message": {},
		},
		Unbindable: map[string]string{
			"agent_id": "identifies one running sub-agent, which is chosen per call",
		},
	},
	"spawn_status": {
		Bindable: map[string]struct{}{
			"timeout_seconds": {},
			"wait":            {},
		},
		Unbindable: map[string]string{
			"agent_id": "identifies one running sub-agent, which is chosen per call",
		},
	},
	"update_plan": {
		Bindable: map[string]struct{}{
			"complexity":  {},
			"description": {},
			"status":      {},
			"title":       {},
		},
		Unbindable: map[string]string{},
	},
	"update_task": {
		Bindable: map[string]struct{}{
			"assignee":    {},
			"description": {},
			"metadata":    {},
			"status":      {},
			"task_id":     {},
			"title":       {},
		},
		Unbindable: map[string]string{},
	},
	"view": {
		Bindable: map[string]struct{}{
			"file_path": {},
			"limit":     {},
			"offset":    {},
			"pages":     {},
			"repo":      {},
		},
		Unbindable: map[string]string{},
	},
	"view_scenario": {
		Bindable: map[string]struct{}{
			"id":   {},
			"name": {},
		},
		Unbindable: map[string]string{},
	},
	"websearch": {
		Bindable: map[string]struct{}{
			"count": {},
			"query": {},
		},
		Unbindable: map[string]string{},
	},
	"worktree": {
		Bindable: map[string]struct{}{
			"action":      {},
			"base_branch": {},
			"branch":      {},
			"copy_files":  {},
			"force":       {},
			"name":        {},
			"session_id":  {},
		},
		Unbindable: map[string]string{},
	},
	"write": {
		Bindable: map[string]struct{}{
			"content": {},
			"repo":    {},
		},
		Unbindable: map[string]string{
			"file_path": "every write would target the same file, so each call destroys the last one's output",
		},
	},
	"write_scenario": {
		Bindable: map[string]struct{}{
			"content":          {},
			"expected_version": {},
			"id":               {},
			"name":             {},
		},
		Unbindable: map[string]string{},
	},
	"write_workflow": {
		Bindable: map[string]struct{}{
			"content":          {},
			"expected_version": {},
			"id":               {},
			"name":             {},
		},
		Unbindable: map[string]string{},
	},
}
