// Copyright (c) 2025 Reliant Labs
//
// Model reference generator - generates documentation from the model registry.
//
// SOURCE OF TRUTH:
//   - internal/llm/models/definitions/models.yaml (model definitions)
//   - internal/llm/models/registry_v2.go (registry API)
//
// GENERATED FILE:
//   - generated/docs-source/reference/models.md
//
// Usage: go run ./tools/docgen/models <output_file>
// Regenerate with: make generate-models

package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/reliant-labs/reliant/internal/llm/models"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: %s <output_file>\n", os.Args[0])
		os.Exit(1)
	}

	outputFile := os.Args[1]

	markdown := generateMarkdown()

	if err := os.WriteFile(outputFile, []byte(markdown), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing output: %v\n", err)
		os.Exit(1)
	}

	registry := models.MustGetRegistry()
	userVisible := registry.GetUserVisibleModels()
	fmt.Printf("Generated models reference: %s (%d models)\n", outputFile, len(userVisible))
}

func generateMarkdown() string {
	var sb strings.Builder

	sb.WriteString(`---
# =============================================================================
# GENERATED FILE - DO NOT EDIT DIRECTLY
#
# Source of truth: internal/llm/models/definitions/models.yaml
# Generated by: go run ./tools/docgen/models
# Regenerate with: make generate-models
# =============================================================================
title: "Models Reference"
description: "Available AI models and their capabilities"
weight: 25
---

Reliant supports models from multiple providers. Use the model ID in workflow configurations and presets.

> **Note:** Reliant has been most extensively tested with **Anthropic** and **OpenAI** models. You may encounter issues when using other providers.

## Model Tags

Models are tagged to help with selection. You can also [bring your own model](/docs/settings/model-config#custom-models) with your own provider.

| Tag | Description |
|-----|-------------|
| ` + "`flagship`" + ` | Most capable models, best quality |
| ` + "`moderate`" + ` | Balance of capability and cost |
| ` + "`fast`" + ` | Optimized for speed |
| ` + "`cheap`" + ` | Low cost per token |
| ` + "`reasoning`" + ` | Extended thinking capabilities |

## Capabilities Legend

| Symbol | Meaning |
|--------|---------|
| {{< icon "wrench-screwdriver" >}} | Supports tool use |
| {{< icon "paper-clip" >}} | Supports attachments (images, PDFs) |
| {{< icon "save" >}} | Supports prompt caching |
| {{< icon "lightning-bolt" >}} | Supports streaming |
| {{< icon "light-bulb" >}} | Extended reasoning/thinking |

---

`)

	// Get user-visible models from registry
	registry := models.MustGetRegistry()
	allUserVisible := registry.GetUserVisibleModels()

	// Filter to only public providers (anthropic, openai, gemini)
	var publicModels []*models.ModelDefinition
	for _, def := range allUserVisible {
		id := def.ID
		if strings.HasPrefix(id, "claude") ||
			strings.HasPrefix(id, "gpt") ||
			strings.HasPrefix(id, "gemini") {
			publicModels = append(publicModels, def)
		}
		// Skip non-public providers (xAI, Vertex AI, etc.)
	}

	// Group models by provider prefix
	providers := map[string][]*models.ModelDefinition{
		"claude": {},
		"gpt":    {},
		"gemini": {},
	}

	for _, def := range publicModels {
		id := def.ID
		switch {
		case strings.HasPrefix(id, "claude"):
			providers["claude"] = append(providers["claude"], def)
		case strings.HasPrefix(id, "gpt"):
			providers["gpt"] = append(providers["gpt"], def)
		case strings.HasPrefix(id, "gemini"):
			providers["gemini"] = append(providers["gemini"], def)
		}
	}

	// Sort each provider's models by ID
	for _, modelList := range providers {
		sort.Slice(modelList, func(i, j int) bool {
			return modelList[i].ID < modelList[j].ID
		})
	}

	// Generate sections (only public providers)
	providerOrder := []struct {
		key   string
		title string
		desc  string
	}{
		{"claude", "Anthropic (Claude)", "All Claude models support attachments (images, PDFs) and prompt caching."},
		{"gpt", "OpenAI (GPT)", "OpenAI's GPT models with varying context windows and capabilities."},
		{"gemini", "Google (Gemini)", "Google's Gemini models with large context windows."},
	}

	for _, p := range providerOrder {
		modelList := providers[p.key]
		if len(modelList) == 0 {
			continue
		}

		sb.WriteString(fmt.Sprintf("## %s\n\n", p.title))
		sb.WriteString("| Model ID | Name | Tags | Context | Capabilities | Providers |\n")
		sb.WriteString("|----------|------|------|---------|--------------|----------|\n")

		for _, def := range modelList {
			sb.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s | %s |\n",
				def.ID,
				def.Name,
				formatTags(def.Tags),
				formatContextWindow(def.Capabilities.MaxContextWindow),
				formatCapabilities(def.Capabilities),
				formatProviders(def.Providers),
			))
		}

		if p.desc != "" {
			sb.WriteString(fmt.Sprintf("\n**Note:** %s\n", p.desc))
		}
		sb.WriteString("\n---\n\n")
	}

	// Add "Models by Tag" section
	sb.WriteString(generateModelsByTag(publicModels))

	// Add usage section
	sb.WriteString(`## Using Models

### Tag-Based Selection (Recommended)

Select models by capability tags for provider-agnostic workflows:

` + "```yaml" + `
# In presets or workflow nodes
model:
  tags: [flagship]      # Best quality model available
  
model:
  tags: [fast, cheap]   # Prefer fast+cheap, falls back to fast-only or cheap-only

model:
  tags: [local, fast]   # Prefer local, use fast cloud model as fallback
` + "```" + `

### Explicit Model ID

Select a specific model by ID:

` + "```yaml" + `
model:
  id: claude-4.5-sonnet
` + "```" + `

### In Workflow Inputs

Workflow inputs use model ID strings (for UI dropdown):

` + "```yaml" + `
inputs:
  model:
    type: model
    default: claude-4.5-sonnet  # Model ID string for input default
` + "```" + `

### In Presets

Presets can use tag-based selection:

` + "```yaml" + `
name: my-preset
tag: agent
params:
  model:
    tags: [flagship]  # Works with any provider
` + "```" + `

---

## Provider Configuration

Models require the appropriate provider to be configured in Settings → AI:

| Provider | Models |
|----------|--------|
| Anthropic | ` + "`claude-*`" + ` |
| OpenAI | ` + "`gpt-*`" + ` |
| Google | ` + "`gemini-*`" + ` |

See [API Keys & Providers]({{< relref "../settings/api-keys" >}}) for setup instructions.
`)

	return sb.String()
}

func formatContextWindow(tokens int) string {
	if tokens >= 1000000 {
		return fmt.Sprintf("%dM", tokens/1000000)
	}
	return fmt.Sprintf("%dK", tokens/1000)
}

func formatTags(tags []string) string {
	// Filter out internal tags (meta) from display
	var visible []string
	for _, tag := range tags {
		if tag != models.TagMeta {
			visible = append(visible, tag)
		}
	}
	if len(visible) == 0 {
		return "-"
	}
	return strings.Join(visible, ", ")
}

func formatCapabilities(caps models.ModelCapabilities) string {
	var icons []string

	if caps.SupportsTools {
		icons = append(icons, "{{< icon \"wrench-screwdriver\" >}}")
	}
	if caps.SupportsAttachments {
		icons = append(icons, "{{< icon \"paper-clip\" >}}")
	}
	if caps.SupportsCaching {
		icons = append(icons, "{{< icon \"save\" >}}")
	}
	if caps.SupportsStreaming {
		icons = append(icons, "{{< icon \"lightning-bolt\" >}}")
	}
	if caps.CanReason {
		icons = append(icons, "{{< icon \"light-bulb\" >}}")
	}

	if len(icons) == 0 {
		return "-"
	}
	return strings.Join(icons, " ")
}

func formatProviders(providers []models.ProviderMapping) string {
	if len(providers) == 0 {
		return "-"
	}

	// Collect unique drivers
	drivers := make([]string, 0, len(providers))
	seen := make(map[string]bool)
	for _, p := range providers {
		if !seen[p.Driver] {
			seen[p.Driver] = true
			drivers = append(drivers, p.Driver)
		}
	}

	return strings.Join(drivers, ", ")
}

// generateModelsByTag creates the "Models by Tag" section showing reverse mapping.
func generateModelsByTag(userFacing []*models.ModelDefinition) string {
	var sb strings.Builder

	sb.WriteString(`## Models by Tag

Find models by capability. Use these tables to answer "what are my options for X?"

`)

	// Define tags to show with descriptions (order matters for presentation)
	tagInfo := []struct {
		tag  string
		name string
		desc string
	}{
		{models.TagFlagship, "Flagship", "Most capable models for complex tasks"},
		{models.TagModerate, "Moderate", "Balance of capability and cost"},
		{models.TagFast, "Fast", "Optimized for quick responses"},
		{models.TagCheap, "Cheap", "Low cost per token"},
		{models.TagReasoning, "Reasoning", "Extended thinking capabilities"},
	}

	for _, ti := range tagInfo {
		// Filter models that have this tag
		var tagged []*models.ModelDefinition
		for _, def := range userFacing {
			if hasTag(def.Tags, ti.tag) {
				tagged = append(tagged, def)
			}
		}

		if len(tagged) == 0 {
			continue
		}

		sb.WriteString(fmt.Sprintf("### %s\n\n", ti.name))
		sb.WriteString(fmt.Sprintf("_%s_\n\n", ti.desc))
		sb.WriteString("| Model | Provider | Context | Capabilities |\n")
		sb.WriteString("|-------|----------|---------|-------------|\n")

		for _, def := range tagged {
			sb.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n",
				def.ID,
				getProviderName(def.ID),
				formatContextWindow(def.Capabilities.MaxContextWindow),
				formatCapabilities(def.Capabilities),
			))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n\n")
	return sb.String()
}

// hasTag checks if a tag slice contains a specific tag.
func hasTag(tags []string, tag string) bool {
	for _, t := range tags {
		if t == tag {
			return true
		}
	}
	return false
}

// getProviderName returns a friendly provider name based on model ID prefix.
func getProviderName(id string) string {
	switch {
	case strings.HasPrefix(id, "vertex-claude"):
		return "Vertex (Claude)"
	case strings.HasPrefix(id, "vertex-gemini"):
		return "Vertex (Gemini)"
	case strings.HasPrefix(id, "claude"):
		return "Anthropic"
	case strings.HasPrefix(id, "gpt"):
		return "OpenAI"
	case strings.HasPrefix(id, "gemini"):
		return "Google"
	case strings.HasPrefix(id, "grok"):
		return "xAI"
	default:
		return "Other"
	}
}
