-- Code generated by scripts/generate-schema-sql.sh. DO NOT EDIT.
--
-- Source of truth: internal/db/migrations/postgres
-- Regenerate with: scripts/generate-schema-sql.sh

--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_keys (
    id text NOT NULL,
    user_id text NOT NULL,
    provider text NOT NULL,
    api_key text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: approvals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.approvals (
    id text NOT NULL,
    chat_id text NOT NULL,
    approval_type integer NOT NULL,
    entity_id text NOT NULL,
    status integer NOT NULL,
    denial_reason text,
    title text NOT NULL,
    metadata text,
    created_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    action_taken text,
    temporal_workflow_id text DEFAULT ''::text NOT NULL
);

--
-- Name: attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attachments (
    id text NOT NULL,
    user_id text NOT NULL,
    filename text NOT NULL,
    size bigint NOT NULL,
    mime_type text NOT NULL,
    file_hash text,
    file_path text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    attachment_type text NOT NULL,
    content bytea
);

--
-- Name: background_process_output; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.background_process_output (
    id bigint NOT NULL,
    process_id text NOT NULL,
    seq bigint NOT NULL,
    stream text NOT NULL,
    line text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: background_process_output_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.background_process_output_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: background_process_output_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.background_process_output_id_seq OWNED BY public.background_process_output.id;

--
-- Name: background_processes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.background_processes (
    id text NOT NULL,
    pid bigint,
    command text NOT NULL,
    working_dir text NOT NULL,
    worktree_id text,
    project_id text,
    chat_id text,
    user_id text NOT NULL,
    status integer DEFAULT 1 NOT NULL,
    exit_code bigint,
    started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ended_at timestamp with time zone,
    signature text,
    source_type text DEFAULT 'llm'::text NOT NULL,
    package_type integer,
    command_name text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT background_processes_source_type_check CHECK ((source_type = ANY (ARRAY['llm'::text, 'package_command'::text, 'manual'::text])))
);

--
-- Name: chat_updates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_updates (
    id text NOT NULL,
    chat_id text NOT NULL,
    sequence_number bigint NOT NULL,
    update_type integer NOT NULL,
    entity_id text NOT NULL,
    data text NOT NULL,
    created_at timestamp with time zone NOT NULL
);

--
-- Name: chats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chats (
    id text NOT NULL,
    title text NOT NULL,
    project_id text NOT NULL,
    user_id text NOT NULL,
    state integer DEFAULT 2,
    workflow_id text,
    run_id text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    last_active timestamp with time zone NOT NULL,
    worktree_id text,
    workflow_name text,
    selected_presets text,
    archived_worktree_name text,
    unread integer DEFAULT 0 NOT NULL,
    active_daemon_id text
);

--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id text NOT NULL,
    chat_id text NOT NULL,
    ordinal bigint NOT NULL,
    thread_id text NOT NULL,
    context_window_id text NOT NULL,
    role integer NOT NULL,
    display_style integer,
    model text,
    agent text,
    token_count bigint,
    cost double precision,
    workflow_id text,
    run_id text,
    node_id text,
    node_path text,
    activity_id text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.questions (
    id text NOT NULL,
    chat_id text NOT NULL,
    workflow_id text NOT NULL,
    temporal_workflow_id text DEFAULT ''::text NOT NULL,
    thread_id text DEFAULT ''::text NOT NULL,
    step_id text DEFAULT ''::text NOT NULL,
    loop_node_id text,
    loop_iteration bigint,
    status integer DEFAULT 1 NOT NULL,
    metadata text,
    response_data text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resolved_at timestamp with time zone,
    tool_call_id text
);

--
-- Name: workflows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflows (
    id text NOT NULL,
    parent_id text,
    chat_id text NOT NULL,
    workflow_name text NOT NULL,
    thread text NOT NULL,
    status integer DEFAULT 2 NOT NULL,
    spawned_by_node_id text,
    loop_iteration bigint,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    worker_started_at timestamp with time zone,
    worker_stopped_at timestamp with time zone,
    outcome text
);

--
-- Name: chats_with_activity; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.chats_with_activity AS
 SELECT id,
    title,
    project_id,
    user_id,
    state,
    workflow_id,
    run_id,
    created_at,
    updated_at,
    last_active,
    worktree_id,
    workflow_name,
    selected_presets,
    archived_worktree_name,
    unread,
    active_daemon_id,
    ( SELECT max(m.created_at) AS max
           FROM public.messages m
          WHERE (m.chat_id = c.id)) AS last_message_at,
        CASE
            WHEN (EXISTS ( SELECT 1
               FROM public.approvals a
              WHERE ((a.chat_id = c.id) AND (a.status = 1)))) THEN 2
            WHEN (EXISTS ( SELECT 1
               FROM public.questions q
              WHERE ((q.chat_id = c.id) AND (q.status = 1)))) THEN 2
            WHEN (EXISTS ( SELECT 1
               FROM public.workflows w
              WHERE ((w.chat_id = c.id) AND (w.status = 2)))) THEN 1
            WHEN (EXISTS ( SELECT 1
               FROM public.workflows w
              WHERE ((w.chat_id = c.id) AND (w.status = 4)))) THEN 3
            ELSE 0
        END AS activity
   FROM public.chats c;

--
-- Name: claude_auth_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.claude_auth_tokens (
    id text NOT NULL,
    user_id text NOT NULL,
    access_token text NOT NULL,
    refresh_token text,
    expires_at timestamp with time zone,
    account_uuid text,
    account_email text,
    organization_uuid text,
    organization_name text,
    scope text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: codex_auth_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.codex_auth_tokens (
    id text NOT NULL,
    user_id text NOT NULL,
    access_token text NOT NULL,
    refresh_token text,
    id_token text,
    account_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: command_favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.command_favorites (
    id text NOT NULL,
    user_id text NOT NULL,
    project_id text NOT NULL,
    command_key text NOT NULL,
    created_at timestamp with time zone NOT NULL
);

--
-- Name: context_windows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.context_windows (
    id text NOT NULL,
    thread_id text NOT NULL,
    sequence bigint NOT NULL,
    compaction_summary_message_id text,
    created_at timestamp with time zone NOT NULL,
    parent_context_window_id text,
    fork_at_ordinal bigint
);

--
-- Name: copilot_auth_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.copilot_auth_tokens (
    id text NOT NULL,
    user_id text NOT NULL,
    github_access_token text NOT NULL,
    github_refresh_token text,
    tier text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: daemon_attachment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daemon_attachment (
    daemon_id text NOT NULL,
    user_id text NOT NULL,
    source text NOT NULL,
    attached_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_stream_activity timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    pod_ip text,
    pod_port integer,
    memory_used_bytes bigint DEFAULT 0 NOT NULL,
    memory_limit_bytes bigint DEFAULT 0 NOT NULL,
    memory_pressure boolean DEFAULT false NOT NULL,
    detected_ports text DEFAULT '[]'::text NOT NULL,
    CONSTRAINT daemon_attachment_source_check CHECK ((source = ANY (ARRAY['inbound'::text, 'outbound'::text])))
);

--
-- Name: daemon_pats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daemon_pats (
    id text NOT NULL,
    user_id text NOT NULL,
    token_hash text NOT NULL,
    token_prefix text NOT NULL,
    name text NOT NULL,
    ephemeral boolean DEFAULT false NOT NULL,
    expires_at timestamp with time zone,
    last_used_at timestamp with time zone,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    daemon_id text,
    kind text DEFAULT 'daemon'::text NOT NULL,
    user_email text DEFAULT ''::text NOT NULL
);

--
-- Name: daemons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daemons (
    id text NOT NULL,
    user_id text NOT NULL,
    hostname text,
    platform text,
    capabilities text,
    project_paths text,
    projects_json text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    daemon_type text
);

--
-- Name: default_preset_assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.default_preset_assignments (
    id text NOT NULL,
    workflow_name text NOT NULL,
    group_name text NOT NULL,
    preset_slug text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: item_defaults; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_defaults (
    id text NOT NULL,
    item_type integer NOT NULL,
    slug text NOT NULL,
    is_hidden boolean NOT NULL,
    reason text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: message_content_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_content_blocks (
    id text NOT NULL,
    message_id text NOT NULL,
    "position" bigint NOT NULL,
    block_type integer NOT NULL,
    content text,
    tool_name text,
    tool_input text,
    tool_call_id text,
    is_error boolean,
    version bigint,
    node_id text,
    node_path text,
    activity_id text,
    workflow_run_id text,
    attempt_number bigint,
    thought_signature text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plans (
    id text NOT NULL,
    title text NOT NULL,
    description text,
    status integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    complexity integer,
    project_id text,
    thread_id text DEFAULT ''::text NOT NULL
);

--
-- Name: presets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.presets (
    id text NOT NULL,
    user_id text NOT NULL,
    project_id text,
    name text NOT NULL,
    slug text NOT NULL,
    description text,
    tag text NOT NULL,
    params text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: project_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_configs (
    id text NOT NULL,
    project_id text NOT NULL,
    daemon_id text NOT NULL,
    user_config_yaml text,
    project_config_yaml text,
    local_config_yaml text,
    global_memory_md text,
    project_memory_md text,
    mcp_configs text,
    pushed_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    project_workflows_json text,
    project_presets_json text,
    project_scenarios_json text,
    project_skills_json text,
    repo_memories_json text,
    runtime_type text
);

--
-- Name: project_daemons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_daemons (
    project_id text NOT NULL,
    daemon_id text NOT NULL,
    path text NOT NULL,
    default_branch text,
    cloned_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id text NOT NULL,
    name text NOT NULL,
    path text NOT NULL,
    user_id text NOT NULL,
    description text,
    is_git_repo boolean DEFAULT true NOT NULL,
    default_branch text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    last_active timestamp with time zone NOT NULL,
    remote_url text,
    is_forge boolean DEFAULT false NOT NULL
);

--
-- Name: provider_backoff; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provider_backoff (
    thread_id text NOT NULL,
    chat_id text NOT NULL,
    waiting_since timestamp with time zone,
    resume_at timestamp with time zone,
    attempt bigint DEFAULT 0 NOT NULL,
    max_attempts bigint DEFAULT 0 NOT NULL,
    status_code bigint DEFAULT 0 NOT NULL,
    reason text DEFAULT ''::text NOT NULL,
    retries bigint DEFAULT 0 NOT NULL,
    waited_ms bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: repos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.repos (
    id text NOT NULL,
    project_id text NOT NULL,
    name text NOT NULL,
    relative_path text DEFAULT ''::text NOT NULL,
    remote_url text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    id text NOT NULL,
    user_id text NOT NULL,
    project_id text,
    key text NOT NULL,
    value text NOT NULL,
    value_type text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: step_executions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.step_executions (
    id text NOT NULL,
    workflow_id text NOT NULL,
    step_id text NOT NULL,
    activity_name text NOT NULL,
    output_json text,
    exit_code bigint,
    success bigint,
    duration_ms bigint,
    created_at timestamp with time zone NOT NULL,
    loop_node_id text,
    loop_iteration bigint
);

--
-- Name: task_dependencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_dependencies (
    id text NOT NULL,
    from_task_id text NOT NULL,
    to_task_id text NOT NULL,
    dependency_type integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tasks (
    id text NOT NULL,
    plan_id text NOT NULL,
    parent_task_id text,
    title text NOT NULL,
    description text,
    status integer DEFAULT 1 NOT NULL,
    "position" bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    metadata text,
    assignee text
);

--
-- Name: threads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.threads (
    id text NOT NULL,
    conversation_id text NOT NULL,
    parent_thread_id text,
    fork_at_ordinal bigint,
    fork_at_context_window_id text,
    workflow_id text,
    created_at timestamp with time zone NOT NULL,
    title text
);

--
-- Name: user_updates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_updates (
    id text NOT NULL,
    user_id text NOT NULL,
    sequence_number bigint NOT NULL,
    project_id text,
    worktree_id text,
    chat_id text,
    update_type integer NOT NULL,
    entity_type integer NOT NULL,
    entity_id text NOT NULL,
    data text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--
-- Name: visibility_overrides; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.visibility_overrides (
    id text NOT NULL,
    user_id text NOT NULL,
    item_type integer NOT NULL,
    slug text NOT NULL,
    is_visible boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);

--
-- Name: workflow_checkpoints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_checkpoints (
    workflow_id text NOT NULL,
    chat_id text NOT NULL,
    node_id text NOT NULL,
    loop_iteration bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

--
-- Name: workflow_drafts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_drafts (
    id text NOT NULL,
    user_id text NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    description text,
    definition text NOT NULL,
    is_valid bigint NOT NULL,
    validation_errors text,
    source_path text,
    forked_from text,
    is_hidden boolean NOT NULL,
    chat_id text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    version bigint NOT NULL
);

--
-- Name: workflow_scenarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_scenarios (
    id text NOT NULL,
    workflow_draft_id text,
    user_id text NOT NULL,
    name text NOT NULL,
    description text,
    events text NOT NULL,
    expect text,
    last_run_at timestamp with time zone,
    last_run_status text,
    last_run_result text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    version bigint NOT NULL
);

--
-- Name: worktrees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.worktrees (
    id text NOT NULL,
    name text NOT NULL,
    path text NOT NULL,
    branch text NOT NULL,
    base_branch text NOT NULL,
    project_id text NOT NULL,
    chat_id text,
    status integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    last_active timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    is_main boolean DEFAULT false NOT NULL,
    cleanup_metadata text,
    base_branches text,
    daemon_id text
);

--
-- Name: background_process_output id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.background_process_output ALTER COLUMN id SET DEFAULT nextval('public.background_process_output_id_seq'::regclass);

--
-- Name: api_keys api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);

--
-- Name: api_keys api_keys_user_id_provider_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_user_id_provider_key UNIQUE (user_id, provider);

--
-- Name: approvals approvals_entity_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.approvals
    ADD CONSTRAINT approvals_entity_id_key UNIQUE (entity_id);

--
-- Name: approvals approvals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.approvals
    ADD CONSTRAINT approvals_pkey PRIMARY KEY (id);

--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);

--
-- Name: background_process_output background_process_output_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.background_process_output
    ADD CONSTRAINT background_process_output_pkey PRIMARY KEY (id);

--
-- Name: background_processes background_processes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.background_processes
    ADD CONSTRAINT background_processes_pkey PRIMARY KEY (id);

--
-- Name: chat_updates chat_updates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_updates
    ADD CONSTRAINT chat_updates_pkey PRIMARY KEY (id);

--
-- Name: chats chats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_pkey PRIMARY KEY (id);

--
-- Name: claude_auth_tokens claude_auth_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claude_auth_tokens
    ADD CONSTRAINT claude_auth_tokens_pkey PRIMARY KEY (id);

--
-- Name: claude_auth_tokens claude_auth_tokens_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claude_auth_tokens
    ADD CONSTRAINT claude_auth_tokens_user_id_key UNIQUE (user_id);

--
-- Name: codex_auth_tokens codex_auth_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.codex_auth_tokens
    ADD CONSTRAINT codex_auth_tokens_pkey PRIMARY KEY (id);

--
-- Name: codex_auth_tokens codex_auth_tokens_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.codex_auth_tokens
    ADD CONSTRAINT codex_auth_tokens_user_id_key UNIQUE (user_id);

--
-- Name: command_favorites command_favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_favorites
    ADD CONSTRAINT command_favorites_pkey PRIMARY KEY (id);

--
-- Name: command_favorites command_favorites_user_id_project_id_command_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_favorites
    ADD CONSTRAINT command_favorites_user_id_project_id_command_key_key UNIQUE (user_id, project_id, command_key);

--
-- Name: context_windows context_windows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.context_windows
    ADD CONSTRAINT context_windows_pkey PRIMARY KEY (id);

--
-- Name: copilot_auth_tokens copilot_auth_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_auth_tokens
    ADD CONSTRAINT copilot_auth_tokens_pkey PRIMARY KEY (id);

--
-- Name: copilot_auth_tokens copilot_auth_tokens_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_auth_tokens
    ADD CONSTRAINT copilot_auth_tokens_user_id_key UNIQUE (user_id);

--
-- Name: daemon_attachment daemon_attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daemon_attachment
    ADD CONSTRAINT daemon_attachment_pkey PRIMARY KEY (daemon_id);

--
-- Name: daemon_pats daemon_pats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daemon_pats
    ADD CONSTRAINT daemon_pats_pkey PRIMARY KEY (id);

--
-- Name: daemons daemons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daemons
    ADD CONSTRAINT daemons_pkey PRIMARY KEY (id);

--
-- Name: default_preset_assignments default_preset_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.default_preset_assignments
    ADD CONSTRAINT default_preset_assignments_pkey PRIMARY KEY (id);

--
-- Name: default_preset_assignments default_preset_assignments_workflow_name_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.default_preset_assignments
    ADD CONSTRAINT default_preset_assignments_workflow_name_group_name_key UNIQUE (workflow_name, group_name);

--
-- Name: item_defaults item_defaults_item_type_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_defaults
    ADD CONSTRAINT item_defaults_item_type_slug_key UNIQUE (item_type, slug);

--
-- Name: item_defaults item_defaults_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_defaults
    ADD CONSTRAINT item_defaults_pkey PRIMARY KEY (id);

--
-- Name: message_content_blocks message_content_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_content_blocks
    ADD CONSTRAINT message_content_blocks_pkey PRIMARY KEY (id);

--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);

--
-- Name: plans plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_pkey PRIMARY KEY (id);

--
-- Name: presets presets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.presets
    ADD CONSTRAINT presets_pkey PRIMARY KEY (id);

--
-- Name: presets presets_user_id_project_id_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.presets
    ADD CONSTRAINT presets_user_id_project_id_slug_key UNIQUE (user_id, project_id, slug);

--
-- Name: project_configs project_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_configs
    ADD CONSTRAINT project_configs_pkey PRIMARY KEY (id);

--
-- Name: project_configs project_configs_project_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_configs
    ADD CONSTRAINT project_configs_project_id_key UNIQUE (project_id);

--
-- Name: project_daemons project_daemons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_daemons
    ADD CONSTRAINT project_daemons_pkey PRIMARY KEY (project_id, daemon_id);

--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

--
-- Name: projects projects_user_id_path_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_user_id_path_key UNIQUE (user_id, path);

--
-- Name: provider_backoff provider_backoff_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provider_backoff
    ADD CONSTRAINT provider_backoff_pkey PRIMARY KEY (thread_id);

--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);

--
-- Name: repos repos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repos
    ADD CONSTRAINT repos_pkey PRIMARY KEY (id);

--
-- Name: repos repos_project_id_relative_path_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repos
    ADD CONSTRAINT repos_project_id_relative_path_key UNIQUE (project_id, relative_path);

--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (id);

--
-- Name: settings settings_user_id_project_id_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_user_id_project_id_key_key UNIQUE (user_id, project_id, key);

--
-- Name: step_executions step_executions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.step_executions
    ADD CONSTRAINT step_executions_pkey PRIMARY KEY (id);

--
-- Name: task_dependencies task_dependencies_from_task_id_to_task_id_dependency_type_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_dependencies
    ADD CONSTRAINT task_dependencies_from_task_id_to_task_id_dependency_type_key UNIQUE (from_task_id, to_task_id, dependency_type);

--
-- Name: task_dependencies task_dependencies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_dependencies
    ADD CONSTRAINT task_dependencies_pkey PRIMARY KEY (id);

--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);

--
-- Name: threads threads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.threads
    ADD CONSTRAINT threads_pkey PRIMARY KEY (id);

--
-- Name: user_updates user_updates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_updates
    ADD CONSTRAINT user_updates_pkey PRIMARY KEY (id);

--
-- Name: user_updates user_updates_user_id_sequence_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_updates
    ADD CONSTRAINT user_updates_user_id_sequence_number_key UNIQUE (user_id, sequence_number);

--
-- Name: visibility_overrides visibility_overrides_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.visibility_overrides
    ADD CONSTRAINT visibility_overrides_pkey PRIMARY KEY (id);

--
-- Name: visibility_overrides visibility_overrides_user_id_item_type_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.visibility_overrides
    ADD CONSTRAINT visibility_overrides_user_id_item_type_slug_key UNIQUE (user_id, item_type, slug);

--
-- Name: workflow_checkpoints workflow_checkpoints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_checkpoints
    ADD CONSTRAINT workflow_checkpoints_pkey PRIMARY KEY (workflow_id);

--
-- Name: workflow_drafts workflow_drafts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_drafts
    ADD CONSTRAINT workflow_drafts_pkey PRIMARY KEY (id);

--
-- Name: workflow_drafts workflow_drafts_user_id_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_drafts
    ADD CONSTRAINT workflow_drafts_user_id_slug_key UNIQUE (user_id, slug);

--
-- Name: workflow_scenarios workflow_scenarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_scenarios
    ADD CONSTRAINT workflow_scenarios_pkey PRIMARY KEY (id);

--
-- Name: workflows workflows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflows
    ADD CONSTRAINT workflows_pkey PRIMARY KEY (id);

--
-- Name: worktrees worktrees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worktrees
    ADD CONSTRAINT worktrees_pkey PRIMARY KEY (id);

--
-- Name: worktrees worktrees_project_id_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worktrees
    ADD CONSTRAINT worktrees_project_id_name_key UNIQUE (project_id, name);

--
-- Name: idx_api_keys_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_keys_provider ON public.api_keys USING btree (user_id, provider);

--
-- Name: idx_api_keys_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_keys_user ON public.api_keys USING btree (user_id);

--
-- Name: idx_bg_proc_output_process_seq; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bg_proc_output_process_seq ON public.background_process_output USING btree (process_id, seq);

--
-- Name: idx_bg_processes_chat; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bg_processes_chat ON public.background_processes USING btree (chat_id) WHERE (chat_id IS NOT NULL);

--
-- Name: idx_bg_processes_cleanup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bg_processes_cleanup ON public.background_processes USING btree (status, ended_at) WHERE (status = ANY (ARRAY[2, 3, 4, 5, 6]));

--
-- Name: idx_bg_processes_running; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bg_processes_running ON public.background_processes USING btree (status, pid) WHERE (status = 1);

--
-- Name: idx_bg_processes_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bg_processes_user ON public.background_processes USING btree (user_id, status);

--
-- Name: idx_bg_processes_worktree; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bg_processes_worktree ON public.background_processes USING btree (worktree_id, status);

--
-- Name: idx_chat_updates_chat_seq; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_updates_chat_seq ON public.chat_updates USING btree (chat_id, sequence_number DESC);

--
-- Name: idx_chat_updates_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chat_updates_created ON public.chat_updates USING btree (created_at DESC);

--
-- Name: idx_claude_auth_tokens_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_claude_auth_tokens_user ON public.claude_auth_tokens USING btree (user_id);

--
-- Name: idx_codex_auth_tokens_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_codex_auth_tokens_user ON public.codex_auth_tokens USING btree (user_id);

--
-- Name: idx_copilot_auth_tokens_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_copilot_auth_tokens_user ON public.copilot_auth_tokens USING btree (user_id);

--
-- Name: idx_daemon_attachment_last_activity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daemon_attachment_last_activity ON public.daemon_attachment USING btree (last_stream_activity);

--
-- Name: idx_daemon_attachment_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daemon_attachment_user_id ON public.daemon_attachment USING btree (user_id);

--
-- Name: idx_daemon_pats_token_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daemon_pats_token_hash ON public.daemon_pats USING btree (token_hash);

--
-- Name: idx_daemon_pats_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daemon_pats_user_id ON public.daemon_pats USING btree (user_id);

--
-- Name: idx_daemons_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daemons_user_id ON public.daemons USING btree (user_id);

--
-- Name: idx_plans_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plans_project ON public.plans USING btree (project_id) WHERE (project_id IS NOT NULL);

--
-- Name: idx_plans_thread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plans_thread ON public.plans USING btree (thread_id);

--
-- Name: idx_project_configs_daemon_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_configs_daemon_id ON public.project_configs USING btree (daemon_id);

--
-- Name: idx_project_configs_pushed_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_configs_pushed_at ON public.project_configs USING btree (pushed_at DESC);

--
-- Name: idx_provider_backoff_chat_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_provider_backoff_chat_id ON public.provider_backoff USING btree (chat_id);

--
-- Name: idx_questions_chat_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_questions_chat_id ON public.questions USING btree (chat_id);

--
-- Name: idx_questions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_questions_status ON public.questions USING btree (status);

--
-- Name: idx_questions_workflow_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_questions_workflow_id ON public.questions USING btree (workflow_id);

--
-- Name: idx_repos_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_repos_project ON public.repos USING btree (project_id);

--
-- Name: idx_task_deps_from; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_task_deps_from ON public.task_dependencies USING btree (from_task_id);

--
-- Name: idx_task_deps_to; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_task_deps_to ON public.task_dependencies USING btree (to_task_id);

--
-- Name: idx_task_deps_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_task_deps_type ON public.task_dependencies USING btree (dependency_type);

--
-- Name: idx_user_updates_chat; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_updates_chat ON public.user_updates USING btree (chat_id) WHERE (chat_id IS NOT NULL);

--
-- Name: idx_user_updates_entity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_updates_entity ON public.user_updates USING btree (entity_type, entity_id);

--
-- Name: idx_user_updates_poll; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_updates_poll ON public.user_updates USING btree (user_id, sequence_number DESC);

--
-- Name: idx_user_updates_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_updates_project ON public.user_updates USING btree (project_id, sequence_number DESC) WHERE (project_id IS NOT NULL);

--
-- Name: idx_workflow_checkpoints_chat_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_workflow_checkpoints_chat_id ON public.workflow_checkpoints USING btree (chat_id);

--
-- Name: project_daemons_daemon_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX project_daemons_daemon_idx ON public.project_daemons USING btree (daemon_id);

--
-- Name: projects_user_remote_url_uniq; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX projects_user_remote_url_uniq ON public.projects USING btree (user_id, remote_url) WHERE (remote_url IS NOT NULL);

--
-- Name: background_process_output background_process_output_process_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.background_process_output
    ADD CONSTRAINT background_process_output_process_id_fkey FOREIGN KEY (process_id) REFERENCES public.background_processes(id) ON DELETE CASCADE;

--
-- Name: background_processes background_processes_chat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.background_processes
    ADD CONSTRAINT background_processes_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id) ON DELETE SET NULL;

--
-- Name: background_processes background_processes_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.background_processes
    ADD CONSTRAINT background_processes_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;

--
-- Name: background_processes background_processes_worktree_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.background_processes
    ADD CONSTRAINT background_processes_worktree_id_fkey FOREIGN KEY (worktree_id) REFERENCES public.worktrees(id) ON DELETE SET NULL;

--
-- Name: plans plans_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

--
-- Name: project_configs project_configs_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_configs
    ADD CONSTRAINT project_configs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

--
-- Name: project_daemons project_daemons_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_daemons
    ADD CONSTRAINT project_daemons_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

--
-- Name: repos repos_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repos
    ADD CONSTRAINT repos_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

--
-- Name: task_dependencies task_dependencies_from_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_dependencies
    ADD CONSTRAINT task_dependencies_from_task_id_fkey FOREIGN KEY (from_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;

--
-- Name: task_dependencies task_dependencies_to_task_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_dependencies
    ADD CONSTRAINT task_dependencies_to_task_id_fkey FOREIGN KEY (to_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;

--
-- Name: user_updates user_updates_chat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_updates
    ADD CONSTRAINT user_updates_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id) ON DELETE CASCADE;

--
-- Name: user_updates user_updates_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_updates
    ADD CONSTRAINT user_updates_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

--
-- Name: user_updates user_updates_worktree_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_updates
    ADD CONSTRAINT user_updates_worktree_id_fkey FOREIGN KEY (worktree_id) REFERENCES public.worktrees(id) ON DELETE CASCADE;

--
-- PostgreSQL database dump complete
--
