// Code generated by go run ./internal/workflow/yaml/cmd/yamlbindingsgen; DO NOT EDIT.

package wfyaml

import "google.golang.org/protobuf/reflect/protoreflect"

type generatedNodeBinding struct {
	oneofFieldName protoreflect.Name
	isStructural   bool
	argFieldKeys   map[string]struct{}
}

const yamlKeyID = "id"
const yamlKeyType = "type"
const yamlKeyCondition = "condition"
const yamlKeyTimeout = "timeout"
const yamlKeySaveMessage = "save_message"
const yamlKeyArgs = "args"
const yamlKeyFrom = "from"
const yamlKeyCases = "cases"
const yamlKeyDefault = "default"
const yamlKeyTo = "to"
const yamlKeyLabel = "label"

var generatedNodeBaseFieldKeys = map[string]struct{}{
	"condition":    {},
	"id":           {},
	"save_message": {},
	"timeout":      {},
	"type":         {},
}

var generatedEdgeFieldKeys = map[string]struct{}{
	"cases":   {},
	"default": {},
	"from":    {},
}

var generatedEdgeCaseFieldKeys = map[string]struct{}{
	"condition": {},
	"label":     {},
	"to":        {},
}

var generatedNodeBindingsByType = map[string]generatedNodeBinding{
	"approval": {
		oneofFieldName: "approval",
		isStructural:   false,
		argFieldKeys: map[string]struct{}{
			"timeout": {},
			"title":   {},
		},
	},
	"call_llm": {
		oneofFieldName: "call_llm",
		isStructural:   false,
		argFieldKeys: map[string]struct{}{
			"max_tokens":     {},
			"messages":       {},
			"model":          {},
			"response_tool":  {},
			"system_prompt":  {},
			"temperature":    {},
			"thinking_level": {},
			"tool_filter":    {},
			"tools":          {},
		},
	},
	"compact": {
		oneofFieldName: "compact",
		isStructural:   false,
		argFieldKeys:   map[string]struct{}{},
	},
	"create_worktree": {
		oneofFieldName: "create_worktree",
		isStructural:   false,
		argFieldKeys: map[string]struct{}{
			"base_branch": {},
			"branch":      {},
			"copy_files":  {},
			"force":       {},
			"name":        {},
		},
	},
	"execute_tools": {
		oneofFieldName: "execute_tools",
		isStructural:   false,
		argFieldKeys: map[string]struct{}{
			"expected_response_tools": {},
			"resolved_tool_calls":     {},
			"response_tool_schemas":   {},
			"tool_calls":              {},
		},
	},
	"join": {
		oneofFieldName: "join",
		isStructural:   true,
		argFieldKeys:   map[string]struct{}{},
	},
	"loop": {
		oneofFieldName: "loop",
		isStructural:   true,
		argFieldKeys: map[string]struct{}{
			"args":       {},
			"inline":     {},
			"items":      {},
			"key":        {},
			"on_failure": {},
			"parallel":   {},
			"presets":    {},
			"project":    {},
			"ref":        {},
			"thread":     {},
			"while":      {},
			"yield":      {},
		},
	},
	"router": {
		oneofFieldName: "router",
		isStructural:   true,
		argFieldKeys: map[string]struct{}{
			"fallback":        {},
			"include_history": {},
			"model":           {},
			"project":         {},
			"prompt":          {},
			"system_prompt":   {},
			"thread":          {},
			"workflows":       {},
		},
	},
	"run": {
		oneofFieldName: "run",
		isStructural:   true,
		argFieldKeys: map[string]struct{}{
			"command":  {},
			"env":      {},
			"work_dir": {},
		},
	},
	"save_message": {
		oneofFieldName: "save_message_node",
		isStructural:   false,
		argFieldKeys: map[string]struct{}{
			"attachments":            {},
			"content":                {},
			"display_style":          {},
			"resolved_attachments":   {},
			"resolved_content":       {},
			"resolved_display_style": {},
			"resolved_role":          {},
			"resolved_thinking":      {},
			"resolved_tool_calls":    {},
			"resolved_tool_results":  {},
			"role":                   {},
			"token_count":            {},
			"tool_calls":             {},
			"tool_results":           {},
		},
	},
	"workflow": {
		oneofFieldName: "workflow",
		isStructural:   true,
		argFieldKeys: map[string]struct{}{
			"args":    {},
			"inline":  {},
			"presets": {},
			"project": {},
			"ref":     {},
			"thread":  {},
		},
	},
}

func generatedNodeBindingForType(nodeType string) (generatedNodeBinding, bool) {
	binding, ok := generatedNodeBindingsByType[nodeType]
	return binding, ok
}

func generatedHasNodeBaseFieldKey(key string) bool {
	_, ok := generatedNodeBaseFieldKeys[key]
	return ok
}

func generatedHasEdgeFieldKey(key string) bool {
	_, ok := generatedEdgeFieldKeys[key]
	return ok
}

func generatedHasEdgeCaseFieldKey(key string) bool {
	_, ok := generatedEdgeCaseFieldKeys[key]
	return ok
}
