// Copyright (c) 2025 Reliant Labs
//
// CLI reference generator - generates documentation from the Cobra command tree.
//
// SOURCE OF TRUTH:
//   - cmd/reliant/commands/ (Cobra command definitions)
//
// GENERATED FILE:
//   - generated/docs-source/reference/cli.md
//
// Usage: go run ./tools/docgen/cli <output_file>
// Regenerate with: make generate-cli

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/reliant-labs/reliant/cmd/reliant/commands"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: %s <output_file>\n", os.Args[0])
		os.Exit(1)
	}

	outputFile := os.Args[1]

	root := commands.NewRootCmd()
	markdown, cmdCount := generateMarkdown(root)

	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, []byte(markdown), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated CLI reference: %s (%d commands)\n", outputFile, cmdCount)
}

func generateMarkdown(root *cobra.Command) (string, int) {
	var sb strings.Builder
	cmdCount := 0

	sb.WriteString(`---
# =============================================================================
# GENERATED FILE - DO NOT EDIT DIRECTLY
#
# Source of truth: cmd/reliant/commands/ (Cobra command definitions)
# Generated by: go run ./tools/docgen/cli
# Regenerate with: make generate-cli
# =============================================================================
title: "CLI Reference"
description: "Complete reference for all Reliant CLI commands, flags, and options"
weight: 30
---

The Reliant CLI provides commands for running server components, managing the local
tools daemon, authenticating, and working with workflows.

## Quick Reference

`)

	// Build quick reference table
	sb.WriteString("| Command | Description |\n")
	sb.WriteString("|---------|-------------|\n")
	writeQuickReference(&sb, root, "reliant")
	sb.WriteString("\n")

	// Global flags
	sb.WriteString("## Global Flags\n\n")
	sb.WriteString("These flags are available on all commands.\n\n")
	writeFlags(&sb, root.PersistentFlags())
	sb.WriteString("\n---\n\n")

	// Document each top-level command and its subcommands
	topLevel := root.Commands()
	sort.Slice(topLevel, func(i, j int) bool {
		return topLevel[i].Name() < topLevel[j].Name()
	})

	for _, cmd := range topLevel {
		if cmd.Hidden || cmd.Name() == "help" || cmd.Name() == "completion" {
			continue
		}
		cmdCount += writeCommand(&sb, cmd, "reliant", 2)
	}

	return sb.String(), cmdCount
}

// writeQuickReference writes a summary table row for each command recursively.
func writeQuickReference(sb *strings.Builder, cmd *cobra.Command, prefix string) {
	for _, sub := range cmd.Commands() {
		if sub.Hidden || sub.Name() == "help" || sub.Name() == "completion" {
			continue
		}
		fullName := prefix + " " + sub.Name()
		anchor := strings.ReplaceAll(fullName, " ", "-")
		fmt.Fprintf(sb, "| [`%s`](#%s) | %s |\n", fullName, anchor, sub.Short)
		writeQuickReference(sb, sub, fullName)
	}
}

// writeCommand writes the full documentation for a command and its subcommands.
// Returns the count of commands documented.
func writeCommand(sb *strings.Builder, cmd *cobra.Command, parentPath string, headingLevel int) int {
	count := 1
	fullPath := parentPath + " " + cmd.Name()
	heading := strings.Repeat("#", headingLevel)

	fmt.Fprintf(sb, "%s %s\n\n", heading, fullPath)

	// Short + long description
	if cmd.Short != "" {
		fmt.Fprintf(sb, "%s\n\n", cmd.Short)
	}
	if cmd.Long != "" {
		fmt.Fprintf(sb, "%s\n\n", cmd.Long)
	}

	// Usage
	fmt.Fprintf(sb, "```\n%s\n```\n\n", cmd.UseLine())

	// Subcommands summary (if any non-hidden subcommands exist)
	subs := cmd.Commands()
	visibleSubs := filterVisible(subs)
	if len(visibleSubs) > 0 {
		sb.WriteString("**Subcommands:**\n\n")
		sb.WriteString("| Command | Description |\n")
		sb.WriteString("|---------|-------------|\n")
		for _, sub := range visibleSubs {
			subFull := fullPath + " " + sub.Name()
			anchor := strings.ReplaceAll(subFull, " ", "-")
			fmt.Fprintf(sb, "| [`%s`](#%s) | %s |\n", sub.Name(), anchor, sub.Short)
		}
		sb.WriteString("\n")
	}

	// Flags specific to this command (non-persistent, non-inherited)
	localFlags := cmd.NonInheritedFlags()
	if localFlags.HasFlags() {
		sb.WriteString("**Flags:**\n\n")
		writeFlags(sb, localFlags)
		sb.WriteString("\n")
	}

	sb.WriteString("---\n\n")

	// Recurse into subcommands at the next heading level (cap at h4)
	nextLevel := headingLevel + 1
	if nextLevel > 4 {
		nextLevel = 4
	}
	sort.Slice(visibleSubs, func(i, j int) bool {
		return visibleSubs[i].Name() < visibleSubs[j].Name()
	})
	for _, sub := range visibleSubs {
		count += writeCommand(sb, sub, fullPath, nextLevel)
	}

	return count
}

// writeFlags writes a markdown table of flags.
func writeFlags(sb *strings.Builder, flags *pflag.FlagSet) {
	type flagInfo struct {
		name         string
		shorthand    string
		typeName     string
		defaultValue string
		usage        string
	}

	var flagList []flagInfo
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		flagList = append(flagList, flagInfo{
			name:         f.Name,
			shorthand:    f.Shorthand,
			typeName:     f.Value.Type(),
			defaultValue: f.DefValue,
			usage:        f.Usage,
		})
	})

	if len(flagList) == 0 {
		return
	}

	sb.WriteString("| Flag | Type | Default | Description |\n")
	sb.WriteString("|------|------|---------|-------------|\n")
	for _, f := range flagList {
		flag := "`--" + f.name + "`"
		if f.shorthand != "" {
			flag += ", `-" + f.shorthand + "`"
		}

		def := f.defaultValue
		if def == "" {
			def = "-"
		} else {
			// Truncate long defaults (e.g., URLs)
			if len(def) > 40 {
				def = def[:37] + "..."
			}
			def = "`" + def + "`"
		}

		typeName := f.typeName
		if typeName == "bool" {
			if def == "`false`" {
				def = "-"
			}
		}

		fmt.Fprintf(sb, "| %s | `%s` | %s | %s |\n", flag, typeName, def, f.usage)
	}
}

// filterVisible returns only non-hidden, non-help commands.
func filterVisible(cmds []*cobra.Command) []*cobra.Command {
	var visible []*cobra.Command
	for _, cmd := range cmds {
		if !cmd.Hidden && cmd.Name() != "help" && cmd.Name() != "completion" {
			visible = append(visible, cmd)
		}
	}
	return visible
}
