#!/bin/bash
# Regenerate internal/db/postgres/schema.sql from the migrations.
#
# schema.sql is sqlc's declared input, but the migrations under
# internal/db/migrations/postgres are the source of truth for the schema. This
# script derives one from the other: it applies every migration to a throwaway
# Postgres and dumps the result, so the file cannot describe a schema the
# migrations do not produce.
#
# Usage: scripts/generate-schema-sql.sh
#
# Requires docker. Postgres runs in a disposable container on its own port and
# is removed on exit, so this touches no database you already have running.

set -euo pipefail

# Must match the Postgres major the project actually runs (docker-compose.yml and
# .github/workflows/check-migrations.yml both use 16). Dumping from a newer major
# emits directives that major cannot parse -- pg_dump 17 writes
# `SET transaction_timeout`, which 16 rejects outright, making schema.sql
# unloadable everywhere it is actually consumed.
PG_IMAGE="postgres:16-alpine"
OUT="internal/db/postgres/schema.sql"
MIGRATIONS="internal/db/migrations/postgres"
CONTAINER="reliant-schema-dump-$$"
PGPASSWORD_VALUE="postgres"

if [ ! -d "$MIGRATIONS" ]; then
  echo "❌ Migration directory not found: $MIGRATIONS (run from the repo root)" >&2
  exit 1
fi

cleanup() {
  docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
}
trap cleanup EXIT

echo "▶ Starting disposable Postgres ($PG_IMAGE)..."
docker run -d --name "$CONTAINER" \
  -e POSTGRES_PASSWORD="$PGPASSWORD_VALUE" \
  -e POSTGRES_USER=postgres \
  -e POSTGRES_DB=schema_dump \
  -P "$PG_IMAGE" >/dev/null

# Wait for the server to accept connections. pg_isready reports readiness of the
# server itself, so this cannot race ahead of a still-initialising cluster.
for _ in $(seq 1 60); do
  if docker exec "$CONTAINER" pg_isready -U postgres -d schema_dump >/dev/null 2>&1; then
    ready=1
    break
  fi
  sleep 1
done
if [ "${ready:-0}" != "1" ]; then
  echo "❌ Postgres container did not become ready in 60s" >&2
  docker logs "$CONTAINER" >&2 || true
  exit 1
fi

echo "▶ Applying migrations from $MIGRATIONS..."
# goose is run against the container's own socket via docker exec so this needs
# no host psql/goose and no published port.
docker exec -i "$CONTAINER" mkdir -p /migrations
docker cp "$MIGRATIONS/." "$CONTAINER:/migrations/" >/dev/null

# Apply migrations in filename order with psql. Each goose migration's Up
# section is delimited by the goose annotations, so strip everything from the
# "-- +goose Down" marker onward and feed the rest to psql.
shopt -s nullglob
migrations=("$MIGRATIONS"/*.sql)
shopt -u nullglob
if [ ${#migrations[@]} -eq 0 ]; then
  echo "❌ No migrations found in $MIGRATIONS — refusing to emit an empty schema" >&2
  exit 1
fi

for m in "${migrations[@]}"; do
  name="$(basename "$m")"
  # Take the Up section only, honouring goose's StatementBegin/End blocks by
  # simply cutting at the Down marker.
  if ! sed '/^-- +goose Down/,$d' "$m" \
    | sed -e '/^-- +goose /d' \
    | docker exec -i "$CONTAINER" psql -U postgres -d schema_dump -v ON_ERROR_STOP=1 -q >/dev/null; then
    echo "❌ Migration failed to apply: $name" >&2
    exit 1
  fi
done
echo "  applied ${#migrations[@]} migrations"

echo "▶ Dumping schema..."
# --schema-only: no data. --no-owner/--no-privileges: the dump must not carry
# the local role names. pg_dump emits objects in dependency order, so the result
# replays into an empty database as-is.
raw="$(docker exec "$CONTAINER" pg_dump -U postgres -d schema_dump \
  --schema-only --no-owner --no-privileges --schema=public)"

# Post-process into valid sqlc input:
#   - \restrict/\unrestrict are psql meta-commands carrying a per-run nonce;
#     they are not SQL and would make every regeneration a spurious diff.
#   - the "Dumped by/from ... version" lines change with the local image and
#     would likewise churn.
#   - CREATE SCHEMA public is dropped so the file loads into any fresh database,
#     which already has a public schema.
cleaned="$(printf '%s\n' "$raw" \
  | sed -e '/^\\restrict /d' \
        -e '/^\\unrestrict /d' \
        -e '/^-- Dumped from database version /d' \
        -e '/^-- Dumped by pg_dump version /d' \
        -e '/^CREATE SCHEMA public;$/d' \
  | cat -s)"

# Refuse to write a schema that describes nothing. Without this, any failure
# that yields an empty dump would silently truncate sqlc's only input.
table_count="$(printf '%s\n' "$cleaned" | grep -c '^CREATE TABLE ' || true)"
if [ "$table_count" -lt 2 ]; then
  echo "❌ Dump contains $table_count tables — refusing to overwrite $OUT" >&2
  exit 1
fi

{
  echo "-- Code generated by scripts/generate-schema-sql.sh. DO NOT EDIT."
  echo "--"
  echo "-- Source of truth: $MIGRATIONS"
  echo "-- Regenerate with: scripts/generate-schema-sql.sh"
  echo ""
  printf '%s\n' "$cleaned"
} > "$OUT"

echo "✅ Wrote $OUT ($table_count tables)"
echo "   Next: make sqlc"
