// Code generated by tools/docgen/activities. DO NOT EDIT.
// Regenerate with: make generate-nodes

package schema

// init populates FieldDescriptions with docstrings extracted from source.
// The map and GetFieldDescription function are defined in field_descriptions_base.go.
func init() {
}
