// Copyright (c) 2025 Reliant Labs
//
// Types reference generator - generates documentation for shared config and output types.
//
// SOURCE OF TRUTH:
//   - Proto annotations [(reliant)] in workflow_v2.proto
//   - internal/workflow/reference (populated from proto descriptors at init)
//
// GENERATED FILE:
//   - generated/docs-source/reference/types.md
//
// Usage: go run ./tools/docgen/types <output_path>
// Regenerate with: make generate-types

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/reliant-labs/reliant/internal/workflow/reference"
)

// TypeCategory groups types for documentation
type TypeCategory struct {
	Name        string
	Description string
	Types       []string
}

// configTypes are types used to configure node behavior
var configTypes = TypeCategory{
	Name:        "Config Types",
	Description: "These types are used to configure node behavior in workflow definitions.",
	Types: []string{
		"ThreadConfig",
		"InjectConfig",
		"SaveMessageConfig",
		"ProjectConfig",
		"ResponseTool",
		"SubWorkflow",
		"ApprovalAction",
	},
}

// outputTypes are helper types found in node outputs
var outputTypes = TypeCategory{
	Name:        "Output Types",
	Description: "These types represent structured data in node outputs, accessible via CEL expressions like `nodes.<id>.<field>.*`.",
	Types: []string{
		"MessageOutput",
		"ThinkingOutput",
		"ToolCall",
		"ToolResult",
	},
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: %s <output_path>\n", os.Args[0])
		os.Exit(1)
	}

	outputPath := os.Args[1]

	markdown := generateTypesMarkdown()

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, []byte(markdown), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing output: %v\n", err)
		os.Exit(1)
	}

	totalTypes := len(configTypes.Types) + len(outputTypes.Types)
	fmt.Printf("Generated types reference: %s (%d types)\n", outputPath, totalTypes)
}

// escapeMarkdownTable escapes characters that would break markdown table formatting.
func escapeMarkdownTable(s string) string {
	// Replace newlines with spaces for table cells
	s = strings.ReplaceAll(s, "\n", " ")
	// Escape pipe characters
	s = strings.ReplaceAll(s, "|", "\\|")
	return s
}

func generateTypesMarkdown() string {
	var sb strings.Builder

	// Hugo frontmatter
	sb.WriteString(`---
# =============================================================================
# GENERATED FILE - DO NOT EDIT DIRECTLY
#
# Source of truth: proto annotations [(reliant)] via v3/reference package
# Generated by: go run ./tools/docgen/types
# Regenerate with: make generate-types
# =============================================================================
title: Types Reference
weight: 16
description: Reference documentation for workflow config types and output helper types
---

# Types Reference

This reference documents the structured types used in workflow definitions and node outputs.

`)

	// Generate Config Types section
	sb.WriteString(fmt.Sprintf("## %s\n\n", configTypes.Name))
	sb.WriteString(fmt.Sprintf("%s\n\n", configTypes.Description))

	// Sort config types for consistent output
	sortedConfigTypes := make([]string, len(configTypes.Types))
	copy(sortedConfigTypes, configTypes.Types)
	sort.Strings(sortedConfigTypes)

	for _, typeName := range sortedConfigTypes {
		writeSharedType(&sb, typeName)
	}

	// Generate Output Types section
	sb.WriteString(fmt.Sprintf("## %s\n\n", outputTypes.Name))
	sb.WriteString(fmt.Sprintf("%s\n\n", outputTypes.Description))

	// Sort output types for consistent output
	sortedOutputTypes := make([]string, len(outputTypes.Types))
	copy(sortedOutputTypes, outputTypes.Types)
	sort.Strings(sortedOutputTypes)

	for _, typeName := range sortedOutputTypes {
		// Try SharedTypes first, then CELHelperTypes
		if _, ok := reference.GetSharedType(typeName); ok {
			writeSharedType(&sb, typeName)
		} else {
			writeHelperType(&sb, typeName)
		}
	}

	return sb.String()
}

// writeSharedType writes documentation for a type from SharedTypes registry
func writeSharedType(sb *strings.Builder, typeName string) {
	info, ok := reference.GetSharedType(typeName)
	if !ok {
		return
	}

	fmt.Fprintf(sb, "### %s\n\n", typeName)

	if info.Description != "" {
		fmt.Fprintf(sb, "%s\n\n", escapeMarkdownTable(info.Description))
	}

	if len(info.Fields) > 0 {
		sb.WriteString("| Field | Type | Required | Description |\n")
		sb.WriteString("|-------|------|----------|-------------|\n")

		for _, f := range info.Fields {
			required := "No"
			if f.Required {
				required = "Yes"
			}
			desc := f.Description
			if desc == "" {
				desc = "-"
			}
			fmt.Fprintf(sb, "| `%s` | %s | %s | %s |\n",
				f.Name, f.Type, required, escapeMarkdownTable(desc))
		}
		sb.WriteString("\n")
	}

	if info.Example != "" {
		sb.WriteString("**Example:**\n\n")
		sb.WriteString("```yaml\n")
		sb.WriteString(info.Example)
		sb.WriteString("\n```\n\n")
	}

	sb.WriteString("---\n\n")
}

// writeHelperType writes documentation for a type from CELHelperTypes registry
func writeHelperType(sb *strings.Builder, typeName string) {
	info, ok := reference.GetCELHelperType(typeName)
	if !ok {
		return
	}

	fmt.Fprintf(sb, "### %s\n\n", typeName)

	if info.Description != "" {
		fmt.Fprintf(sb, "%s\n\n", escapeMarkdownTable(info.Description))
	}

	if info.AccessPath != "" {
		fmt.Fprintf(sb, "**Access path:** `%s`\n\n", info.AccessPath)
	}

	if len(info.Fields) > 0 {
		sb.WriteString("| Field | Type | Description |\n")
		sb.WriteString("|-------|------|-------------|\n")

		for _, f := range info.Fields {
			desc := f.Description
			if desc == "" {
				desc = "-"
			}
			fmt.Fprintf(sb, "| `%s` | %s | %s |\n",
				f.Name, f.Type, escapeMarkdownTable(desc))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n\n")
}
