// Copyright (c) 2025 Reliant Labs
package llm

import (
	"context"
	"time"

	"github.com/reliant-labs/reliant/internal/llm/models"
	"github.com/reliant-labs/reliant/internal/llm/tools"
	"github.com/reliant-labs/reliant/internal/models/message"
)

type EventType string

const (
	EventContentStart  EventType = "content_start"
	EventToolUseStart  EventType = "tool_use_start"
	EventToolUseDelta  EventType = "tool_use_delta"
	EventToolUseStop   EventType = "tool_use_stop"
	EventContentDelta  EventType = "content_delta"
	EventThinkingStart EventType = "thinking_start"
	EventThinkingDelta EventType = "thinking_delta"
	EventThinkingStop  EventType = "thinking_stop"
	EventContentStop   EventType = "content_stop"
	EventComplete      EventType = "complete"
	EventError         EventType = "error"
	EventWarning       EventType = "warning"
	// EventRetryWait is emitted by a driver immediately BEFORE it sleeps out a
	// retryable provider error (429 / transient 5xx). It carries the wait the
	// driver is about to take, so the caller can record a durable marker while
	// the request is parked instead of the whole ladder happening invisibly
	// inside one activity attempt. Emitted before the sleep, never after: a
	// marker written after the fact cannot make a run that is waiting RIGHT NOW
	// distinguishable from one that is working.
	EventRetryWait EventType = "retry_wait"
)

// RetryWait describes one rung of a driver's provider-error backoff ladder.
type RetryWait struct {
	// Attempt is the 1-based number of the request that just failed.
	Attempt int
	// MaxAttempts is the ladder's ceiling, so a consumer can say "3 of 8".
	MaxAttempts int
	// Delay is how long the driver is about to sleep before retrying.
	Delay time.Duration
	// StatusCode is the provider HTTP status that triggered the retry (429, 503…).
	StatusCode int
	// Reason is the driver's own retry-decision reason ("http_429",
	// "transient_gateway_error", …) — the same string it logs.
	Reason string
}

// TokenUsage contains token information from an LLM response.
// TokenCount represents the total tokens used (input + output + cache).
// This is used for compaction decisions.
type TokenUsage struct {
	TokenCount        int64   // Total tokens (for compaction decisions)
	InputTokens       int64   // Input tokens sent to the model
	OutputTokens      int64   // Output tokens generated by the model
	CachedInputTokens int64   // Cached input tokens billed at a distinct rate when available
	Cost              float64 // Cost in USD

	// Prompt-cache accounting, kept as two SEPARATE counters because only the
	// split answers the diagnostic question. On a long thread the prompt
	// prefix dominates latency, so whether it was served from cache is the
	// difference between a 3s turn and a 200s one:
	//
	//   CacheReadInputTokens > 0                          -> cache HIT (prefix reused)
	//   CacheCreationInputTokens > 0, CacheRead == 0      -> cache WRITE (prefix changed / first call)
	//   both 0 on a provider that populates them          -> caching not in effect
	//
	// A single "cached tokens" number cannot distinguish a hit from a write,
	// which is exactly the distinction needed when a turn stalls.
	//
	// NOT every driver populates these — see the per-driver usage()
	// constructors. Zero here means "this driver reports nothing", not
	// "the cache missed"; check the driver before reading a zero as a miss.
	CacheReadInputTokens     int64 // prompt tokens served FROM cache
	CacheCreationInputTokens int64 // prompt tokens WRITTEN to cache
}

// DriverResponse represents a complete response from a driver
type DriverResponse struct {
	Content           string
	Thinking          string // Extended thinking/reasoning content
	ThinkingSignature string // Signature for multi-turn thinking preservation
	ToolCalls         []message.ToolCall
	Usage             TokenUsage
	FinishReason      message.FinishReason

	// Upstream correlation identifiers copied from provider response headers when available.
	// Used for log correlation between Reliant app logs and HTTP capture tooling (e.g. Proxyman).
	UpstreamRequestID  string // e.g. x-oai-request-id
	UpstreamProxymanID string // e.g. x-proxyman-id
}

// DriverEvent represents a streaming event from a driver
type DriverEvent struct {
	Type EventType

	Model    models.Model // model used for this event
	Content  string
	Thinking string
	Response *DriverResponse
	ToolCall *message.ToolCall
	Error    error
	// Retry is set only on EventRetryWait.
	Retry *RetryWait
}

// Driver represents the interface for interacting with LLM providers
// This was previously called Provider but has been renamed for clarity
// Using interface{} for messages and tools to avoid circular dependencies
type Driver interface {
	Name() string
	// SendMessages sends messages to the model and returns a complete response
	// The messages and tools parameters are interface{} to avoid circular dependencies
	SendMessages(ctx context.Context, prompts []string, messages []message.Message, tools []tools.Tool) (*DriverResponse, error)

	// StreamResponse sends messages to the model and returns a stream of events
	// The messages and tools parameters are interface{} to avoid circular dependencies
	StreamResponse(ctx context.Context, prompts []string, messages []message.Message, tools []tools.Tool) <-chan DriverEvent

	// Model returns the model configuration for this driver
	Model() models.Model

	// ValidateKey validates the API key for this driver using a small model
	ValidateKey(ctx context.Context) error
}

// DriverOptions holds configuration options for creating a driver
type DriverOptions struct {
	SessionID   *string
	ApiKey      string
	Model       models.Model
	MaxTokens   int64
	Temperature *float64 // Optional temperature override (0.0-1.0)

	// Shared Options -- these are not common on ALL models, but are used by multiple providers
	DisableCache     bool
	ReasoningEffort  string
	ExtraHeaders     map[string]string
	WorkingDirectory string // Project or worktree path where the agent is operating

	// ForceToolChoice pins the request to a single named tool, so the model's
	// first emission must be a tool_use block for that tool. Empty means the
	// provider default (auto).
	//
	// Only safe for ONE-SHOT requests where the named tool is the only tool.
	// A pin applies to every request in a turn loop, so an agent handed real
	// tools alongside a pinned one could never call them — see
	// soleCodexResponseToolName in drivers/codex/driver.go for the incident
	// this warning comes from.
	ForceToolChoice string

	// Anthropic-specific options
	UseBedrock bool

	// Copilot-specific options. Auth is the raw GitHub OAuth token as a Bearer
	// credential against a single host; there is no tier or session-token concept.
	BearerToken string

	// OpenAI-specific options
	BaseURL string

	// Gemini-specific options
	SafetyLevel string

	// Claude OAuth account metadata (from stored tokens, replaces .claude.json)
	UserID           string // Reliant (Supabase) user ID for device ID generation
	AccountUUID      string
	AccountEmail     string
	OrganizationUUID string

	// TokenRefresher is an optional callback that coordinates an OAuth
	// access-token refresh. It receives the token state the caller currently
	// holds and returns the state to use going forward — which may be freshly
	// refreshed tokens, or newer tokens that another goroutine/process already
	// rotated and persisted (OAuth refresh tokens are single-use, so
	// uncoordinated concurrent refreshes kill the session). Implementations
	// must be safe for concurrent use.
	TokenRefresher func(held OAuthTokens) (OAuthTokens, error)
	// TokenReloader is an optional callback that returns the currently
	// persisted OAuth tokens, or nil if none are stored. Drivers use it to
	// recover from a 401 caused by another process rotating the tokens after
	// this driver loaded its credentials.
	TokenReloader func() (*OAuthTokens, error)
	// RefreshToken is the OAuth refresh token used by TokenRefresher.
	RefreshToken string
	// TokenExpiresAt is when the current access token expires.
	TokenExpiresAt time.Time
}

// OAuthTokens is a snapshot of OAuth credentials held by a driver that
// supports transparent token refresh (currently Claude OAuth).
type OAuthTokens struct {
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
}
