// Copyright (c) 2025 Reliant Labs
//
// Keyboard shortcuts generator - generates TypeScript and Markdown from YAML source of truth.
//
// SOURCE OF TRUTH: config/shortcuts.yaml
//
// GENERATED FILES:
//   - web/src/store/shortcutsData.generated.ts
//   - generated/docs-source/settings/keyboard-shortcuts.generated.md
//
// Usage: go run ./tools/docgen/shortcuts <yaml_file> <ts_output> <md_output>

package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// ShortcutsConfig represents the YAML structure
type ShortcutsConfig struct {
	Categories []string   `yaml:"categories"`
	Shortcuts  []Shortcut `yaml:"shortcuts"`
}

// Shortcut represents a single keyboard shortcut
type Shortcut struct {
	ID          string `yaml:"id"`
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
	Category    string `yaml:"category"`
	Binding     string `yaml:"binding"`
	Handler     string `yaml:"handler"`
}

// ParsedBinding represents a parsed key binding
type ParsedBinding struct {
	Key   string
	Cmd   bool // Cmd on Mac, Ctrl on Windows
	Ctrl  bool // Always Ctrl (for Cmd+Ctrl bindings)
	Shift bool
	Alt   bool
}

func main() {
	if len(os.Args) < 4 {
		fmt.Fprintf(os.Stderr, "Usage: %s <yaml_file> <ts_output> <md_output>\n", os.Args[0])
		os.Exit(1)
	}

	yamlFile := os.Args[1]
	tsOutput := os.Args[2]
	mdOutput := os.Args[3]

	// Read and parse YAML
	data, err := os.ReadFile(yamlFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading YAML: %v\n", err)
		os.Exit(1)
	}

	var config ShortcutsConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing YAML: %v\n", err)
		os.Exit(1)
	}

	// Generate TypeScript
	ts := generateTypeScript(config)
	if err := os.WriteFile(tsOutput, []byte(ts), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing TypeScript: %v\n", err)
		os.Exit(1)
	}

	// Generate Markdown
	md := generateMarkdown(config)
	if err := os.WriteFile(mdOutput, []byte(md), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing Markdown: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated shortcuts: %s (%d shortcuts), %s\n", tsOutput, len(config.Shortcuts), mdOutput)
}

func parseBinding(binding string) ParsedBinding {
	p := ParsedBinding{}

	// Handle simple keys without modifiers
	if !strings.Contains(binding, "+") {
		p.Key = binding
		return p
	}

	parts := strings.Split(binding, "+")
	for i, part := range parts {
		part = strings.TrimSpace(part)
		if i == len(parts)-1 {
			// Last part is the key
			p.Key = part
		} else {
			// Modifier
			switch part {
			case "Cmd":
				p.Cmd = true
			case "Ctrl":
				p.Ctrl = true
			case "Shift":
				p.Shift = true
			case "Alt":
				p.Alt = true
			}
		}
	}

	return p
}

func generateTypeScript(config ShortcutsConfig) string {
	var sb strings.Builder

	sb.WriteString(`// =============================================================================
// GENERATED FILE - DO NOT EDIT DIRECTLY
// =============================================================================
//
// Source of truth: config/shortcuts.yaml
// Generated by: go run ./tools/docgen/shortcuts
// Regenerate with: make generate-shortcuts
//
// This file contains the default keyboard shortcut definitions.
// =============================================================================

import type { KeyBinding, ShortcutDefinition } from './shortcutsStore';

// Helper function to create cross-platform key bindings (Cmd on Mac, Ctrl on Windows)
function createCrossPlatformBinding(key: string, options: { shift?: boolean; alt?: boolean } = {}): KeyBinding {
  const isMac = typeof window !== 'undefined' && 
    (window.navigator.platform.toUpperCase().includes('MAC') || 
     window.navigator.userAgent.toUpperCase().includes('MAC'));
  
  return {
    key,
    meta: isMac,
    ctrl: !isMac,
    shift: options.shift,
    alt: options.alt
  };
}

// Helper function to create Cmd+Ctrl bindings (Cmd+Ctrl on Mac, Ctrl+Alt on Windows)
function createCmdCtrlBinding(key: string, options: { shift?: boolean } = {}): KeyBinding {
  const isMac = typeof window !== 'undefined' && 
    (window.navigator.platform.toUpperCase().includes('MAC') || 
     window.navigator.userAgent.toUpperCase().includes('MAC'));
  
  return {
    key,
    meta: isMac,
    ctrl: true,
    alt: !isMac,
    shift: options.shift
  };
}

/**
 * Default keyboard shortcuts.
 * 
 * Categories:
`)

	for _, cat := range config.Categories {
		sb.WriteString(fmt.Sprintf(" *   - %s\n", cat))
	}

	sb.WriteString(` */
export const defaultShortcuts: Record<string, Omit<ShortcutDefinition, 'currentBinding'>> = {
`)

	for i, s := range config.Shortcuts {
		p := parseBinding(s.Binding)

		// Determine binding type and generate code
		var bindingCode string
		if !p.Cmd && !p.Ctrl && !p.Shift && !p.Alt {
			// Simple key
			bindingCode = fmt.Sprintf("{ key: '%s' }", p.Key)
		} else if p.Cmd && p.Ctrl {
			// Cmd+Ctrl style
			opts := ""
			if p.Shift {
				opts = ", { shift: true }"
			}
			bindingCode = fmt.Sprintf("createCmdCtrlBinding('%s'%s)", p.Key, opts)
		} else if p.Cmd {
			// Cross-platform style
			opts := []string{}
			if p.Shift {
				opts = append(opts, "shift: true")
			}
			if p.Alt {
				opts = append(opts, "alt: true")
			}
			if len(opts) > 0 {
				bindingCode = fmt.Sprintf("createCrossPlatformBinding('%s', { %s })", p.Key, strings.Join(opts, ", "))
			} else {
				bindingCode = fmt.Sprintf("createCrossPlatformBinding('%s')", p.Key)
			}
		} else {
			// Direct binding
			parts := []string{fmt.Sprintf("key: '%s'", p.Key)}
			if p.Ctrl {
				parts = append(parts, "ctrl: true")
			}
			if p.Shift {
				parts = append(parts, "shift: true")
			}
			if p.Alt {
				parts = append(parts, "alt: true")
			}
			bindingCode = fmt.Sprintf("{ %s }", strings.Join(parts, ", "))
		}

		sb.WriteString(fmt.Sprintf(`  %s: {
    id: '%s',
    name: '%s',
    description: '%s',
    category: '%s',
    defaultBinding: %s,
    handler: '%s'
  }`, s.ID, s.ID, escapeJS(s.Name), escapeJS(s.Description), s.Category, bindingCode, s.Handler))

		if i < len(config.Shortcuts)-1 {
			sb.WriteString(",")
		}
		sb.WriteString("\n")
	}

	sb.WriteString(`};
`)

	return sb.String()
}

func escapeJS(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	return s
}

func generateMarkdown(config ShortcutsConfig) string {
	var sb strings.Builder

	sb.WriteString(`---
title: "Keyboard Shortcuts"
description: "Default keyboard shortcuts for Reliant"
weight: 60
---

<!-- =============================================================================
     GENERATED FILE - DO NOT EDIT DIRECTLY
     
     Source of truth: config/shortcuts.yaml
     Generated by: go run ./tools/docgen/shortcuts
     Regenerate with: make generate-shortcuts
     ============================================================================= -->

Reliant includes keyboard shortcuts for common actions. All shortcuts can be customized in Settings → Keyboard Shortcuts.

`)

	// Group by category
	byCategory := make(map[string][]Shortcut)
	for _, s := range config.Shortcuts {
		byCategory[s.Category] = append(byCategory[s.Category], s)
	}

	// Output in category order
	for _, cat := range config.Categories {
		shortcuts := byCategory[cat]
		if len(shortcuts) == 0 {
			continue
		}

		sb.WriteString(fmt.Sprintf("## %s\n\n", cat))
		sb.WriteString("| Shortcut | Action |\n")
		sb.WriteString("|----------|--------|\n")

		// Sort by name within category
		sort.Slice(shortcuts, func(i, j int) bool {
			return shortcuts[i].Name < shortcuts[j].Name
		})

		for _, s := range shortcuts {
			displayBinding := formatBindingForDocs(s.Binding)
			sb.WriteString(fmt.Sprintf("| `%s` | %s |\n", displayBinding, s.Name))
		}
		sb.WriteString("\n")
	}

	sb.WriteString(`## Customizing Shortcuts

To customize keyboard shortcuts:

1. Open Settings (` + "`Cmd+,`" + `)
2. Navigate to Keyboard Shortcuts
3. Click any shortcut to rebind it
4. Press your desired key combination
5. Click Save

Use the Reset button to restore default shortcuts.
`)

	return sb.String()
}

func formatBindingForDocs(binding string) string {
	// Convert to display format (e.g., "Cmd+Shift+T")
	// Already in correct format from YAML
	return binding
}
