// Copyright (c) 2025 Reliant Labs
//
// Keyboard shortcuts generator - generates TypeScript and Markdown from YAML source of truth.
//
// SOURCE OF TRUTH: config/shortcuts.yaml
//
// GENERATED FILES:
//   - web/src/store/shortcutsData.generated.ts
//   - generated/docs-source/settings/keyboard-shortcuts.generated.md
//
// Usage: go run ./tools/docgen/shortcuts <yaml_file> <ts_output> <md_output>

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// ShortcutsConfig represents the YAML structure
type ShortcutsConfig struct {
	Categories []string   `yaml:"categories"`
	Shortcuts  []Shortcut `yaml:"shortcuts"`
}

// Shortcut represents a single keyboard shortcut.
//
// Binding is the desktop (Electron) default. WebBinding overrides it in a
// browser tab, where many chords are reserved — see config/shortcuts.yaml for
// the conflict rules. When WebBinding is empty the same chord is used on both.
type Shortcut struct {
	ID          string `yaml:"id"`
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
	Category    string `yaml:"category"`
	Binding     string `yaml:"binding"`
	WebBinding  string `yaml:"web_binding"`
	Handler     string `yaml:"handler"`
	// Context names the focus surface this shortcut belongs to. Defaults to
	// "global" when omitted.
	Context string `yaml:"context"`
	// AllowInInput lets an unmodified binding fire while the user is typing.
	AllowInInput bool `yaml:"allow_in_input"`
	// Passthrough handles the chord without consuming it.
	Passthrough bool `yaml:"passthrough"`
}

// Context returns the declared context, defaulting to "global".
func (s Shortcut) EffectiveContext() string {
	if s.Context == "" {
		return "global"
	}
	return s.Context
}

// EffectiveWebBinding returns the browser binding, falling back to the desktop
// one when no override is declared.
func (s Shortcut) EffectiveWebBinding() string {
	if s.WebBinding == "" {
		return s.Binding
	}
	return s.WebBinding
}

// ParsedBinding represents a parsed key binding
type ParsedBinding struct {
	Key   string
	Cmd   bool // Cmd on Mac, Ctrl on Windows
	Ctrl  bool // Always Ctrl (for Cmd+Ctrl bindings)
	Shift bool
	Alt   bool
}

func main() {
	if len(os.Args) < 4 {
		fmt.Fprintf(os.Stderr, "Usage: %s <yaml_file> <ts_output> <md_output>\n", os.Args[0])
		os.Exit(1)
	}

	yamlFile := os.Args[1]
	tsOutput := os.Args[2]
	mdOutput := os.Args[3]

	// Read and parse YAML
	data, err := os.ReadFile(yamlFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading YAML: %v\n", err)
		os.Exit(1)
	}

	var config ShortcutsConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing YAML: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(tsOutput), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating TypeScript output directory: %v\n", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(filepath.Dir(mdOutput), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating Markdown output directory: %v\n", err)
		os.Exit(1)
	}

	// Generate TypeScript
	ts := generateTypeScript(config)
	if err := os.MkdirAll(filepath.Dir(tsOutput), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating directory for TypeScript output: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(tsOutput, []byte(ts), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing TypeScript: %v\n", err)
		os.Exit(1)
	}

	// Generate Markdown
	md := generateMarkdown(config)
	if err := os.MkdirAll(filepath.Dir(mdOutput), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating directory for Markdown output: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(mdOutput, []byte(md), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing Markdown: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated shortcuts: %s (%d shortcuts), %s\n", tsOutput, len(config.Shortcuts), mdOutput)
}

func parseBinding(binding string) ParsedBinding {
	p := ParsedBinding{}

	// Handle simple keys without modifiers
	if !strings.Contains(binding, "+") {
		p.Key = binding
		return p
	}

	parts := strings.Split(binding, "+")
	for i, part := range parts {
		part = strings.TrimSpace(part)
		if i == len(parts)-1 {
			// Last part is the key
			p.Key = part
		} else {
			// Modifier
			switch part {
			case "Cmd":
				p.Cmd = true
			case "Ctrl":
				p.Ctrl = true
			case "Shift":
				p.Shift = true
			case "Alt":
				p.Alt = true
			}
		}
	}

	return p
}

func generateTypeScript(config ShortcutsConfig) string {
	var sb strings.Builder

	sb.WriteString(`// =============================================================================
// GENERATED FILE - DO NOT EDIT DIRECTLY
// =============================================================================
//
// Source of truth: config/shortcuts.yaml
// Generated by: go run ./tools/docgen/shortcuts
// Regenerate with: make generate-shortcuts
//
// This file contains the default keyboard shortcut definitions.
// =============================================================================

import type { ShortcutDefinition } from './shortcutsStore';

/**
 * Default keyboard shortcuts.
 *
 * Bindings are authored strings ("Cmd+Shift+P", "Cmd+K C") rather than
 * pre-resolved modifier objects. Platform folding (Cmd to Meta on macOS, to
 * Control elsewhere) happens at load time in parseBinding(), so one definition
 * serves every platform and sequences stay readable.
 *
 * Categories:
`)

	for _, cat := range config.Categories {
		fmt.Fprintf(&sb, " *   - %s\n", cat)
	}

	sb.WriteString(` */
export const defaultShortcuts: Record<string, Omit<ShortcutDefinition, 'currentBinding'>> = {
`)

	for i, s := range config.Shortcuts {
		fmt.Fprintf(&sb, `  %s: {
    id: '%s',
    name: '%s',
    description: '%s',
    category: '%s',
    defaultBinding: '%s',
    defaultWebBinding: '%s',
    context: '%s',
    handler: '%s'`,
			s.ID, s.ID, escapeJS(s.Name), escapeJS(s.Description), s.Category,
			escapeJS(s.Binding), escapeJS(s.EffectiveWebBinding()),
			s.EffectiveContext(), s.Handler)

		if s.AllowInInput {
			sb.WriteString(",\n    allowInInput: true")
		}
		if s.Passthrough {
			sb.WriteString(",\n    passthrough: true")
		}

		sb.WriteString("\n  }")

		if i < len(config.Shortcuts)-1 {
			sb.WriteString(",")
		}
		sb.WriteString("\n")
	}

	sb.WriteString(`};
`)

	return sb.String()
}

func escapeJS(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	return s
}

func generateMarkdown(config ShortcutsConfig) string {
	var sb strings.Builder

	sb.WriteString(`---
title: "Keyboard Shortcuts"
description: "Default keyboard shortcuts for Reliant"
weight: 60
---

<!-- =============================================================================
     GENERATED FILE - DO NOT EDIT DIRECTLY
     
     Source of truth: config/shortcuts.yaml
     Generated by: go run ./tools/docgen/shortcuts
     Regenerate with: make generate-shortcuts
     ============================================================================= -->

Reliant includes keyboard shortcuts for common actions. All shortcuts can be customized in Settings → Keyboard Shortcuts.

Some shortcuts differ between the desktop app and the browser. Browsers reserve
chords like ` + "`Cmd+T`" + ` and ` + "`Cmd+W`" + ` for their own tabs and windows and will not
release them to a web page, so those actions use a ` + "`Cmd+K`" + ` prefix on the web.
Where the **Browser** column is blank the shortcut is the same on both.

`)

	// Group by category
	byCategory := make(map[string][]Shortcut)
	for _, s := range config.Shortcuts {
		byCategory[s.Category] = append(byCategory[s.Category], s)
	}

	// Output in category order
	for _, cat := range config.Categories {
		shortcuts := byCategory[cat]
		if len(shortcuts) == 0 {
			continue
		}

		fmt.Fprintf(&sb, "## %s\n\n", cat)
		sb.WriteString("| Desktop | Browser | Action |\n")
		sb.WriteString("|---------|---------|--------|\n")

		// Sort by name within category
		sort.Slice(shortcuts, func(i, j int) bool {
			return shortcuts[i].Name < shortcuts[j].Name
		})

		for _, s := range shortcuts {
			desktop := fmt.Sprintf("`%s`", formatBindingForDocs(s.Binding))
			web := ""
			if s.WebBinding != "" && s.WebBinding != s.Binding {
				web = fmt.Sprintf("`%s`", formatBindingForDocs(s.WebBinding))
			}
			fmt.Fprintf(&sb, "| %s | %s | %s |\n", desktop, web, s.Name)
		}
		sb.WriteString("\n")
	}

	sb.WriteString(`## Customizing Shortcuts

To customize keyboard shortcuts:

1. Open Settings (` + "`Cmd+,`" + `)
2. Navigate to Keyboard Shortcuts
3. Click any shortcut to rebind it
4. Press your desired key combination
5. Click Save

Use the Reset button to restore default shortcuts.
`)

	return sb.String()
}

func formatBindingForDocs(binding string) string {
	// Convert to display format (e.g., "Cmd+Shift+T")
	// Already in correct format from YAML
	return binding
}
