// Copyright (c) 2025 Reliant Labs
//
// Tool reference generator - uses the tool registry directly.
//
// SOURCE OF TRUTH:
//   - internal/llm/tools.GetToolRegistry() (the actual registry)
//
// GENERATED FILES:
//   - generated/docs-source/reference/tools.md
//
// Usage: go run ./tools/docgen/tools <output>
// Regenerate with: make generate-tools-ref

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/reliant-labs/reliant/internal/llm/tools"
)

// ToolInfo holds extracted tool metadata
type ToolInfo struct {
	Name        string
	Description string
	Tags        []string
	ParamSchema string // JSON schema as string
}

// TagInfo holds tag metadata
type TagInfo struct {
	Name        string
	Description string
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: %s <output>\n", os.Args[0])
		os.Exit(1)
	}

	output := os.Args[1]

	toolInfos, tagInfos := extractFromRegistry()
	markdown := generateMarkdown(toolInfos, tagInfos, true)
	if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating directory: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(output, []byte(markdown), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated tool reference: %s, (%d tools, %d tags)\n",
		output, len(toolInfos), len(tagInfos))
}

func extractFromRegistry() ([]ToolInfo, []TagInfo) {
	registry := tools.GetToolRegistry()

	// Create minimal factory for instantiation (only needs schema, not Run())
	factory := tools.NewToolsFactory(&tools.ToolsOptions{})

	var toolInfos []ToolInfo

	for _, def := range registry {
		// Instantiate tool to get Description and ParamSchema
		tool := def.Factory(factory)

		// Convert tags to strings
		var tagStrs []string
		for _, t := range def.Tags {
			tagStrs = append(tagStrs, string(t))
		}

		// Get param schema as JSON
		var paramSchemaJSON string
		if schema := tool.ParamSchema(); schema != nil {
			if b, err := json.MarshalIndent(schema, "", "  "); err == nil {
				paramSchemaJSON = string(b)
			}
		}

		toolInfos = append(toolInfos, ToolInfo{
			Name:        tool.Name(),
			Description: tool.Description(),
			Tags:        tagStrs,
			ParamSchema: paramSchemaJSON,
		})
	}

	// Sort by name
	sort.Slice(toolInfos, func(i, j int) bool {
		return toolInfos[i].Name < toolInfos[j].Name
	})

	// Build tag info from known tags
	tagInfos := []TagInfo{
		{Name: "readonly", Description: "Read-only tools (safe for planning mode)"},
		{Name: "plan", Description: "Planning mode tools (read-only + planning tools)"},
		{Name: "file", Description: "File operations"},
		{Name: "search", Description: "Search operations"},
		{Name: "execution", Description: "Command execution"},
		{Name: "shell", Description: "Shell tools (bash on Unix, powershell on Windows)"},
		{Name: "web", Description: "Web operations"},
		{Name: "planning", Description: "Planning and task management tools"},
		{Name: "analysis", Description: "Analysis tools"},
		{Name: "workflow", Description: "Workflow builder tools"},
		{Name: "mcp", Description: "All MCP tools"},
		{Name: "default", Description: "Default toolset (commonly used tools)"},
	}

	return toolInfos, tagInfos
}

func generateMarkdown(toolInfos []ToolInfo, tagInfos []TagInfo, withHugoFrontmatter bool) string {
	var sb strings.Builder

	if withHugoFrontmatter {
		sb.WriteString(`---
# =============================================================================
# GENERATED FILE - DO NOT EDIT DIRECTLY
#
# Source of truth: internal/llm/tools.GetToolRegistry()
# Generated by: go run ./tools/docgen/tools
# Regenerate with: make generate-tools-ref
# =============================================================================
title: Tools Quick Reference
weight: 25
description: Auto-generated quick reference for all tools (tags, names, descriptions)
---

`)
	} else {
		sb.WriteString(`<!-- =============================================================================
     GENERATED FILE - DO NOT EDIT DIRECTLY
     
     Source of truth: internal/llm/tools.GetToolRegistry()
     Generated by: go run ./tools/docgen/tools
     Regenerate with: make generate-tools-ref
     ============================================================================= -->

`)
	}

	if !withHugoFrontmatter {
		sb.WriteString("# Tools Quick Reference\n\n")
	}

	sb.WriteString("This reference lists all available tools organized by category.\n\n")

	// Render Tag Reference
	sb.WriteString("## Tool Tags\n\n")
	sb.WriteString("Tools are organized by tags for filtering:\n\n")
	sb.WriteString("| Tag | Description |\n")
	sb.WriteString("|-----|-------------|\n")
	for _, tag := range tagInfos {
		fmt.Fprintf(&sb, "| `tag:%s` | %s |\n", tag.Name, tag.Description)
	}
	sb.WriteString("\n---\n\n")

	// Define categories and their filters
	type Category struct {
		Name        string
		Anchor      string
		Description string
		Filter      func(tags []string) bool
		Tools       []ToolInfo
	}

	categories := []*Category{
		{
			Name:        "Planning & Task Management",
			Anchor:      "planning--task-management",
			Description: "Tools for creating plans, managing tasks, and tracking progress.",
			Filter:      func(tags []string) bool { return contains(tags, "planning") || contains(tags, "plan") },
		},
		{
			Name:        "File Operations",
			Anchor:      "file-operations",
			Description: "Tools for reading, writing, and modifying files.",
			Filter:      func(tags []string) bool { return contains(tags, "file") },
		},
		{
			Name:        "Information Retrieval",
			Anchor:      "information-retrieval",
			Description: "Tools for searching code, finding files, and fetching external content.",
			Filter: func(tags []string) bool {
				return contains(tags, "search") || contains(tags, "web") || contains(tags, "analysis")
			},
		},
		{
			Name:        "Workflow Management",
			Anchor:      "workflow-management",
			Description: "Tools for managing and inspecting workflows, presets, and scenarios.",
			Filter:      func(tags []string) bool { return contains(tags, "workflow") },
		},
		{
			Name:        "System & Execution",
			Anchor:      "system--execution",
			Description: "Tools for executing shell commands and managing system processes.",
			Filter:      func(tags []string) bool { return contains(tags, "execution") || contains(tags, "shell") },
		},
		{
			Name:        "Other Tools",
			Anchor:      "other-tools",
			Description: "Miscellaneous tools and utilities.",
			Filter:      func(tags []string) bool { return true }, // Catch-all
		},
	}

	// Assign tools to categories (first match wins to avoid duplicates)
	assigned := make(map[string]bool)
	for _, cat := range categories {
		for _, tool := range toolInfos {
			if assigned[tool.Name] {
				continue
			}
			if cat.Filter(tool.Tags) {
				cat.Tools = append(cat.Tools, tool)
				assigned[tool.Name] = true
			}
		}
	}

	// 1. Quick Links (Table of Contents)
	sb.WriteString("## Categories\n\n")
	for _, cat := range categories {
		if len(cat.Tools) == 0 {
			continue
		}
		fmt.Fprintf(&sb, "- [%s](#%s) (%d tools)\n", cat.Name, cat.Anchor, len(cat.Tools))
	}
	sb.WriteString("\n---\n\n")

	// 2. Render Categories
	for _, cat := range categories {
		if len(cat.Tools) == 0 {
			continue
		}

		// Section Header
		fmt.Fprintf(&sb, "## %s\n\n", cat.Name)
		if cat.Description != "" {
			fmt.Fprintf(&sb, "_%s_\n\n", cat.Description)
		}

		// Summary Table
		sb.WriteString("| Tool | Tags | Description |\n")
		sb.WriteString("|------|------|-------------|\n")
		for _, tool := range cat.Tools {
			shortDesc := getShortDescription(tool.Description)
			tagsStr := strings.Join(tool.Tags, ", ")
			if tagsStr == "" {
				tagsStr = "-"
			}
			// Link to the details anchor below
			fmt.Fprintf(&sb, "| [`%s`](#%s) | %s | %s |\n",
				tool.Name,
				strings.ToLower(tool.Name),
				tagsStr,
				shortDesc,
			)
		}
		sb.WriteString("\n")

		// Tool Details for this category
		for _, tool := range cat.Tools {
			fmt.Fprintf(&sb, "### %s\n\n", tool.Name)
			if len(tool.Tags) > 0 {
				fmt.Fprintf(&sb, "**Tags:** `%s`\n\n", strings.Join(tool.Tags, "`, `"))
			}

			if tool.Description != "" {
				sb.WriteString(cleanDescription(tool.Description))
				sb.WriteString("\n\n")
			}
			sb.WriteString("---\n\n")
		}
	}

	return sb.String()
}

func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}

func getShortDescription(desc string) string {
	if desc == "" {
		return "-"
	}

	// Get first line or first sentence
	lines := strings.Split(desc, "\n")
	firstLine := strings.TrimSpace(lines[0])

	// Truncate if too long
	if len(firstLine) > 100 {
		firstLine = firstLine[:97] + "..."
	}

	// Escape pipe characters for markdown tables
	firstLine = strings.ReplaceAll(firstLine, "|", "\\|")

	return cleanEmojis(firstLine)
}

func cleanDescription(desc string) string {
	// Remove emojis
	desc = cleanEmojis(desc)

	// Replace custom tags with markdown code blocks
	desc = strings.ReplaceAll(desc, "<good-example>", "```bash")
	desc = strings.ReplaceAll(desc, "</good-example>", "```")
	desc = strings.ReplaceAll(desc, "<bad-example>", "```bash")
	desc = strings.ReplaceAll(desc, "</bad-example>", "```")

	// Process line by line for other formatting
	lines := strings.Split(desc, "\n")
	var newLines []string

	for _, line := range lines {
		// Fix headers - convert # to #### to avoid conflicting with page structure
		if strings.HasPrefix(line, "# ") {
			newLines = append(newLines, "#### "+strings.TrimPrefix(line, "# "))
			continue
		}

		newLines = append(newLines, line)
	}

	return strings.Join(newLines, "\n")
}

func cleanEmojis(s string) string {
	// Remove common emojis used in tool descriptions
	s = strings.ReplaceAll(s, "❌ ", "")
	s = strings.ReplaceAll(s, "❌", "")
	s = strings.ReplaceAll(s, "✓ ", "")
	s = strings.ReplaceAll(s, "✓", "")
	s = strings.ReplaceAll(s, "✗ ", "")
	s = strings.ReplaceAll(s, "✗", "")
	// Additional emojis found in edit tool
	s = strings.ReplaceAll(s, "🎯 ", "")
	s = strings.ReplaceAll(s, "🎯", "")
	s = strings.ReplaceAll(s, "💡 ", "")
	s = strings.ReplaceAll(s, "💡", "")
	s = strings.ReplaceAll(s, "🔄 ", "")
	s = strings.ReplaceAll(s, "🔄", "")
	s = strings.ReplaceAll(s, "📝 ", "")
	s = strings.ReplaceAll(s, "📝", "")
	s = strings.ReplaceAll(s, "□ ", "")
	s = strings.ReplaceAll(s, "□", "")
	return s
}
